---
trigger: none
pr: none

resources:
  pipelines:
    - pipeline: PolarisAlertingBuild
      source: Polaris Alerting - Build
      trigger:
        branches:
          include:
            - refs/heads/main
        stages:
          - Publish_Artifacts
            
variables:
  - group: kv-dev-terraform
  - group: kv-qa-terraform
  - group: kv-prod-terraform
  - group: polaris-global
  - group: terraform-containers
    
pool:
  vmImage: ubuntu-latest

stages:
  - stage: Apply_DEV
    displayName: DEV > Apply Terraform
    jobs:
      - deployment: Apply_Alerting_Terraform
        environment: "Dev"
        workspace:
          clean: all
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../tasks/task_get-credentials.yml
                  parameters:
                    azureSubscription: $(dev-azure-subscription)
                    
                - template: ../tasks/task_apply-alerting-terraform.yml
                  parameters:
                    targetBuild: PolarisAlertingBuild
                    targetTerraformArtifact: "alerting-terraform-files"
                    targetLabel: "DEV"
                    targetName: "Alerting Terraform CI Deployment"
                    targetPlanName: "dev"
                    terraformStorageAccount: $(dev-terraform-storage-account)
                    terraformContainerName: $(alerting-terraform-container-name)
                    terraformStateKey: $(terraform-key)
                    terraformStateAccessKey: $(cpsdevstorageterraform-key1)
                    armClientId: $(clientId)
                    armClientSecret: $(clientSecret)
                    armTenantId: $(tenantId)
                    armSubscriptionId: $(subscriptionId)
                    
  # QA Apply to QA
  - stage: Apply_QA
    displayName: QA > Apply Terraform
    dependsOn: Apply_DEV
    condition: succeeded()
    jobs:
      - deployment: Apply_Alerting_Terraform
        environment: "QA"
        workspace:
          clean: all
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../tasks/task_get-credentials.yml
                  parameters:
                    azureSubscription: $(qa-azure-subscription)
                    
                - template: ../tasks/task_apply-alerting-terraform.yml
                  parameters:
                    targetBuild: PolarisAlertingBuild
                    targetTerraformArtifact: "alerting-terraform-files"
                    targetLabel: "QA"
                    targetName: "Alerting Terraform CI Deployment"
                    targetPlanName: "qa"
                    terraformStorageAccount: $(qa-terraform-storage-account)
                    terraformContainerName: $(alerting-terraform-container-name)
                    terraformStateKey: $(terraform-key)
                    terraformStateAccessKey: $(cpsqastorageterraform-key1)
                    armClientId: $(clientId)
                    armClientSecret: $(clientSecret)
                    armTenantId: $(tenantId)
                    armSubscriptionId: $(subscriptionId)
                    
  # Apply to PROD              
  - stage: Apply_PROD
    displayName: PROD > Apply Terraform
    dependsOn: Apply_DEV
    condition: succeeded()
    jobs:
      - deployment: Apply_Alerting_Terraform
        environment: "Prod"
        workspace:
          clean: all
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../tasks/task_get-credentials.yml
                  parameters:
                    azureSubscription: $(prod-azure-subscription)
                    
                - template: ../tasks/task_apply-alerting-terraform.yml
                  parameters:
                    targetBuild: PolarisAlertingBuild
                    targetTerraformArtifact: "alerting-terraform-files"
                    targetLabel: "PROD"
                    targetName: "Alerting Terraform CI Deployment"
                    targetPlanName: "prod"
                    terraformStorageAccount: $(prod-terraform-storage-account)
                    terraformContainerName: $(alerting-terraform-container-name)
                    terraformStateKey: $(terraform-key)
                    terraformStateAccessKey: $(cpsprodstorageterraform-key1)
                    armClientId: $(clientId)
                    armClientSecret: $(clientSecret)
                    armTenantId: $(tenantId)
                    armSubscriptionId: $(subscriptionId)
