# Quick and dirty test pipeline to explore potential scripts

trigger: none
pr: none

variables:
  - group: kv-dev-terraform
  - group: polaris-global
  - group: pipeline-terraform
  - group: ui-terraform

stages:
  - stage: Run_Script
    displayName: Test > Script
    pool:
      name: $(dev-build-agent)
    jobs:
      - job: Execute
        steps:
          # Set Log Analytics Archival Period - remove when supported natively by Terraform
          - bash: |
              az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID
              az monitor log-analytics workspace table update --resource-group rg-polaris-analytics-dev --workspace-name la-polaris-dev --name AppEvents --retention-time $LOG_RETENTION_TIME --total-retention-time $TOTAL_LOG_RETENTION_TIME --subscription $ARM_SUBSCRIPTION_ID
              az monitor log-analytics workspace table update --resource-group rg-polaris-analytics-dev --workspace-name la-polaris-dev --name AppRequests --retention-time $LOG_RETENTION_TIME --total-retention-time $TOTAL_LOG_RETENTION_TIME --subscription $ARM_SUBSCRIPTION_ID
              az monitor log-analytics workspace table update --resource-group rg-polaris-analytics-dev --workspace-name la-polaris-dev --name AppServiceConsoleLogs --retention-time $LOG_RETENTION_TIME --total-retention-time $TOTAL_LOG_RETENTION_TIME --subscription $ARM_SUBSCRIPTION_ID
            displayName: Script > Set Log Analytics Archival Periods
            env:
              ARM_CLIENT_ID: $(innovation-development-spn-client-id)
              ARM_CLIENT_SECRET: $(innovation-development-spn-secret)
              ARM_TENANT_ID: $(innovation-development-spn-tenant-id)
              ARM_SUBSCRIPTION_ID: $(innovation-development-subscription-id)
              LOG_RETENTION_TIME: $(log-retention-time)
              TOTAL_LOG_RETENTION_TIME: $(total-log-retention-time)
