# Build and Publish Artifact Azure DevOps pipeline for Pipeline Terraform, following commit

name: '$(majorMinorVersion).$(Year:yy)$(DayOfYear).$(semanticVersion)'

trigger:
  batch: true
  branches:
    include:
      - main
  
  paths:
    include:
      - "polaris-terraform/pipeline-terraform/*"

variables:
  majorMinorVersion: 1.0
  semanticVersion: $[counter(variables['majorMinorVersion'], 1)]

stages:
  - stage: Publish_Terraform
    displayName: Create a Build
    jobs:
      - job:
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: PublishPipelineArtifact@1
            displayName: 'Publish Terraform Artifacts'
            inputs:
              targetPath: '$(Pipeline.Workspace)/s/polaris-terraform/pipeline-terraform/'
              artifact: 'pipeline-terraform-files'
              publishLocation: 'pipeline'