# Pull Request Azure DevOps pipeline for Pipeline Terraform - actual trigger defined in Azure DevOps via build policy

trigger: none

variables:
  - group: kv-dev-terraform
  - group: polaris-global
  - group: pipeline-terraform

stages:
  - template: templates/terraform-adv-validation.yml # Validate
    parameters:
      terraformVersion: $(terraform-version)
      terraformStorageAccount: $(dev-terraform-storage-account)
      terraformContainerName: $(pipeline-terraform-container-name)
      terraformStateKey: $(terraform-key)
      terraformAccessKey: $(cpsdevstorageterraform-key1)
      workingDirectory: "$(System.DefaultWorkingDirectory)/polaris-terraform/pipeline-terraform/"
      rulesToSkip: $(checkov-rules-to-skip)

  - template: templates/terraform-plan-nopub.yml # Plan DEV
    parameters:
      name: 'DEV'
      buildAgent: $(dev-build-agent)
      terraformVersion: $(terraform-version)
      terraformStorageAccount: $(dev-terraform-storage-account)
      terraformContainerName: $(pipeline-terraform-container-name)
      terraformStateKey: $(terraform-key)
      terraformAccessKey: $(cpsdevstorageterraform-key1)
      workingDirectory: "$(System.DefaultWorkingDirectory)/polaris-terraform/pipeline-terraform/"
      planName: 'dev'
      spnClientId: $(innovation-development-spn-client-id)
      spnClientSecret: $(innovation-development-spn-secret)
      spnTenantId: $(innovation-development-spn-tenant-id)
      subscriptionId: $(innovation-development-subscription-id)