---
# Build and Publish Artifact Azure DevOps pipeline for Networking and Networking-Events Terraform files

name: '$(majorMinorVersion).$(Year:yy)$(DayOfYear).$(semanticVersion)-ci'

trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - polaris-terraform/networking-terraform/*

pr: none

variables:
  - group: polaris-global
  - name: buildConfiguration
    value: "Release"
  - name: majorMinorVersion
    value: "1.0"
  - name: semanticVersion
    value: "$[counter(variables['majorMinorVersion'], 1)]"

pool:
  name: $(dev-build-agent)

stages:
  - stage: Publish_Artifacts
    displayName: Publish artifacts
    jobs:
      - job:
        steps:
          - task: PublishPipelineArtifact@1
            displayName: 'Publish pipeline terraform artifact'
            inputs:
              targetPath: "$(Pipeline.Workspace)/s/polaris-terraform/networking-terraform/"
              artifact: "networking-terraform-files"
              publishLocation: "pipeline"
