# Build and Publish Artifact Azure DevOps pipeline for Networking and Networking-Events Terraform files

name: '$(majorMinorVersion).$(Year:yy)$(DayOfYear).$(semanticVersion)'

trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - polaris-terraform/networking-terraform/*
       
pr: none
  
variables:
  buildConfiguration: "Release"
  majorMinorVersion: 1.0
  semanticVersion: $[counter(variables['majorMinorVersion'], 1)]
    
stages:
  - stage: Publish_Artifacts
    displayName: Publish artifacts
    jobs:
      - job:
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: PublishPipelineArtifact@1
            displayName: 'Publish pipeline terraform artifact'
            inputs:
              targetPath: "$(Pipeline.Workspace)/s/polaris-terraform/networking-terraform/"
              artifact: "networking-terraform-files"
              publishLocation: "pipeline"