# Unified Build and Release Azure DevOps networking for the Networking and Networking-Events Terraform

trigger: none
pr: none

resources:
  pipelines:
    - pipeline: NetworkingBuild
      source: Polaris Networking - Build
      trigger:
        branches:
          include:
            - refs/heads/main
        stages:
          - Publish_Artifacts

variables:
  - group: kv-dev-terraform
  - group: kv-qa-terraform
  - group: kv-prod-terraform
  - group: polaris-global
  - group: networking-terraform
  - group: polaris-vpn

stages:
  - stage: Apply_DEV
    displayName: DEV Deployment
    pool:
      vmImage: ubuntu-latest
    jobs:
      - deployment: Networking_Terraform_Deployment
        environment: "Dev"
        strategy:
          runOnce:
            deploy:
              steps:
                #create vpn tunnel
                - bash: |
                    sudo apt-get --assume-yes --no-install-recommends install openvpn

                    chmod 777 vpnconfig.ovpn
                    envsubst < vpnconfig.ovpn > _vpnconfig.ovpn

                    sudo openvpn _vpnconfig.ovpn &

                    sleep 5

                    ifconfig tun0
                    sudo rm /etc/resolv.conf
                    echo "nameserver 10.7.197.20" | sudo tee /etc/resolv.conf

                    sudo cat openvpn.log

                    nslookup fa-polaris-dev-gateway.azurewebsites.net
                    nslookup fa-polaris-dev-gateway.azurewebsites.net 10.7.197.20

                    sudo cat /etc/resolv.conf
                  workingDirectory: $(Pipeline.Workspace)/NetworkingBuild/polaris-template-files
                  env:
                    PRESHAREDKEY: $(dev_pre-shared_key)
                    PRIVATEKEY: $(dev_private_key)
                    CLIENTCERTIFICATE: $(dev_client_cert)
                    VPNSERVER: $(dev_vpn_server)
                  displayName: Creating DEV VPN tunnel
                  
                # Install Terraform based on version variable
                - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
                  displayName: Terraform > Install
                  inputs:
                    terraformVersion: $(terraform-version)
                
                #download networking terraform build artifact
                - download: NetworkingBuild
                  displayName: Terraform > Download Networking terraform build
                  artifact: "networking-terraform-files"
                
                # Terraform Init
                - bash: |
                    terraform init \
                      -backend-config="storage_account_name=$TF_STATE_ACCOUNT_NAME" \
                      -backend-config="container_name=$TF_STATE_CONTAINER_NAME" \
                      -backend-config="key=$TF_STATE_KEY" \
                      -backend-config="access_key=$TF_STATE_ACCESS_KEY"
                  displayName: Terraform > Init
                  workingDirectory: $(Pipeline.Workspace)/NetworkingBuild/networking-terraform-files
                  env:
                    TF_STATE_ACCOUNT_NAME: $(dev-terraform-storage-account)
                    TF_STATE_CONTAINER_NAME: $(networking-terraform-container-name)
                    TF_STATE_KEY: $(terraform-key)
                    TF_STATE_ACCESS_KEY: $(cpsdevstorageterraform-key1)
                    TF_LOG: $(dev-log-level)
                
                # Terraform Plan
                - bash: |
                    terraform plan -input=false -out=dev.tfplan -var-file="dev.tfvars"
                  displayName: 'Terraform > Write Networking Plan'
                  workingDirectory: $(Pipeline.Workspace)/NetworkingBuild/networking-terraform-files
                  env:
                    ARM_CLIENT_ID: $(innovation-development-spn-client-id)
                    ARM_CLIENT_SECRET: $(innovation-development-spn-secret)
                    ARM_TENANT_ID: $(innovation-development-spn-tenant-id)
                    ARM_SUBSCRIPTION_ID: $(innovation-development-subscription-id)
                    TF_LOG: $(dev-log-level)
                
                # Terraform Apply
                - bash: |
                    terraform apply -auto-approve dev.tfplan
                  displayName: Terraform > Apply to DEV
                  workingDirectory: $(Pipeline.Workspace)/NetworkingBuild/networking-terraform-files
                  env:
                    ARM_CLIENT_ID: $(innovation-development-spn-client-id)
                    ARM_CLIENT_SECRET: $(innovation-development-spn-secret)
                    ARM_TENANT_ID: $(innovation-development-spn-tenant-id)
                    ARM_SUBSCRIPTION_ID: $(innovation-development-subscription-id)
                    TF_LOG: $(dev-log-level)
                    
  - stage: Apply_QA
    displayName: QA Deployment
    pool:
      vmImage: ubuntu-latest
    jobs:
      - deployment: Networking_Terraform_Deployment
        environment: "QA"
        strategy:
          runOnce:
            deploy:
              steps:
                #create vpn tunnel
                - bash: |
                    sudo apt-get --assume-yes --no-install-recommends install openvpn

                    chmod 777 vpnconfig.ovpn
                    envsubst < vpnconfig.ovpn > _vpnconfig.ovpn

                    sudo openvpn _vpnconfig.ovpn &

                    sleep 5

                    ifconfig tun0

                    sudo rm /etc/resolv.conf
                    echo "nameserver $DNSSERVER" | sudo tee /etc/resolv.conf
                  workingDirectory: $(Pipeline.Workspace)/NetworkingBuild/polaris-template-files
                  env:
                    PRESHAREDKEY: $(qa_pre-shared_key)
                    PRIVATEKEY: $(qa_private_key)
                    CLIENTCERTIFICATE: $(qa_client_cert)
                    VPNSERVER: $(qa_vpn_server)
                    DNSSERVER: $(qa_dns_server)
                  displayName: Creating QA VPN tunnel
                  
                # Install Terraform based on version variable
                - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
                  displayName: Terraform > Install
                  inputs:
                    terraformVersion: $(terraform-version)
                
                #download networking terraform build artifact
                - download: NetworkingBuild
                  displayName: Terraform > Download Networking terraform build
                  artifact: "networking-terraform-files"
                
                # Terraform Init
                - bash: |
                    terraform init \
                      -backend-config="storage_account_name=$TF_STATE_ACCOUNT_NAME" \
                      -backend-config="container_name=$TF_STATE_CONTAINER_NAME" \
                      -backend-config="key=$TF_STATE_KEY" \
                      -backend-config="access_key=$TF_STATE_ACCESS_KEY"
                  displayName: Terraform > Init
                  workingDirectory: $(Pipeline.Workspace)/NetworkingBuild/networking-terraform-files
                  env:
                    TF_STATE_ACCOUNT_NAME: $(qa-terraform-storage-account)
                    TF_STATE_CONTAINER_NAME: $(networking-terraform-container-name)
                    TF_STATE_KEY: $(terraform-key)
                    TF_STATE_ACCESS_KEY: $(cpsqastorageterraform-key1)
                    TF_LOG: $(qa-log-level)
                
                # Terraform Plan
                - bash: |
                    terraform plan -input=false -out=qa.tfplan -var-file="qa.tfvars"
                  displayName: 'Terraform > Write Networking Plan'
                  workingDirectory: $(Pipeline.Workspace)/NetworkingBuild/networking-terraform-files
                  env:
                    ARM_CLIENT_ID: $(innovation-qa-spn-client-id)
                    ARM_CLIENT_SECRET: $(innovation-qa-spn-secret)
                    ARM_TENANT_ID: $(innovation-qa-spn-tenant-id)
                    ARM_SUBSCRIPTION_ID: $(innovation-qa-subscription-id)
                    TF_LOG: $(qa-log-level)
                
                # Terraform Apply
                - bash: |
                    terraform apply -auto-approve qa.tfplan
                  displayName: Terraform > Apply to QA
                  workingDirectory: $(Pipeline.Workspace)/NetworkingBuild/networking-terraform-files
                  env:
                    ARM_CLIENT_ID: $(innovation-qa-spn-client-id)
                    ARM_CLIENT_SECRET: $(innovation-qa-spn-secret)
                    ARM_TENANT_ID: $(innovation-qa-spn-tenant-id)
                    ARM_SUBSCRIPTION_ID: $(innovation-qa-subscription-id)
                    TF_LOG: $(qa-log-level)

  - stage: Apply_PROD
    displayName: PROD Deployment
    pool:
      vmImage: ubuntu-latest
    jobs:
      - deployment: Networking_Terraform_Deployment
        environment: "Prod"
        strategy:
          runOnce:
            deploy:
              steps:
                #create vpn tunnel
                - bash: |
                    sudo apt-get --assume-yes --no-install-recommends install openvpn

                    chmod 777 vpnconfig.ovpn
                    envsubst < vpnconfig.ovpn > _vpnconfig.ovpn

                    sudo openvpn _vpnconfig.ovpn &

                    sleep 5

                    ifconfig tun0

                    sudo rm /etc/resolv.conf
                    echo "nameserver $DNSSERVER" | sudo tee /etc/resolv.conf
                  workingDirectory: $(Pipeline.Workspace)/NetworkingBuild/polaris-template-files
                  env:
                    PRESHAREDKEY: $(prod_pre-shared_key)
                    PRIVATEKEY: $(prod_private_key)
                    CLIENTCERTIFICATE: $(prod_client_cert)
                    VPNSERVER: $(prod_vpn_server)
                    DNSSERVER: $(prod_dns_server)
                  displayName: Creating PROD VPN tunnel
                  
                # Install Terraform based on version variable
                - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
                  displayName: Terraform > Install
                  inputs:
                    terraformVersion: $(terraform-version)
                
                #download networking terraform build artifact
                - download: NetworkingBuild
                  displayName: Terraform > Download Networking terraform build
                  artifact: "networking-terraform-files"
                
                # Terraform Init
                - bash: |
                    terraform init \
                      -backend-config="storage_account_name=$TF_STATE_ACCOUNT_NAME" \
                      -backend-config="container_name=$TF_STATE_CONTAINER_NAME" \
                      -backend-config="key=$TF_STATE_KEY" \
                      -backend-config="access_key=$TF_STATE_ACCESS_KEY"
                  displayName: Terraform > Init
                  workingDirectory: $(Pipeline.Workspace)/NetworkingBuild/networking-terraform-files
                  env:
                    TF_STATE_ACCOUNT_NAME: $(prod-terraform-storage-account)
                    TF_STATE_CONTAINER_NAME: $(networking-terraform-container-name)
                    TF_STATE_KEY: $(terraform-key)
                    TF_STATE_ACCESS_KEY: $(cpsprodstorageterraform-key1)
                    TF_LOG: $(prod-log-level)
                
                # Terraform Plan
                - bash: |
                    terraform plan -input=false -out=prod.tfplan -var-file="prod.tfvars"
                  displayName: 'Terraform > Write Networking Plan'
                  workingDirectory: $(Pipeline.Workspace)/NetworkingBuild/networking-terraform-files
                  env:
                    ARM_CLIENT_ID: $(innovation-prod-spn-client-id)
                    ARM_CLIENT_SECRET: $(innovation-prod-spn-secret)
                    ARM_TENANT_ID: $(innovation-prod-spn-tenant-id)
                    ARM_SUBSCRIPTION_ID: $(innovation-prod-subscription-id)
                    TF_LOG: $(prod-log-level)
                
                # Terraform Apply
                - bash: |
                    terraform apply -auto-approve prod.tfplan
                  displayName: Terraform > Apply to PROD
                  workingDirectory: $(Pipeline.Workspace)/NetworkingBuild/networking-terraform-files
                  env:
                    ARM_CLIENT_ID: $(innovation-prod-spn-client-id)
                    ARM_CLIENT_SECRET: $(innovation-prod-spn-secret)
                    ARM_TENANT_ID: $(innovation-prod-spn-tenant-id)
                    ARM_SUBSCRIPTION_ID: $(innovation-prod-subscription-id)
                    TF_LOG: $(prod-log-level)