trigger:
  branches:
    include:
      - main
      - qa
      - release

  paths:
    include:
      - "polaris-terraform/ui-terraform/*"

steps:
  - task: PublishPipelineArtifact@1
    displayName: 'Publish Terraform Artifacts'
    inputs:
      targetPath: '$(Pipeline.Workspace)/s/polaris-terraform/ui-terraform/'
      artifact: 'ui-terraform-files'
      publishLocation: 'pipeline'