import { PresentationDocumentProperties } from "../../domain/gateway/PipelineDocument";

const docTypeTest = (
  caseDocument: PresentationDocumentProperties,
  codes: string[]
) =>
  !!caseDocument.cmsDocType.documentType &&
  codes.some(
    (code) =>
      !!code &&
      code.replace(/\s+/g, "") ===
        caseDocument.cmsDocType.documentType.replace(/\s+/g, "")
  );

const documentCategoryDefinitions: {
  category: string;
  showIfEmpty: boolean;
  test: (caseDocument: PresentationDocumentProperties) => boolean;
}[] = [
  // todo: when we know, write the `test` logic to identify which document goes in which section
  {
    category: "Reviews",
    showIfEmpty: true,
    test: (doc) =>
      docTypeTest(doc, [
        "MG3",
        "MG3A",
        "MG3S",
        "MG3AS",
        "CAP01",
        "MG17",
        "MG 3",
        "MG 3A",
        "MG 17",
        "DCF",
      ]),
  },
  {
    category: "Case overview",
    showIfEmpty: true,
    test: (doc) =>
      docTypeTest(doc, [
        "MG 1",
        "MG 4",
        "MG 4A",
        "MG 4B",
        "MG 4C",
        "MG 5",
        "MG 4F",
        "MG 4(Post)",
        "MG 5(SP)",
        "MG 4D",
        "MG 4E",
      ]),
  },
  {
    category: "Statements",
    showIfEmpty: true,
    test: (doc) =>
      docTypeTest(doc, [
        "MG 11(CONT)",
        "MG 11(T)",
        "MG 11T(CONT)",
        "MG 11",
        "MG 11(R)",
      ]),
  },
  {
    category: "Exhibits",
    showIfEmpty: true,
    test: (doc) =>
      docTypeTest(doc, [
        "MG 12",
        "MG 15(ROTI)",
        "MG 15(CONT)",
        "MG 15(T)",
        "MG 15(T)(CONT)",
        "MG/FSS B",
        "OTHER EXHIBIT",
        "MG 15(SDN)",
        "MG 15(ROVI)",
        "MGDD",
        "MG 15(CNOI)",
        "MG 00",
        "ABE",
        "EG3",
        "EG3",
      ]),
  },
  {
    category: "Forensics",
    showIfEmpty: true,
    test: (doc) => docTypeTest(doc, ["MG 21", "MG 21A", "MG22 SFR"]),
  },
  {
    category: "Unused material",
    showIfEmpty: true,
    test: (doc) =>
      docTypeTest(doc, ["MG 6B", "MG 6C", "MG 6D", "MG 6E", "MG 6A", "SDC"]),
  },
  {
    category: "Defendant",
    showIfEmpty: true,
    test: (doc) =>
      docTypeTest(doc, ["MG/FSS A", "MG 14", "PCN 1", "PCN 2", "PCN 3"]),
  },
  {
    category: "Court preparation",
    showIfEmpty: true,
    test: (doc) =>
      docTypeTest(doc, [
        "MG 7",
        "MG 8",
        "MG 9",
        "MG 10",
        "MG 18",
        "MG19",
        "MG 2",
        "MG 13",
        "MG 16(DBCI)",
        "MG 16(DDOI)",
        "MG 16",
      ]),
  },
  {
    category: "Communications",
    showIfEmpty: true,
    test: (doc) =>
      docTypeTest(doc, [
        "AD01",
        "CCA01",
        "CCCP05",
        "CCCP08",
        "CCCP09",
        "CCCP12",
        "CCCP15",
        "CCCP17",
        "CCCP24",
        "CCCP25",
        "CFS02",
        "CMS01",
        "CMS10",
        "CMS11",
        "CMS12",
        "CMS13",
        "CMS21",
        "CMS22",
        "CFS01",
        "CMS25",
        "CMS26",
        "CMS27",
        "CMS28",
        "CMS30",
        "CMS33",
        "CMS39",
        "CMS40",
        "CMS41",
        "CMS42",
        "CMS43",
        "CCCP01",
        "CMS45",
        "CMS46",
        "CMS47",
        "CMS48",
        "CMS49",
        "CMS50",
        "CMS51",
        "CMS52",
        "CMS53",
        "CMS54",
        "CNATV01",
        "CNAV01",
        "CPIA01",
        "CPIA02",
        "CPIA03",
        "CPIA04",
        "CPIA05",
        "CPIA06",
        "CPIA07",
        "CTL01",
        "CTL02",
        "CTL03",
        "CVT01",
        "DN01",
        "DN02",
        "DN03",
        "DN04",
        "DP01",
        "DVM1",
        "DWR01",
        "POL1",
        "MIC01",
        "NEA01",
        "NFE01",
        "NFE02",
        "NFE03",
        "NFE04",
        "NT01",
        "NT02",
        "NT03",
        "PSR",
        "RID1",
        "S9",
        "SC01",
        "WEF04",
        "CCCP23A",
        "CCCP23B",
        "CCCP23C",
        "VIW03",
        "VIW04",
        "VIW05",
        "CMS34P",
        "CMS36P",
        "CMS37L",
        "CMS38L",
        "CD1",
        "CPSLogo",
        "CMS55",
        "VIW07",
        "VIW08",
        "CVR02",
        "CTL04",
        "POL2",
        "CMS56",
        "CMS57",
        "CMS58",
        "CMS59",
        "CMS60",
        "DVM4",
        "AR01",
        "AR02",
        "AR03",
        "AR04",
        "AR05",
        "AR06",
        "AR07",
        "AR08",
        "AR09",
        "AR10",
        "AR11",
        "AR12",
        "AR13",
        "AR14",
        "AR15",
        "AR16",
        "AR17",
        "AR18",
        "WEF04(Cont)",
        "CMS41b",
        "DRS",
        "CPIA1 (MC)",
        "CPIA2 (MC)",
        "CPIA3",
        "CPIA4",
        "CPIA4a",
        "CPIA5",
        "CPIA6",
        "CPIA01 (pre Apr05)",
        "CPIA02 (pre Apr05)",
        "CPIA03 (pre Apr05)",
        "CPIA04 (pre Apr05)",
        "CPIA05 (pre Apr05)",
        "CPIA06 (pre Apr05)",
        "CPIA07 (pre Apr05)",
        "BCE01",
        "BCE02",
        "BCE04",
        "BCE05",
        "BCE07",
        "BCE08",
        "NFR-HE1",
        "NFR-HE2",
        "POL3",
        "ASW",
        "CMP",
        "FIST2",
        "HFCC1",
        "VHCC1",
        "VHCC2",
        "VHCC3",
        "VHCC4",
        "VHCC5",
        "VHCC6",
        "VHCC7",
        "VHCC8",
        "VHCC9",
        "CMS61",
        "NFR-CCF1",
        "NFR-CCF2",
        "NFR-CCF3",
        "CP1-Def",
        "WEFLabel",
        "VFS1",
        "RP1",
        "RP2",
        "PSR02",
        "CBO1",
        "CBO2",
        "CPR3",
        "VIW11",
        "CMS01a",
        "REV1",
        "KDAR01",
        "CHS01",
        "s51(Ct)",
        "s51(Def)",
        "s51(Pol)",
        "BCE03",
        "NFR-HE3",
        "DGCC",
        "DGYCC",
        "MCTP",
        "LLA",
        "CMPSCR",
        "DN09",
        "PRMB",
        "CP2-Def",
        "CP3-Crt",
        "DEFRAINF",
        "DEFRALIC",
        "DEFRAREP",
        "DEFRAS9",
        "DEFRASUM",
        "DEFRALET",
        "REVIEW",
        "DWPDISC1",
        "DWPDISC2",
        "DWPCPR",
        "DWPCPO",
        "DWPPR",
        "PCREng",
        "PCRWel",
        "CPIA1 (CC)",
        "CPIA2 (CC)",
        "DIRCT",
        "DIRDEF",
        "HRS-MC",
        "HRS-CC",
        "WIH01",
        "HR",
        "DCF_FH_D",
        "DCF_FH_N",
        "DCF_BB_D",
        "DCF_BB_N",
        "CMS27a",
        "RRA01",
        "RRA02",
        "VIW01",
        "VIW02",
        "NFR-PS1",
        "MG6",
        "MG 20",
        "UNKNOWN",
        "HTE",
        "DREP",
        "DCS-R",
        "OTHER MATERIAL",
        "DDE1",
        "STWAC01",
        "CPIA8",
        "PFD04",
        "PFD02-",
        "PFD01",
        "PFD03",
        "SMOKE0502",
        "SMOKEe0502",
        "FEES01",
        "FEE202",
        "POC01",
        "Proceeds of Crime",
        "POL02",
        "Local Template01",
        "TEST-LOCAL_doc",
        "LOC03",
        "LOC4-test",
        "SMOKE 04MAR",
        "temp",
        "POC02-new",
        "COA BT Inactive",
        "COA BT TEST",
        "PFD03",
        "PFD04",
        "PFD01",
        "PFD02-",
        "CPIA8",
      ]),
  },
  {
    category: "Uncategorised",
    showIfEmpty: false,
    test: (doc) => docTypeTest(doc, ["PE 1", "PE 2", "PE 3", "PE 4"]),
  },
  // have unknown last so it can scoop up any unmatched documents
  {
    category: "Uncategorised",
    showIfEmpty: false,
    test: () => true,
  },
];

export const categoryNamesInPresentationOrder = documentCategoryDefinitions.map(
  ({ category }) => category
);

export const getCategory = (item: PresentationDocumentProperties) =>
  documentCategoryDefinitions.find(({ test }) => test(item))!.category;
