---
parameters:
  - name: devOpsPatToken
  - name: checkoutRef
  - name: cypressClientId
  - name: cypressClientSecret
  - name: cypressAdUserName
  - name: cypressAdPassword
  - name: cypressEnvironment
  - name: cypressPreSearchDelayMs
  - name: cypressGrepTagsA
  - name: cypressGrepTagsB

stages:
  - stage: Wait_For_Running_Tests
    displayName: Wait for Running Tests
    jobs:
      - job:
        steps:
          - template: ../../../polaris-devops-pipelines/deployments_v2/stages/jobs/tasks/task_wait-for-running-releases.yml
            parameters:
              devOpsPatToken: ${{ parameters.devOpsPatToken }}

  - stage: Run_e2e_Tests
    displayName: Run e2e Tests
    dependsOn: Wait_For_Running_Tests
    jobs:
      - template: jobs/job_prepare-dot-net-tests.yml
        parameters:
          checkoutRef: ${{ parameters.checkoutRef }}

      - template: jobs/job_run-dot-net-tests.yml
        parameters:
          checkoutRef: ${{ parameters.checkoutRef }}

      - template: jobs/job_run-cypress-tests-a.yml
        parameters:
          checkoutRef: ${{ parameters.checkoutRef }}
          cypressClientId: ${{ parameters.cypressClientId }}
          cypressClientSecret: ${{ parameters.cypressClientSecret }}
          cypressAdUserName: ${{ parameters.cypressAdUserName }}
          cypressAdPassword: ${{ parameters.cypressAdPassword }}
          cypressEnvironment: ${{ parameters.cypressEnvironment }}
          cypressPreSearchDelayMs: ${{ parameters.cypressPreSearchDelayMs }}
          cypressGrepTagsA: ${{ parameters.cypressGrepTagsA }}

      - template: jobs/job_run-cypress-tests-b.yml
        parameters:
          checkoutRef: ${{ parameters.checkoutRef }}
          cypressClientId: ${{ parameters.cypressClientId }}
          cypressClientSecret: ${{ parameters.cypressClientSecret }}
          cypressAdUserName: ${{ parameters.cypressAdUserName }}
          cypressAdPassword: ${{ parameters.cypressAdPassword }}
          cypressEnvironment: ${{ parameters.cypressEnvironment }}
          cypressPreSearchDelayMs: ${{ parameters.cypressPreSearchDelayMs }}
          cypressGrepTagsB: ${{ parameters.cypressGrepTagsB }}