parameters:
  buildAgent: ""
  buildLabel: ""
  appInsightsKey: ""
  devOpsEnv: ""
  envLabel: ""
  envSuffix: ""
  azureSubscription: ""
  devOpsPatToken: ""
  
jobs:
- deployment: DeployPipelineComponents
  environment: ${{ parameters.devOpsEnv }}
  strategy:
    runOnce:
      deploy:
        steps:
          #download scripts artifact
        - download: ${{ parameters.buildLabel }}
          displayName: Download Scripts
          artifact: 'polaris-script-files'
          
          #send custom event to AppInsights
        - template: steps/tasks/send-to-app-insights.yml
          parameters:
            appInsightsKey: "${{ parameters.appInsightsKey }}"
            message: "${{ parameters.envLabel }} Pipeline Component Deployment: Started"
          
        - template: steps/deploy-coordinator.yml
          parameters:
            appInsightsKey: "${{ parameters.appInsightsKey }}"
            envLabel: "${{ parameters.envLabel }}"
            buildLabel: "${{ parameters.buildLabel }}"
            envSuffix: "${{ parameters.envSuffix }}"
            azureSubscription: "${{ parameters.azureSubscription }}"
          
        - template: steps/deploy-pdf-generator.yml
          parameters:
            appInsightsKey: "${{ parameters.appInsightsKey }}"
            envLabel: "${{ parameters.envLabel }}"
            buildLabel: "${{ parameters.buildLabel }}"
            envSuffix: "${{ parameters.envSuffix }}"
            azureSubscription: "${{ parameters.azureSubscription }}"
            
        - template: steps/deploy-text-extractor.yml
          parameters:
            appInsightsKey: "${{ parameters.appInsightsKey }}"
            envLabel: "${{ parameters.envLabel }}"
            buildLabel: "${{ parameters.buildLabel }}"
            envSuffix: "${{ parameters.envSuffix }}"
            azureSubscription: "${{ parameters.azureSubscription }}"
          
          #send custom event to AppInsights
        - template: steps/tasks/send-to-app-insights.yml
          parameters:
            appInsightsKey: "${{ parameters.appInsightsKey }}"
            message: "${{ parameters.envLabel }} Pipeline Component Deployment: Completed"
          
          #send any failures to AppInsights  
        - template: steps/tasks/send-failure-to-app-insights.yml
          parameters:
            appInsightsKey: "${{ parameters.appInsightsKey }}"
            devOpsPatToken: "${{ parameters.devOpsPatToken }}"
            message: "${{ parameters.envLabel }} Pipeline Component Deployment: Failed"