/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CpsGlobalNav {
        "forceEnvironment": string;
        /**
          * The text to appear at the start of the second row
         */
        "name": string;
    }
}
export interface CpsGlobalNavCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCpsGlobalNavElement;
}
declare global {
    interface HTMLCpsGlobalNavElementEventMap {
        "cpsGlobalNavEvent": string;
    }
    interface HTMLCpsGlobalNavElement extends Components.CpsGlobalNav, HTMLStencilElement {
        addEventListener<K extends keyof HTMLCpsGlobalNavElementEventMap>(type: K, listener: (this: HTMLCpsGlobalNavElement, ev: CpsGlobalNavCustomEvent<HTMLCpsGlobalNavElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLCpsGlobalNavElementEventMap>(type: K, listener: (this: HTMLCpsGlobalNavElement, ev: CpsGlobalNavCustomEvent<HTMLCpsGlobalNavElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLCpsGlobalNavElement: {
        prototype: HTMLCpsGlobalNavElement;
        new (): HTMLCpsGlobalNavElement;
    };
    interface HTMLElementTagNameMap {
        "cps-global-nav": HTMLCpsGlobalNavElement;
    }
}
declare namespace LocalJSX {
    interface CpsGlobalNav {
        "forceEnvironment"?: string;
        /**
          * The text to appear at the start of the second row
         */
        "name"?: string;
        "onCpsGlobalNavEvent"?: (event: CpsGlobalNavCustomEvent<string>) => void;
    }
    interface IntrinsicElements {
        "cps-global-nav": CpsGlobalNav;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cps-global-nav": LocalJSX.CpsGlobalNav & JSXBase.HTMLAttributes<HTMLCpsGlobalNavElement>;
        }
    }
}
