parameters:
  stageName: ""
  displayName: ""
  buildAgent: ""
  buildLabel: ""
  appInsightsKey: ""
  devOpsEnv: "Dev"
  envLabel: "DEV"
  envSuffix: "-dev"
  azureSubscription: ""
  devOpsPatToken: ""

stages:
  - stage: ${{ parameters.stageName }}
    displayName: ${{ parameters.displayName }}
    pool:
      name: ${{ parameters.buildAgent }}
    jobs:
      - template: jobs/deploy-pipeline-components.yml
        parameters:
          buildAgent: ${{ parameters.buildAgent }}
          buildLabel: ${{ parameters.buildLabel }}
          appInsightsKey: ${{ parameters.appInsightsKey }}
          devOpsEnv: ${{ parameters.devOpsEnv }}
          envLabel: ${{ parameters.envLabel }}
          envSuffix: ${{ parameters.envSuffix }}
          azureSubscription: ${{ parameters.azureSubscription }}
          devOpsPatToken: ${{ parameters.devOpsPatToken }}
    
      - template: jobs/deploy-ui-components.yml
        parameters:
          buildAgent: ${{ parameters.buildAgent }}
          buildLabel: ${{ parameters.buildLabel }}
          appInsightsKey: ${{ parameters.appInsightsKey }}
          devOpsEnv: ${{ parameters.devOpsEnv }}
          envLabel: ${{ parameters.envLabel }}
          envSuffix: ${{ parameters.envSuffix }}
          azureSubscription: ${{ parameters.azureSubscription }}
          devOpsPatToken: ${{ parameters.devOpsPatToken }}