parameters:
  - name: stageBuildAgent
    type: string
  - name: stageDependsOn
    type: object
  - name: envLabel
    type: string
  - name: targetLabel
    type: string
  - name: targetName
    type: string
  - name: targetSuffix
    type: string
  - name: appInsightsKey
    type: string
  - name: azureSubscription
    type: string
  - name: devOpsPatToken
    type: string
  - name: logResultDependsOn
    type: object
    
stages:
  - stage: Deploy_${{ parameters.targetLabel }}
    displayName: Deploy > ${{ parameters.targetLabel }}
    ${{ if parameters.stageDependsOn }}:
      dependsOn: ${{ parameters.stageDependsOn }}
    pool:
      name: ${{ parameters.stageBuildAgent }}
    jobs:
      - template: jobs/log-start.yml
        parameters:
          envLabel: ${{ parameters.envLabel }}
          targetLabel: ${{ parameters.targetLabel }}
          targetName: ${{ parameters.targetName }}
          appInsightsKey: ${{ parameters.appInsightsKey }}

      - template: jobs/deploy-pipeline-components.yml
        parameters:
          envLabel: ${{ parameters.envLabel }}
          targetLabel: ${{ parameters.targetLabel }}
          targetName: ${{ parameters.targetName }}
          targetSuffix: ${{ parameters.targetSuffix }}
          appInsightsKey: ${{ parameters.appInsightsKey }}
          azureSubscription: ${{ parameters.azureSubscription }}

      - template: jobs/deploy-ui-components.yml
        parameters:
          envLabel: ${{ parameters.envLabel }}
          targetLabel: ${{ parameters.targetLabel }}
          targetName: ${{ parameters.targetName }}
          targetSuffix: ${{ parameters.targetSuffix }}
          appInsightsKey: ${{ parameters.appInsightsKey }}"
          azureSubscription: ${{ parameters.azureSubscription }}

      - template: jobs/log-result.yml
        parameters:
          envLabel: ${{ parameters.envLabel }}
          targetLabel: ${{ parameters.targetLabel }}
          targetName: ${{ parameters.targetName }}
          appInsightsKey: ${{ parameters.appInsightsKey }}
          devOpsPatToken: ${{ parameters.devOpsPatToken }}
          dependsOn: ${{ parameters.logResultDependsOn }}