---
parameters:
  - name: stageBuildAgent
    type: string
  - name: stageDependsOn
    type: object
  - name: targetBuild
    type: string
  - name: targetLabel
    type: string
  - name: targetName
    type: string
  - name: buildDefinitionId
    type: string
  - name: appInsightsKey
    type: string
  - name: devOpsPatToken
    type: string

stages:
  - stage: Run_e2e_Tests_${{ parameters.targetLabel }}
    displayName: e2e tests > ${{ parameters.targetLabel }}
    ${{ if parameters.stageDependsOn }}:
      dependsOn: ${{ parameters.stageDependsOn }}
    condition: succeeded()
    pool:
      name: ${{ parameters.stageBuildAgent }}
    jobs:
      - template: jobs/job_log-start.yml
        parameters:
          targetBuild: ${{ parameters.targetBuild }}
          targetLabel: ${{ parameters.targetLabel }}
          targetName: ${{ parameters.targetName }}
          appInsightsKey: ${{ parameters.appInsightsKey }}

      - template: jobs/job_run-e2e-tests.yml
        parameters:
          targetLabel: ${{ parameters.targetLabel }}
          buildDefinitionId: ${{ parameters.buildDefinitionId }}
          devOpsPatToken: ${{ parameters.devOpsPatToken }}
            
      - template: jobs/job_log-result.yml
        parameters:
          targetBuild: ${{ parameters.targetBuild }}
          targetLabel: ${{ parameters.targetLabel }}
          targetName: ${{ parameters.targetName }}
          appInsightsKey: ${{ parameters.appInsightsKey }}
          devOpsPatToken: ${{ parameters.devOpsPatToken }}
          jobDependsOn:
            - LogStart
            - RunE2ETests
