---
parameters:
  - name: stageBuildAgent
    type: string
  - name: stageDependsOn
    type: object
  - name: envLabel
    type: string
  - name: targetSuffix
    type: string
  - name: targetBuild
    type: string
  - name: targetLabel
    type: string
  - name: azureSubscription
    type: string
  - name: appInsightsKey
    type: string
  - name: devOpsPatToken
    type: string

stages:
  - stage: Start_${{ parameters.targetLabel }}
    displayName: Start Slots > ${{ parameters.targetLabel }}
    ${{ if parameters.stageDependsOn }}:
      dependsOn: ${{ parameters.stageDependsOn }}
    condition: succeeded()
    pool:
      name: ${{ parameters.stageBuildAgent }}
    jobs:
      - template: jobs/job_log-start.yml
        parameters:
          targetBuild: ${{ parameters.targetBuild }}
          targetLabel: ${{ parameters.targetLabel }}
          targetName: "Start Polaris Codebase Slots"
          appInsightsKey: ${{ parameters.appInsightsKey }}

      - template: jobs/job_start-slots.yml
        parameters:
          envLabel: ${{ parameters.envLabel }}
          targetSuffix: ${{ parameters.targetSuffix }}
          azureSubscription: ${{ parameters.azureSubscription }}
          jobDependsOn:
            - LogStart

      - template: jobs/job_log-result.yml
        parameters:
          targetBuild: ${{ parameters.targetBuild }}
          targetLabel: ${{ parameters.targetLabel }}
          targetName: "Start Polaris Codebase Slots"
          appInsightsKey: ${{ parameters.appInsightsKey }}
          devOpsPatToken: ${{ parameters.devOpsPatToken }}
          jobDependsOn:
            - Start_Pipeline_Slots
            - Start_UI_Slots
