---
parameters:
  - name: stageBuildAgent
    type: string
  - name: stageDependsOn
    type: object
  - name: envLabel
    type: string
  - name: targetBuild
    type: string
  - name: targetLabel
    type: string
  - name: targetName
    type: string
  - name: targetSuffix
    type: string
  - name: appInsightsKey
    type: string
  - name: azureSubscription
    type: string
  - name: devOpsPatToken
    type: string

stages:
  - stage: Deploy_${{ parameters.targetLabel }}
    displayName: Deploy > ${{ parameters.targetLabel }}
    ${{ if parameters.stageDependsOn }}:
      dependsOn: ${{ parameters.stageDependsOn }}
    pool:
      name: ${{ parameters.stageBuildAgent }}
    jobs:
      - template: jobs/job_log-start-deployment.yml
        parameters:
          envLabel: ${{ parameters.envLabel }}
          targetBuild: ${{ parameters.targetBuild }}
          targetLabel: ${{ parameters.targetLabel }}
          targetName: ${{ parameters.targetName }}
          appInsightsKey: ${{ parameters.appInsightsKey }}
          
      - template: jobs/job_deploy-codebase.yml
        parameters:
          envLabel: ${{ parameters.envLabel }}
          targetBuild: ${{ parameters.targetBuild }}
          targetLabel: ${{ parameters.targetLabel }}
          targetName: ${{ parameters.targetName }}
          targetSuffix: ${{ parameters.targetSuffix }}
          appInsightsKey: ${{ parameters.appInsightsKey }}
          azureSubscription: ${{ parameters.azureSubscription }}
          jobDependsOn:
            - LogStart

      - template: jobs/job_log-result-deployment.yml
        parameters:
          envLabel: ${{ parameters.envLabel }}
          targetBuild: ${{ parameters.targetBuild }}
          targetLabel: ${{ parameters.targetLabel }}
          targetName: ${{ parameters.targetName }}
          appInsightsKey: ${{ parameters.appInsightsKey }}
          devOpsPatToken: ${{ parameters.devOpsPatToken }}
          jobDependsOn:
            - LogStart
            - DeployCoordinator
            - DeployPdfGenerator
            - DeployTextGenerator
            - DeploySpa
            - DeployGateway
