---
parameters:
  - name: buildAgent
    type: string
  - name: targetSuffix
    type: string
  - name: targetBuild
    type: string
  - name: targetLabel
    type: string
  - name: azureSubscription
    type: string
  - name: appInsightsKey
    type: string
  - name: devOpsPatToken
    type: string
    
stages:
  - stage: Swap_${{ parameters.targetLabel }}
    displayName: Swap Slots > ${{ parameters.targetLabel }}
    dependsOn: Run_e2e_Tests_${{ parameters.targetLabel }}
    condition: succeeded()
    pool:
      name: ${{ parameters.buildAgent }}
    jobs:
      - template: jobs/job_log-start.yml
        parameters:
          targetBuild: ${{ parameters.targetBuild }}
          targetLabel: ${{ parameters.targetLabel }}
          targetName: "Swap Polaris UI Slots"
          appInsightsKey: ${{ parameters.appInsightsKey }}
          
      - template: jobs/job_generate-slot-name.yml
        parameters:
          targetBuild: ${{ parameters.targetBuild }}
          jobDependsOn:
            - LogStart
            
      - template: jobs/job_swap-ui-slots.yml
        parameters:
          targetSuffix: ${{ parameters.targetSuffix }}
          azureSubscription: ${{ parameters.azureSubscription }}
          jobDependsOn:
            - GenerateSlotName
              
      - template: jobs/job_log-result.yml
        parameters:
          targetBuild: ${{ parameters.targetBuild }}
          targetLabel: ${{ parameters.targetLabel }}
          targetName: "Swap Polaris UI Slots"
          appInsightsKey: ${{ parameters.appInsightsKey }}
          devOpsPatToken: ${{ parameters.devOpsPatToken }}
          jobDependsOn:
            - Swap_UI_Slots
