---
parameters:
  - name: stageBuildAgent
    type: string
  - name: stageDependsOn
    type: object
  - name: envLabel
    type: string
  - name: targetBuild
    type: string
  - name: targetSuffix
    type: string
  - name: targetLabel
    type: string
  - name: targetName
    type: string
  - name: appInsightsKey
    type: string
  - name: coordinatorStatusUrl
    type: string
  - name: pdfGeneratorStatusUrl
    type: string
  - name: textExtractorStatusUrl
    type: string
  - name: authHandoverStatusUrl
    type: string
  - name: gatewayStatusUrl
    type: string
  - name: proxyStatusUrl
    type: string
  - name: spaStatusUrl
    type: string
  - name: statusCheckMethod
    type: string
  - name: statusCheckRetries
    type: string
  - name: statusCheckDelaySeconds
    type: string
  - name: statusCheckTimeoutSeconds
    type: string
  - name: devOpsPatToken
    type: string
  - name: armClientId
    type: string
  - name: armClientSecret
    type: string
  - name: armTenantId
    type: string
  - name: armSubscriptionId
    type: string

stages:
  - stage: Check_${{ parameters.targetLabel }}
    displayName: Status Checks > ${{ parameters.targetLabel }}
    ${{ if parameters.stageDependsOn }}:
      dependsOn: ${{ parameters.stageDependsOn }}
    condition: succeeded()
    pool:
      name: ${{ parameters.stageBuildAgent }}
    jobs:
      - template: jobs/job_log-start.yml
        parameters:
          targetBuild: ${{ parameters.targetBuild }}
          targetLabel: ${{ parameters.targetLabel }}
          targetName: ${{ parameters.targetName }}
          appInsightsKey: ${{ parameters.appInsightsKey }}
          
      - template: jobs/job_generate-slot-name.yml
        parameters:
          targetBuild: ${{ parameters.targetBuild }}
          jobDependsOn:
            - LogStart

      - template: jobs/job_check-pipeline-components.yml
        parameters:
          targetBuild: ${{ parameters.targetBuild }}
          targetLabel: ${{ parameters.targetLabel }}
          coordinatorStatusUrl: ${{ parameters.coordinatorStatusUrl }}
          pdfGeneratorStatusUrl: ${{ parameters.pdfGeneratorStatusUrl }}
          textExtractorStatusUrl: ${{ parameters.textExtractorStatusUrl }}
          statusCheckMethod: ${{ parameters.statusCheckMethod }}
          statusCheckRetries: ${{ parameters.statusCheckRetries }}
          statusCheckDelaySeconds: ${{ parameters.statusCheckDelaySeconds }}
          statusCheckTimeoutSeconds: ${{ parameters.statusCheckTimeoutSeconds }}
          jobDependsOn:
            - GenerateSlotName

      - template: jobs/job_check-ui-components.yml
        parameters:
          targetBuild: ${{ parameters.targetBuild }}
          targetLabel: ${{ parameters.targetLabel }}
          authHandoverStatusUrl: ${{ parameters.authHandoverStatusUrl }}
          gatewayStatusUrl: ${{ parameters.gatewayStatusUrl }}
          proxyStatusUrl: ${{ parameters.proxyStatusUrl }}
          spaStatusUrl: ${{ parameters.spaStatusUrl }}
          statusCheckMethod: ${{ parameters.statusCheckMethod }}
          statusCheckRetries: ${{ parameters.statusCheckRetries }}
          statusCheckDelaySeconds: ${{ parameters.statusCheckDelaySeconds }}
          statusCheckTimeoutSeconds: ${{ parameters.statusCheckTimeoutSeconds }}
          jobDependsOn:
            - GenerateSlotName

      - template: jobs/job_log-result.yml
        parameters:
          targetBuild: ${{ parameters.targetBuild }}
          targetLabel: ${{ parameters.targetLabel }}
          targetName: ${{ parameters.targetName }}
          appInsightsKey: ${{ parameters.appInsightsKey }}
          devOpsPatToken: ${{ parameters.devOpsPatToken }}
          jobDependsOn:
            - LogStart
            - CheckCoordinator
            - CheckPDFGenerator
            - CheckTextExtractor
            - CheckAuthHandover
            - CheckGateway
            - CheckSPA
