export const Agency = {
  DWP: { code: "1", name: "DWP" },
  NHS: { code: "2", name: "NHS" },
  CounterFraudAuthority: { code: "3", name: "Counter Fraud Authority" },
  DepartmentForHealthAndSocialCare: {
    code: "4",
    name: "Department for Health and Social Care",
  },
  MHRA: {
    code: "5",
    name: "Medicines Healthcare Regulatory Agency (MHRA)",
  },
  WelshRevenueAuthority: { code: "6", name: "Welsh Revenue Authority" },
  ChildMaintenanceGroup: { code: "7", name: "Child Maintenance Group" },
  DefraLinkedAgencies: { code: "8", name: "DEFRA-linked agencies including:" },
  TheVeterinaryMedicinesDirectorate: {
    code: "9",
    name: "The Veterinary Medicines Directorate",
  },
  AnimalHealthAndVeterinaryLaboratoriesAgency: {
    code: "10",
    name: "Animal Health and Veterinary Laboratories Agency",
  },
  ForestryCommissionWales: { code: "11", name: "Forestry Commission Wales" },
  RuralPaymentsAgency: { code: "12", name: "Rural Payments Agency" },
  HorticulturalMarketingInspectorate: {
    code: "13",
    name: "Horticultural Marketing Inspectorate",
  },
  MarineManagementOrganisation: {
    code: "14",
    name: "Marine Management Organisation",
  },
  GangmastersAndLabourAbuseAuthority: {
    code: "15",
    name: "Gangmasters and Labour Abuse Authority",
  },
  BritishCattleMovementService: {
    code: "16",
    name: "British Cattle Movement Service",
  },
  FoodStandardsAgency: { code: "17", name: "Food Standards Agency" },
  NATIS: { code: "18", name: "NATIS" },
  MOD: { code: "19", name: "MOD" },
  NCA: { code: "20", name: "NCA" },
  LocalAuthority: { code: "21", name: "Local Authority" },
  IOPC: {
    code: "22",
    name: "Independent Office for Police Conduct (IOPC)",
  },
  HSE: { code: "23", name: "Health and Safety Executive (HSE)" },
  HomeOfficeImmigration: { code: "24", name: "Home Office Immigration" },
  HMRC: { code: "25", name: "HMRC" },
  ROCU: { code: "26", name: "ROCU" },
  SO15: { code: "27", name: "SO15" },
  PoliceScotland: { code: "28", name: "Police Scotland" },
  CounterTerrorismPolice: { code: "29", name: "Counter Terrorism Police" },
  AvonandSomersetConstabulary: {
    code: "30",
    name: "Avon and Somerset Constabulary",
  },
  BedfordshirePolice: { code: "31", name: "Bedfordshire Police" },
  CambridgeshireConstabulary: {
    code: "32",
    name: "Cambridgeshire Constabulary",
  },
  CheshireConstabulary: { code: "33", name: "Cheshire Constabulary" },
  CityofLondonPolice: { code: "34", name: "City of London Police" },
  ClevelandPolice: { code: "35", name: "Cleveland Police" },
  CumbriaConstabulary: { code: "36", name: "Cumbria Constabulary" },
  DerbyshireConstabulary: { code: "37", name: "Derbyshire Constabulary" },
  DevonAndCornwallPolice: { code: "38", name: "Devon & Cornwall Police" },
  DorsetPolice: { code: "39", name: "Dorset Police" },
  DurhamConstabulary: { code: "40", name: "Durham Constabulary" },
  EssexPolice: { code: "41", name: "Essex Police" },
  GloucestershireConstabulary: {
    code: "42",
    name: "Gloucestershire Constabulary",
  },
  GreaterManchesterPolice: { code: "43", name: "Greater Manchester Police" },
  HampshireConstabulary: { code: "44", name: "Hampshire Constabulary" },
  HertfordshireConstabulary: { code: "45", name: "Hertfordshire Constabulary" },
  HumbersidePolice: { code: "46", name: "Humberside Police" },
  KentPolice: { code: "47", name: "Kent Police" },
  LancashireConstabulary: { code: "48", name: "Lancashire Constabulary" },
  LeicestershirePolice: { code: "49", name: "Leicestershire Police" },
  LincolnshirePolice: { code: "50", name: "Lincolnshire Police" },
  MerseysidePolice: { code: "51", name: "Merseyside Police" },
  MetropolitanPoliceService: {
    code: "52",
    name: "Metropolitan Police Service",
  },
  NorfolkConstabulary: { code: "53", name: "Norfolk Constabulary" },
  NorthYorkshirePolice: { code: "54", name: "North Yorkshire Police" },
  NorthamptonshirePolice: { code: "55", name: "Northamptonshire Police" },
  NorthumbriaPolice: { code: "56", name: "Northumbria Police" },
  NottinghamshirePolice: { code: "57", name: "Nottinghamshire Police" },
  SouthYorkshirePolice: { code: "58", name: "South Yorkshire Police" },
  StaffordshirePolice: { code: "59", name: "Staffordshire Police" },
  SuffolkConstabulary: { code: "60", name: "Suffolk Constabulary" },
  SurreyPolice: { code: "61", name: "Surrey Police" },
  SussexPolice: { code: "62", name: "Sussex Police" },
  ThamesValleyPolice: { code: "63", name: "Thames Valley Police" },
  WarwickshirePolice: { code: "64", name: "Warwickshire Police" },
  WestMerciaPolice: { code: "65", name: "West Mercia Police" },
  WestMidlandsPolice: { code: "66", name: "West Midlands Police" },
  WestYorkshirePolice: { code: "67", name: "West Yorkshire Police" },
  WiltshirePolice: { code: "68", name: "Wiltshire Police" },
  DyfedPowysPolice: { code: "69", name: "Dyfed-Powys Police" },
  GwentPolice: { code: "70", name: "Gwent Police" },
  NorthWalesPolice: { code: "71", name: "North Wales Police" },
  SouthWalesPolice: { code: "72", name: "South Wales Police" },
  BritishTransportPolice: { code: "73", name: "British Transport Police" },
  CivilNuclearConstabulary: { code: "74", name: "Civil Nuclear Constabulary" },
  MinistryofDefencePolice: { code: "75", name: "Ministry of Defence Police" },
  NationalPoliceAirService: { code: "76", name: "National Police Air Service" },
  SEROCU: { code: "77", name: "SEROCU" },
  ERSOU: { code: "78", name: "ERSOU" },
};
