

AppDependencies
| where AppRoleName == "fa-polaris-coordinator"
| where DependencyType == "HTTP"
| where Target == "fa-polaris-text-extractor.azurewebsites.net"
| where OperationName in ("ExtractText", "RefreshDocumentOrchestratorNext", "RefreshDocumentOrchestrator")
| summarize 
    FailedCount = countif(not(Success)),
    TotalCount = count() 
 by 
    bin(TimeGenerated, ts)
| project 
    TimeGenerated,
    FailRatePercentage = round(100.0 * FailedCount/ TotalCount, 2)