trigger: none
pr: none

schedules:
  - cron: "0 3 * * *" # First number represent the amount of minutes, second represent the hours. In this case 03:00 Monday - Sunday
    displayName: Clear-down PROD Polaris Assets
    branches:
      include:
        - main
    always: true

variables:
  - group: kv-prod-terraform
  - group: polaris-global
  - group: pipeline-terraform
  
stages:
  - stage: Clear_down_SearchIndex
    displayName: Reset Search Index
    jobs:
      - job: Clear_down_SearchIndex
        pool:
          vmImage: ubuntu-latest
        steps:
          #create prod vpn tunnel
          - bash: |
              sudo apt-get --assume-yes --no-install-recommends install openvpn

              chmod 777 vpnconfig.ovpn
              envsubst < vpnconfig.ovpn > _vpnconfig.ovpn

              sudo openvpn _vpnconfig.ovpn &

              sleep 5

              ifconfig tun0

              sudo rm /etc/resolv.conf
              echo "nameserver $DNSSERVER" | sudo tee /etc/resolv.conf
            workingDirectory: "$(Pipeline.Workspace)/s/polaris-devops-pipelines/templates"
            env:
              PRESHAREDKEY: $(prod_pre-shared_key)
              PRIVATEKEY: $(prod_private_key)
              CLIENTCERTIFICATE: $(prod_client_cert)
              VPNSERVER: $(prod_vpn_server)
              DNSSERVER: $(prod_dns_server)
            displayName: Creating PROD VPN tunnel
            
          # Terraform Init
          - bash: |
              terraform init \
                -backend-config="storage_account_name=$TF_STATE_ACCOUNT_NAME" \
                -backend-config="container_name=$TF_STATE_CONTAINER_NAME" \
                -backend-config="key=$TF_STATE_KEY" \
                -backend-config="access_key=$TF_STATE_ACCESS_KEY"
            displayName: Terraform > Init
            workingDirectory: "$(Pipeline.Workspace)/s/polaris-terraform/pipeline-terraform/"
            env:
              TF_STATE_ACCOUNT_NAME: $(prod-terraform-storage-account)
              TF_STATE_CONTAINER_NAME: $(pipeline-terraform-container-name)
              TF_STATE_KEY: $(terraform-key)
              TF_STATE_ACCESS_KEY: $(cpsprodstorageterraform-key1)
                
          # Terraform Plan
          - bash: |
              terraform plan -input=false -out=prod.tfplan -var-file="prod.tfvars" -target="restapi_object.definition" -replace="restapi_object.definition"
            displayName: 'Terraform > Write Pipeline Plan, flagging search index refresh'
            workingDirectory: "$(Pipeline.Workspace)/s/polaris-terraform/pipeline-terraform/"
            env:
              ARM_CLIENT_ID: $(innovation-prod-spn-client-id)
              ARM_CLIENT_SECRET: $(innovation-prod-spn-secret)
              ARM_TENANT_ID: $(innovation-prod-spn-tenant-id)
              ARM_SUBSCRIPTION_ID: $(innovation-prod-subscription-id)
                
          # Terraform Apply
          - bash: |
              terraform apply -auto-approve prod.tfplan
            displayName: Terraform > Refresh Search Index
            workingDirectory: "$(Pipeline.Workspace)/s/polaris-terraform/pipeline-terraform/"
            env:
              ARM_CLIENT_ID: $(innovation-prod-spn-client-id)
              ARM_CLIENT_SECRET: $(innovation-prod-spn-secret)
              ARM_TENANT_ID: $(innovation-prod-spn-tenant-id)
              ARM_SUBSCRIPTION_ID: $(innovation-prod-subscription-id)
                
  - stage: Clear_down_BlobStorage
    displayName: Reset Document Blob Storage
    dependsOn: Clear_down_SearchIndex
    condition: succeeded()
    jobs:
      - job: Clear_down_BlobStorage
        pool:
          vmImage: ubuntu-latest
        steps:
          #create prod vpn tunnel
          - bash: |
              sudo apt-get --assume-yes --no-install-recommends install openvpn

              chmod 777 vpnconfig.ovpn
              envsubst < vpnconfig.ovpn > _vpnconfig.ovpn

              sudo openvpn _vpnconfig.ovpn &

              sleep 5

              ifconfig tun0

              sudo rm /etc/resolv.conf
              echo "nameserver $DNSSERVER" | sudo tee /etc/resolv.conf
            workingDirectory: "$(Pipeline.Workspace)/s/polaris-devops-pipelines/templates"
            env:
              PRESHAREDKEY: $(prod_pre-shared_key)
              PRIVATEKEY: $(prod_private_key)
              CLIENTCERTIFICATE: $(prod_client_cert)
              VPNSERVER: $(prod_vpn_server)
              DNSSERVER: $(prod_dns_server)
            displayName: Creating PROD VPN tunnel
            
          - task: AzureCLI@2
            displayName: Refresh Blob Storage
            inputs:
              connectedServiceNameARM: '$(prod-azure-subscription)'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az storage blob delete-batch --account-name $(prod-document-storage-account) --source documents --connection-string '$(cpsdocumentstorage-connection-string)' --delete-snapshots include