export enum AreaDivision {
  Wales = "Cymru/Wales",
  EastMidlands = "East Midlands",
  EastOfEngland = "East of England",
  LondonNorth = "London North",
  LondonSouth = "London South",
  MerseryCheshire = "Mersey-Cheshire",
  NorthEast = "North East",
  NorthWest = "North West",
  SouthEast = "South East",
  SouthWest = "South West",
  ThamesAndChiltern = "Thames and Chiltern",
  Wessex = "Wessex",
  WestMidlands = "West Midlands",
  YorkshireAndHumberside = "Yorkshire and Humberside",
  SpecialCrimeAndCounterTerrorismDivision = "Special Crime and Counter Terrorism Division",
  ProceedsOfCrime = "Proceeds of Crime",
  SEOCIDInternationalLondonAndSouthEastDivision = "SEOCID International, London and South East Division",
  SEOCIDRegionalAndWalesDivision = "SEOCID Regional and Wales Division",
  TestArea1 = "Test Area 1",
  TestArea2 = "Test Area 2",
  TestDivision1 = "Test Division 1",
  TestDivision2 = "Test Division 2",
}
