export enum AreaDivision {
  Wales = "Cymru/Wales",
  EastMidlands = "East Midlands",
  EastOfEngland = "East of England",
  LondonNorth = "London North",
  LondonSouth = "London South",
  MerseryCheshire = "Mersey-Cheshire",
  NorthEast = "North East",
  NorthWest = "North West",
  SouthEast = "South East",
  SouthWest = "South West",
  ThamesAndChiltern = "Thames and Chiltern",
  Wessex = "Wessex",
  WestMidlands = "West Midlands",
  YorkshireAndHumberside = "Yorkshire and Humberside",
  SpecialCrimeAndCounterTerrorismDivision = "Special Crime and Counter Terrorism Division",
  ProceedsOfCrime = "Proceeds of Crime",
  SEOCIDInternationalLondonAndSouthEastDivision = "SEOCID International, London and South East Division",
  SEOCIDRegionalAndWalesDivision = "SEOCID Regional and Wales Division",
  TestArea1 = "Test Area 1",
  TestArea2 = "Test Area 2",
  TestDivision1 = "Test Division 1",
  TestDivision2 = "Test Division 2",
}

export const areaDivisionsByGroup: { [type: string]: AreaDivision } = {
  "AZURE-WALES": AreaDivision.Wales,
  "AZURE-EAST_MIDLANDS": AreaDivision.EastMidlands,
  "AZURE-EAST_OF_ENGLAND": AreaDivision.EastOfEngland,
  "AZURE-LONDON_NORTH": AreaDivision.LondonNorth,
  "AZURE-LONDON_SOUTH": AreaDivision.LondonSouth,
  "AZURE-MERSEY_CHESHIRE": AreaDivision.MerseryCheshire,
  "AZURE-NORTH_EAST": AreaDivision.NorthEast,
  "AZURE-NORTH_WEST": AreaDivision.NorthWest,
  "AZURE-SOUTH_EAST": AreaDivision.SouthEast,
  "AZURE-SOUTH_WEST": AreaDivision.SouthWest,
  "AZURE-THAMES_AND_CHILTERN": AreaDivision.ThamesAndChiltern,
  "AZURE-WESSEX": AreaDivision.Wessex,
  "AZURE-WEST_MIDLANDS": AreaDivision.WestMidlands,
  "AZURE-YORKSHIRE_AND_HUMBERSIDE": AreaDivision.YorkshireAndHumberside,
  "AZURE-SPECIAL_CRIME_AND_COUNTER_TERRORISM_DIVISION":
    AreaDivision.SpecialCrimeAndCounterTerrorismDivision,
  "AZURE-PROCEEDS_OF_CRIME": AreaDivision.ProceedsOfCrime,
  "AZURE-SEOCID_INTERNATIONAL_LONDON_AND_SOUTH_EAST_DIVISION":
    AreaDivision.SEOCIDInternationalLondonAndSouthEastDivision,
  "AZURE-SEOCID_REGIONAL_AND_WALES_DIVISION":
    AreaDivision.SEOCIDRegionalAndWalesDivision,
  "AZURE-TEST_AREA_1": AreaDivision.TestArea1,
  "AZURE-TEST_AREA_2": AreaDivision.TestArea2,
  "AZURE-TEST_DIVISION_1": AreaDivision.TestDivision1,
  "AZURE-TEST_DIVISION_2": AreaDivision.TestDivision2,
};
