export type InvestigatingAgency =
  | "DWP"
  | "NHS"
  | "Counter Fraud Authority"
  | "Department for Health and Social Care"
  | "Medicines Healthcare Regulatory Agency (MHRA)"
  | "Welsh Revenue Authority"
  | "Child Maintenance Group"
  | "DEFRA-linked agencies including:"
  | "The Veterinary Medicines Directorate"
  | "Animal Health and Veterinary Laboratories Agency"
  | "Forestry Commission Wales"
  | "Rural Payments Agency"
  | "Horticultural Marketing Inspectorate"
  | "Marine Management Organisation"
  | "Gangmasters and Labour Abuse Authority"
  | "British Cattle Movement Service"
  | "Food Standards Agency"
  | "NATIS"
  | "MOD"
  | "NCA"
  | "Local Authority"
  | "Independent Office for Police Conduct (IOPC)"
  | "Health and Safety Executive (HSE)"
  | "Home Office Immigration"
  | "HMRC"
  | "ROCU"
  | "SO15"
  | "Police Scotland"
  | "Counter Terrorism Police"
  | "Avon and Somerset Constabulary"
  | "Bedfordshire Police"
  | "Cambridgeshire Constabulary"
  | "Cheshire Constabulary"
  | "City of London Police"
  | "Cleveland Police"
  | "Cumbria Constabulary"
  | "Derbyshire Constabulary"
  | "Devon & Cornwall Police"
  | "Dorset Police"
  | "Durham Constabulary"
  | "Essex Police"
  | "Gloucestershire Constabulary"
  | "Greater Manchester Police"
  | "Hampshire Constabulary"
  | "Hertfordshire Constabulary"
  | "Humberside Police"
  | "Kent Police"
  | "Lancashire Constabulary"
  | "Leicestershire Police"
  | "Lincolnshire Police"
  | "Merseyside Police"
  | "Metropolitan Police Service"
  | "Norfolk Constabulary"
  | "North Yorkshire Police"
  | "Northamptonshire Police"
  | "Northumbria Police"
  | "Nottinghamshire Police"
  | "South Yorkshire Police"
  | "Staffordshire Police"
  | "Suffolk Constabulary"
  | "Surrey Police"
  | "Sussex Police"
  | "Thames Valley Police"
  | "Warwickshire Police"
  | "West Mercia Police"
  | "West Midlands Police"
  | "West Yorkshire Police"
  | "Wiltshire Police"
  | "Dyfed-Powys Police"
  | "Gwent Police"
  | "North Wales Police"
  | "South Wales Police"
  | "British Transport Police"
  | "Civil Nuclear Constabulary"
  | "Ministry of Defence Police"
  | "National Police Air Service"
  | "SEROCU"
  | "ERSOU";
