trigger:
  branches:
    include:
    - main
    - feature/*
    - release/*
    - bug/*

  paths:
    include:
      - "terraform/pipeline-terraform/*"

steps:
  - task: PublishPipelineArtifact@1
    displayName: "Publish Terraform Artifacts"
    inputs:
      targetPath: "$(Pipeline.Workspace)/s/terraform/"
      artifact: "terraform-files"
      publishLocation: "pipeline"
