parameters:
  - name: project
    type: string
  - name: arguments
    type: string

steps:
  - task: NuGetAuthenticate@1
    displayName: "Authenticate NuGet feeds"

  - task: UseDotNet@2
    displayName: "Use .NET SDK from global.json"
    inputs:
      packageType: "sdk"
      useGlobalJson: true
  
  - task: DotNetCoreCLI@2
    inputs:
      command: "test"
      projects: ${{ parameters.project }}
      arguments: ${{ parameters.arguments }}
    displayName: "Run integration tests"