---
parameters:
  - name: targetBuild
    type: string
  - name: targetLabel
    type: string
  - name: targetName
    type: string
  - name: targetSuffix
    type: string
  - name: appInsightsKey
    type: string
  - name: azureSubscription
    type: string

steps:
  # download scripts artifact
  - download: ${{ parameters.targetBuild }}
    displayName: Download Scripts
    artifact: 'polaris-script-files'

  # send custom event to AppInsights
  - template: task_send-to-app-insights.yml
    parameters:
      appInsightsKey: ${{ parameters.appInsightsKey }}
      targetBuild: ${{ parameters.targetBuild }}
      message: "${{ parameters.targetLabel }} ${{ parameters.targetName }}: Publish Pdf Redactor - Started"

  # download pdf-redactor build artifact
  - download: ${{ parameters.targetBuild }}
    displayName: Deploy > Download PDF Redactor Codebase Build
    artifact: "polaris-pdf-redactor-drop"

  # Deploy Related Codebase to Env
  - task: AzureFunctionApp@1
    displayName: 'Deploy PDF Redactor Azure Function App to ${{ parameters.targetLabel }}'
    inputs:
      azureSubscription: ${{ parameters.azureSubscription }}
      appType: functionApp
      appName: "fa-polaris${{ parameters.targetSuffix }}-pdf-redactor"
      package: $(Pipeline.Workspace)/${{ parameters.targetBuild }}/polaris-pdf-redactor-drop
      deployToSlotOrASE: true
      resourceGroupName: "rg-polaris-pipeline${{ parameters.targetSuffix }}"
      slotName: "staging1"

  # send custom event to AppInsights
  - template: task_send-to-app-insights.yml
    parameters:
      appInsightsKey: ${{ parameters.appInsightsKey }}
      targetBuild: ${{ parameters.targetBuild }}
      message: "${{ parameters.targetLabel }} ${{ parameters.targetName }}: Publish Pdf Redactor - Completed"