trigger:
  branches:
    include:
    - main

  paths:
    include:
      - "polaris-terraform/ui-events-terraform/*"

steps:
  - task: PublishPipelineArtifact@1
    displayName: "Publish Terraform Artifacts"
    inputs:
      targetPath: "$(Pipeline.Workspace)/s/polaris-terraform/ui-events-terraform/"
      artifact: "ui-events-terraform-files"
      publishLocation: "pipeline"
