using Common.Dto.Case;

// TODO - Is this Used?
namespace PolarisGateway.Domain.StaticData
{
    public static class DocumentCmsTypes
    {
        private static List<DocumentCmsTypeDto> _documentCmsTypes = new List<DocumentCmsTypeDto>
        {
#region LookupValues
            new DocumentCmsTypeDto(100004,"1","rer32r32r2r"),
            new DocumentCmsTypeDto(100011,"1111","1111"),
            new DocumentCmsTypeDto(100156,"1111233446","OR78888888OR788888888or788888888or788888888OR78888"),
            new DocumentCmsTypeDto(100200,"123","123455"),
            new DocumentCmsTypeDto(100196,"1230","test code"),
            new DocumentCmsTypeDto(100183,"1234","Test Demo2"),
            new DocumentCmsTypeDto(100212,"12345ATEST","ATEST"),
            new DocumentCmsTypeDto(100053,"18850test","ortest"),
            new DocumentCmsTypeDto(100076,"18929logo","one"),
            new DocumentCmsTypeDto(100090,"2nd","2nd"),
            new DocumentCmsTypeDto(100178,"3452","test demop"),
            new DocumentCmsTypeDto(100182,"5478","Test Demo"),
            new DocumentCmsTypeDto(100165,"AA","BB"),
            new DocumentCmsTypeDto(100153,"AAAAARGH","AAAAARGH!"),
            new DocumentCmsTypeDto(100154,"AAARGHmk2","AAARGHmk2"),
            new DocumentCmsTypeDto(100102,"AATEST","AATEST1"),
            new DocumentCmsTypeDto(1201,"ABE","ABE"),
            new DocumentCmsTypeDto(100209,"ABSDDDD","New test document"),
            new DocumentCmsTypeDto(1,"AD01","Initial Details of the Prosecution Case"),
            new DocumentCmsTypeDto(100140,"ANew£$%%$","ANew"),
            new DocumentCmsTypeDto(100112,"AP RG2","AP RG2"),
            new DocumentCmsTypeDto(100034,"AP4 CMS","AP4 CMS"),
            new DocumentCmsTypeDto(100083,"AP4 LMTest","AP4 LMTest"),
            new DocumentCmsTypeDto(100040,"AP4 One","AP4 One"),
            new DocumentCmsTypeDto(100099,"AP4 Three","AP4 Three"),
            new DocumentCmsTypeDto(100108,"AP4 ThreeZ","AP4 ThreeZ"),
            new DocumentCmsTypeDto(100038,"AP4 Two","AP4 Two"),
            new DocumentCmsTypeDto(100107,"AP4 Two1","AP4 Two1"),
            new DocumentCmsTypeDto(100051,"AP4 WMStwo","AP4 WMStwo"),
            new DocumentCmsTypeDto(100109,"AP4 Z 1","AP4 Z 1"),
            new DocumentCmsTypeDto(100110,"AP4 Zwms2","AP4 Zwms2"),
            new DocumentCmsTypeDto(100113,"AP4RG3","AR4RG3"),
            new DocumentCmsTypeDto(100041,"AP4WMS One","AP4WMS One"),
            new DocumentCmsTypeDto(117,"AR01","Discharge Order"),
            new DocumentCmsTypeDto(118,"AR02","Consent Order - Shares"),
            new DocumentCmsTypeDto(119,"AR03","Consent Order - House"),
            new DocumentCmsTypeDto(120,"AR04","Consent Order - Car"),
            new DocumentCmsTypeDto(121,"AR05","Ex-Parte Variation Order"),
            new DocumentCmsTypeDto(122,"AR06","Restraint Order"),
            new DocumentCmsTypeDto(123,"AR07","Order of alternative service"),
            new DocumentCmsTypeDto(124,"AR08","Statement for Mgt Receiver"),
            new DocumentCmsTypeDto(125,"AR09","Mgt Receivership Order"),
            new DocumentCmsTypeDto(126,"AR10","Restraint Application"),
            new DocumentCmsTypeDto(127,"AR11","Confirmation of service form"),
            new DocumentCmsTypeDto(128,"AR12","Letter to Land Registry"),
            new DocumentCmsTypeDto(129,"AR13","Receivership Order"),
            new DocumentCmsTypeDto(130,"AR14","Brief to Counsel to Appoint Receiver"),
            new DocumentCmsTypeDto(131,"AR15","SIS of Receivership Order"),
            new DocumentCmsTypeDto(132,"AR16","Statement of Service"),
            new DocumentCmsTypeDto(133,"AR17","NTC Criminal Lifestyle"),
            new DocumentCmsTypeDto(134,"AR18","NTC not Criminal Lifestyle"),
            new DocumentCmsTypeDto(161,"ASW","Area Staff Workbook"),
            new DocumentCmsTypeDto(100190,"AW1","AW1"),
            new DocumentCmsTypeDto(100084,"Adamtest","Adamtest"),
            new DocumentCmsTypeDto(100097,"Alice","Alice"),
            new DocumentCmsTypeDto(152,"BCE01","Bad Character - Non-Defendant Application"),
            new DocumentCmsTypeDto(153,"BCE02","Bad Character - Defendant Notice"),
            new DocumentCmsTypeDto(195,"BCE03","Bad Character Non-Defendant Objection Notice"),
            new DocumentCmsTypeDto(154,"BCE04","App adduce non-def's BC (CC)"),
            new DocumentCmsTypeDto(155,"BCE05","Notice intent adduce BC (CC)"),
            new DocumentCmsTypeDto(156,"BCE07","App adduce non-def's BC (CA)"),
            new DocumentCmsTypeDto(157,"BCE08","Notice intent adduce BC (CA)"),
            new DocumentCmsTypeDto(100155,"Boom","Boom"),
            new DocumentCmsTypeDto(227,"CAP01","Case Action Plan"),
            new DocumentCmsTypeDto(184,"CBO1","Notice of Intent to Apply for SCPO (post con)"),
            new DocumentCmsTypeDto(185,"CBO2","Notice of Intent to Apply for ASBO (post con)"),
            new DocumentCmsTypeDto(2,"CCA01","Crown Court Acquittal"),
            new DocumentCmsTypeDto(37,"CCCP01","Outline of Allegations"),
            new DocumentCmsTypeDto(3,"CCCP05","Prosecution Advocate Brief"),
            new DocumentCmsTypeDto(4,"CCCP08","Brief Backsheet"),
            new DocumentCmsTypeDto(5,"CCCP09","Statement/Evidence List"),
            new DocumentCmsTypeDto(6,"CCCP12","Exhibit List"),
            new DocumentCmsTypeDto(7,"CCCP15","Index to Unused Material"),
            new DocumentCmsTypeDto(8,"CCCP17","S41 Schedule"),
            new DocumentCmsTypeDto(83,"CCCP23A","Covering Letter (Court)"),
            new DocumentCmsTypeDto(84,"CCCP23B","Covering Letter (Defence)"),
            new DocumentCmsTypeDto(85,"CCCP23C","Covering Letter (Police)"),
            new DocumentCmsTypeDto(10,"CCCP24","Form14a"),
            new DocumentCmsTypeDto(11,"CCCP25","Form 14a Reply Form"),
            new DocumentCmsTypeDto(100173,"CCR4561","CCR4561"),
            new DocumentCmsTypeDto(100175,"CCR4561","CCR4561"),
            new DocumentCmsTypeDto(100176,"CCR4561B","CCR4561B"),
            new DocumentCmsTypeDto(99,"CD1","Consent Form"),
            new DocumentCmsTypeDto(20,"CFS01","CFS Brief"),
            new DocumentCmsTypeDto(12,"CFS02","CFS Back Sheet"),
            new DocumentCmsTypeDto(100123,"CHADD2","CHADD2"),
            new DocumentCmsTypeDto(191,"CHS01","Case History Sheet"),
            new DocumentCmsTypeDto(162,"CMP","Case Management Panel Briefing"),
            new DocumentCmsTypeDto(201,"CMPSCR","CMP/Sensitive Case Referral"),
            new DocumentCmsTypeDto(13,"CMS01","Indictment"),
            new DocumentCmsTypeDto(188,"CMS01a","Indictment (CCC)"),
            new DocumentCmsTypeDto(14,"CMS10","DCV Letter"),
            new DocumentCmsTypeDto(15,"CMS11","Meeting - Family"),
            new DocumentCmsTypeDto(16,"CMS12","Meeting - Victim"),
            new DocumentCmsTypeDto(17,"CMS13","ESMM Request"),
            new DocumentCmsTypeDto(18,"CMS21","Transfer Letter (Def)"),
            new DocumentCmsTypeDto(19,"CMS22","Transfer Letter (MC)"),
            new DocumentCmsTypeDto(21,"CMS25","A/C Brief"),
            new DocumentCmsTypeDto(22,"CMS26","A/S Brief"),
            new DocumentCmsTypeDto(23,"CMS27","Note to Counsel"),
            new DocumentCmsTypeDto(511,"CMS27a","Note to Counsel"),
            new DocumentCmsTypeDto(24,"CMS28","Undertaking (Cover Letter)"),
            new DocumentCmsTypeDto(25,"CMS30","Undertaking Discharged"),
            new DocumentCmsTypeDto(26,"CMS33","Remitted Case"),
            new DocumentCmsTypeDto(89,"CMS34P","Charge Label (Portrait)"),
            new DocumentCmsTypeDto(91,"CMS36P","Advice Label (Portrait)"),
            new DocumentCmsTypeDto(97,"CMS37L","Appeal Label (Landscape)"),
            new DocumentCmsTypeDto(98,"CMS38L","Crown Court Label (Landscape)"),
            new DocumentCmsTypeDto(32,"CMS39","Victim Letter"),
            new DocumentCmsTypeDto(33,"CMS40","Defendant Letter"),
            new DocumentCmsTypeDto(34,"CMS41","Court (MC) Letter"),
            new DocumentCmsTypeDto(136,"CMS41b","Court (CC) Letter"),
            new DocumentCmsTypeDto(35,"CMS42","General Letter"),
            new DocumentCmsTypeDto(36,"CMS43","Further Charges"),
            new DocumentCmsTypeDto(38,"CMS45","Lodge Indictment"),
            new DocumentCmsTypeDto(39,"CMS46","Judge's bundle (cover)"),
            new DocumentCmsTypeDto(40,"CMS47","Defence bundle (cover)"),
            new DocumentCmsTypeDto(41,"CMS48","Prelim Hearing (cover)"),
            new DocumentCmsTypeDto(42,"CMS49","Adverse Outcome Form"),
            new DocumentCmsTypeDto(43,"CMS50","Advice to Police"),
            new DocumentCmsTypeDto(44,"CMS51","Dewarn Memo"),
            new DocumentCmsTypeDto(45,"CMS52","S9 Court Notice"),
            new DocumentCmsTypeDto(46,"CMS53","S51 Schedule"),
            new DocumentCmsTypeDto(47,"CMS54","PSR(CC)"),
            new DocumentCmsTypeDto(105,"CMS55","Schedule of Charges"),
            new DocumentCmsTypeDto(111,"CMS56","Victim - Insufficient Evidence"),
            new DocumentCmsTypeDto(112,"CMS57","Victim - Not in Public Interest"),
            new DocumentCmsTypeDto(113,"CMS58","Witness Summons - Memo to Police"),
            new DocumentCmsTypeDto(114,"CMS59","Witness Summons - MC Letter"),
            new DocumentCmsTypeDto(115,"CMS60","Witness Summons - CC Letter"),
            new DocumentCmsTypeDto(174,"CMS61","Archive Box Label"),
            new DocumentCmsTypeDto(100160,"CN2","CN2"),
            new DocumentCmsTypeDto(48,"CNATV01","TV Link Application (CNATV01)"),
            new DocumentCmsTypeDto(49,"CNAV01","Video Application (CNAV01)"),
            new DocumentCmsTypeDto(100252,"COA BT Inactive","Court of Appeal Brief - local TEST inactive"),
            new DocumentCmsTypeDto(100253,"COA BT TEST","Court of Appeal Brief-local TEST"),
            new DocumentCmsTypeDto(178,"CP1-Def","Application Covering Letter (Defence)"),
            new DocumentCmsTypeDto(204,"CP2-Def","Letter of Application(Defence)"),
            new DocumentCmsTypeDto(205,"CP3-Crt","Letter of Application(Court)"),
            new DocumentCmsTypeDto(50,"CPIA01","Primary - items"),
            new DocumentCmsTypeDto(145,"CPIA01 (pre Apr05)","Primary - items (pre Apr05)"),
            new DocumentCmsTypeDto(51,"CPIA02","Primary - no items"),
            new DocumentCmsTypeDto(146,"CPIA02 (pre Apr05)","Primary - no items (pre Apr05)"),
            new DocumentCmsTypeDto(52,"CPIA03","Def Statement to Police"),
            new DocumentCmsTypeDto(147,"CPIA03 (pre Apr05)","Def Statement to Police (pre Apr05)"),
            new DocumentCmsTypeDto(53,"CPIA04","Secondary - items"),
            new DocumentCmsTypeDto(148,"CPIA04 (pre Apr05)","Secondary - items (pre Apr05)"),
            new DocumentCmsTypeDto(54,"CPIA05","Secondary - no items"),
            new DocumentCmsTypeDto(149,"CPIA05 (pre Apr05)","Secondary - no items (pre Apr05)"),
            new DocumentCmsTypeDto(55,"CPIA06","Copy MG6C to Police"),
            new DocumentCmsTypeDto(150,"CPIA06 (pre Apr05)","Copy MG6C to Police (pre Apr05)"),
            new DocumentCmsTypeDto(56,"CPIA07","Request hearing - court"),
            new DocumentCmsTypeDto(151,"CPIA07 (pre Apr05)","Request hearing - court (pre Apr05)"),
            new DocumentCmsTypeDto(220,"CPIA1 (CC)","Initial - Disclosure (CC)"),
            new DocumentCmsTypeDto(138,"CPIA1 (MC)","Initial - Disclosure (MC)"),
            new DocumentCmsTypeDto(221,"CPIA2 (CC)","Initial - No Disclosure (CC)"),
            new DocumentCmsTypeDto(139,"CPIA2 (MC)","Initial - No Disclosure (MC)"),
            new DocumentCmsTypeDto(140,"CPIA3","Def Statement to Police"),
            new DocumentCmsTypeDto(141,"CPIA4","Ongoing - Disclosure"),
            new DocumentCmsTypeDto(142,"CPIA4a","Inadequate Def Statement"),
            new DocumentCmsTypeDto(143,"CPIA5","Ongoing - No Disclosure"),
            new DocumentCmsTypeDto(144,"CPIA6","Copy MG6c to Police"),
            new DocumentCmsTypeDto(100232,"CPIA8","Disclosure Management Document - Crown Court"),
            new DocumentCmsTypeDto(226015,"CPIA8","Disclosure Management Document - Crown Court"),
            new DocumentCmsTypeDto(186,"CPR3","Application for a Witness Summons"),
            new DocumentCmsTypeDto(100,"CPSLogo","LetterheadLogo"),
            new DocumentCmsTypeDto(57,"CTL01","CTL Extension Notice"),
            new DocumentCmsTypeDto(58,"CTL02","CTL Extension - Defence Letter"),
            new DocumentCmsTypeDto(59,"CTL03","CTL Extension - Listing Office"),
            new DocumentCmsTypeDto(109,"CTL04","CTL Extension Appeal"),
            new DocumentCmsTypeDto(108,"CVR02","Undertaking"),
            new DocumentCmsTypeDto(60,"CVT01","Transcript Request (CVT01)"),
            new DocumentCmsTypeDto(100122,"ChaaDD","Chaadd"),
            new DocumentCmsTypeDto(100157,"ChambersNa","ChambersNa"),
            new DocumentCmsTypeDto(100213,"CodeTFS1770","CodeTFS1770"),
            new DocumentCmsTypeDto(100058,"DA2Z3TEST2","DA2Z3TEST2NAME"),
            new DocumentCmsTypeDto(100101,"DAMYD11","ZZDAMYDC11"),
            new DocumentCmsTypeDto(100052,"DAMYDOC1","DAMYDOC1NAME"),
            new DocumentCmsTypeDto(100059,"DAONE11","DAONE11NAME"),
            new DocumentCmsTypeDto(100071,"DATEM100","DATEM100NAME"),
            new DocumentCmsTypeDto(100092,"DATEST1","ZZLOGOTEST"),
            new DocumentCmsTypeDto(100056,"DAZ2TEST","DAZ2TEST"),
            new DocumentCmsTypeDto(100057,"DAZ3TEST","DAZ3TESTNAME"),
            new DocumentCmsTypeDto(100085,"DB test","Db test"),
            new DocumentCmsTypeDto(1064,"DCF","Digital Case File"),
            new DocumentCmsTypeDto(231,"DCF_BB_D","DCF Breach of Bail"),
            new DocumentCmsTypeDto(232,"DCF_BB_N","DCF Breach of Bail Remand Application"),
            new DocumentCmsTypeDto(229,"DCF_FH_D","DCF First Hearing"),
            new DocumentCmsTypeDto(230,"DCF_FH_N","DCF First Hearing Remand Application"),
            new DocumentCmsTypeDto(1065,"DCS-R","DCS Document Received"),
            new DocumentCmsTypeDto(100230,"DDE1","Defence Engagement Log"),
            new DocumentCmsTypeDto(100103,"DDTEST1","TEST1"),
            new DocumentCmsTypeDto(100177,"DEF111","DEFENCE1"),
            new DocumentCmsTypeDto(206,"DEFRAINF","Information"),
            new DocumentCmsTypeDto(211,"DEFRALET","Summons/S9 Letter"),
            new DocumentCmsTypeDto(207,"DEFRALIC","Laying in Court"),
            new DocumentCmsTypeDto(208,"DEFRAREP","Prosecutor Report"),
            new DocumentCmsTypeDto(209,"DEFRAS9","Section 9"),
            new DocumentCmsTypeDto(210,"DEFRASUM","Summons"),
            new DocumentCmsTypeDto(197,"DGCC","Conditional Caution Authority"),
            new DocumentCmsTypeDto(198,"DGYCC","Youth Conditional Caution Authority"),
            new DocumentCmsTypeDto(222,"DIRCT","Directions Letter (Court)"),
            new DocumentCmsTypeDto(223,"DIRDEF","Directions Letter (Defence)"),
            new DocumentCmsTypeDto(61,"DN01","Disc Notice (Police)"),
            new DocumentCmsTypeDto(62,"DN02","Dropped/LOF (Police)"),
            new DocumentCmsTypeDto(63,"DN03","Disc Notice (MC)"),
            new DocumentCmsTypeDto(64,"DN04","Disc Notice (Defence)"),
            new DocumentCmsTypeDto(202,"DN09","Disc Notice (Prison)"),
            new DocumentCmsTypeDto(65,"DP01","Proposed Discontinuance"),
            new DocumentCmsTypeDto(1055,"DREP","DREP"),
            new DocumentCmsTypeDto(137,"DRS","Disclosure Record Sheet"),
            new DocumentCmsTypeDto(66,"DVM1","DVM1"),
            new DocumentCmsTypeDto(116,"DVM4","DVM4"),
            new DocumentCmsTypeDto(216,"DWPCPO","CPO Letter"),
            new DocumentCmsTypeDto(215,"DWPCPR","Client Prosecution Report"),
            new DocumentCmsTypeDto(213,"DWPDISC1","Case Discontinued"),
            new DocumentCmsTypeDto(214,"DWPDISC2","Client Discontinuance"),
            new DocumentCmsTypeDto(217,"DWPPR","Prosecution Report"),
            new DocumentCmsTypeDto(67,"DWR01","S51 Notice (Def)"),
            new DocumentCmsTypeDto(100065,"Dave","Dave"),
            new DocumentCmsTypeDto(100121,"Def Sols","Defence Sols"),
            new DocumentCmsTypeDto(100126,"DefDOB1","DefDOB1"),
            new DocumentCmsTypeDto(100118,"DefDOBTest","DefDOBTEST"),
            new DocumentCmsTypeDto(100119,"Defs DOB","Defendants and DOB"),
            new DocumentCmsTypeDto(100120,"Defs DOB2","Defs DOB 2"),
            new DocumentCmsTypeDto(100239,"EG3","Egress Unused Disclosed MME"),
            new DocumentCmsTypeDto(226148,"EG3","Egress Unused Disclosed MME"),
            new DocumentCmsTypeDto(100241,"FEE202","Updated Case Management Record for CCDs"),
            new DocumentCmsTypeDto(100240,"FEES01","Crown Court Fee Log"),
            new DocumentCmsTypeDto(163,"FIST2","Fees Information Sheet"),
            new DocumentCmsTypeDto(100198,"Fantasy2","Fantasy2"),
            new DocumentCmsTypeDto(100199,"Fantasy3","Fantasy3"),
            new DocumentCmsTypeDto(100116,"Friday","Friday"),
            new DocumentCmsTypeDto(164,"HFCC1","Notify Heavy Fraud/Complex Case"),
            new DocumentCmsTypeDto(228,"HR","Hearing Record"),
            new DocumentCmsTypeDto(225,"HRS-CC","Hearing Record Sheet - Crown Court"),
            new DocumentCmsTypeDto(224,"HRS-MC","Hearing Record Sheet - Magistrates Court"),
            new DocumentCmsTypeDto(1032,"HTE","Forwarded Internal Email"),
            new DocumentCmsTypeDto(190,"KDAR01","Key Decision and Action Record"),
            new DocumentCmsTypeDto(200,"LLA","Live Link Application"),
            new DocumentCmsTypeDto(100181,"LM1SMOKE","New05NOV"),
            new DocumentCmsTypeDto(100104,"LMTemp","Local temp CoverLetterLM"),
            new DocumentCmsTypeDto(100247,"LOC03","Local-test-document"),
            new DocumentCmsTypeDto(100248,"LOC4-test","Local-doc-test"),
            new DocumentCmsTypeDto(100226,"LOCALTEMPLATENS","Local Template Non-Sensitive Unit"),
            new DocumentCmsTypeDto(100228,"LOCALTEMPLATENS","Local Template in SFD proxy"),
            new DocumentCmsTypeDto(100227,"LOCALTEMPLATENS","Local Template in SFD Unit"),
            new DocumentCmsTypeDto(100225,"LOCALTEMPLATES","Local Template in Sensitive Unit"),
            new DocumentCmsTypeDto(100245,"Local Template01","POC3"),
            new DocumentCmsTypeDto(100077,"Logo&Text","OR18929"),
            new DocumentCmsTypeDto(199,"MCTP","Magistrates' Court Case Management Form"),
            new DocumentCmsTypeDto(1066,"MG 00","MG00"),
            new DocumentCmsTypeDto(1001,"MG 1","MG1"),
            new DocumentCmsTypeDto(1015,"MG 10","MG10"),
            new DocumentCmsTypeDto(1031,"MG 11","MG11"),
            new DocumentCmsTypeDto(1016,"MG 11(CONT)","MG11(CONT)"),
            new DocumentCmsTypeDto(1059,"MG 11(R)","MG11(R)"),
            new DocumentCmsTypeDto(1017,"MG 11(T)","MG11(T)"),
            new DocumentCmsTypeDto(1018,"MG 11T(CONT)","MG11T(CONT)"),
            new DocumentCmsTypeDto(1019,"MG 12","MG12"),
            new DocumentCmsTypeDto(1040,"MG 13","MG13"),
            new DocumentCmsTypeDto(1041,"MG 14","MG14"),
            new DocumentCmsTypeDto(1062,"MG 15(CNOI)","MG15(CNOI)"),
            new DocumentCmsTypeDto(1021,"MG 15(CONT)","MG15(CONT)"),
            new DocumentCmsTypeDto(1020,"MG 15(ROTI)","MG15(ROTI)"),
            new DocumentCmsTypeDto(1044,"MG 15(ROVI)","MG15(ROVI)"),
            new DocumentCmsTypeDto(1042,"MG 15(SDN)","MG15(SDN)"),
            new DocumentCmsTypeDto(1022,"MG 15(T)","MG15(T)"),
            new DocumentCmsTypeDto(1023,"MG 15(T)(CONT)","MG15(T)(CONT)"),
            new DocumentCmsTypeDto(1063,"MG 16","MG16"),
            new DocumentCmsTypeDto(1045,"MG 16(DBCI)","MG16(DBCI)"),
            new DocumentCmsTypeDto(1046,"MG 16(DDOI)","MG16(DDOI)"),
            new DocumentCmsTypeDto(1047,"MG 17","MG17"),
            new DocumentCmsTypeDto(1024,"MG 18","MG18"),
            new DocumentCmsTypeDto(1033,"MG 2","MG2"),
            new DocumentCmsTypeDto(1026,"MG 20","MG20"),
            new DocumentCmsTypeDto(1048,"MG 21","MG21"),
            new DocumentCmsTypeDto(1049,"MG 21A","MG21A"),
            new DocumentCmsTypeDto(1034,"MG 3","MG3"),
            new DocumentCmsTypeDto(1035,"MG 3A","MG3A"),
            new DocumentCmsTypeDto(1002,"MG 4","MG4"),
            new DocumentCmsTypeDto(1037,"MG 4(Post)","MG4(Post)"),
            new DocumentCmsTypeDto(1003,"MG 4A","MG4A"),
            new DocumentCmsTypeDto(1004,"MG 4B","MG4B"),
            new DocumentCmsTypeDto(1005,"MG 4C","MG4C"),
            new DocumentCmsTypeDto(1060,"MG 4D","MG4D"),
            new DocumentCmsTypeDto(1061,"MG 4E","MG4E"),
            new DocumentCmsTypeDto(1036,"MG 4F","MG4F"),
            new DocumentCmsTypeDto(1006,"MG 5","MG5"),
            new DocumentCmsTypeDto(1038,"MG 5(SP)","MG5(SP)"),
            new DocumentCmsTypeDto(1039,"MG 6A","MG6A"),
            new DocumentCmsTypeDto(1008,"MG 6B","MG6B"),
            new DocumentCmsTypeDto(1009,"MG 6C","MG6C"),
            new DocumentCmsTypeDto(1010,"MG 6D","MG6D"),
            new DocumentCmsTypeDto(1011,"MG 6E","MG6E"),
            new DocumentCmsTypeDto(1012,"MG 7","MG7"),
            new DocumentCmsTypeDto(1013,"MG 8","MG8"),
            new DocumentCmsTypeDto(1014,"MG 9","MG9"),
            new DocumentCmsTypeDto(1027,"MG/FSS A","MG/FSS A"),
            new DocumentCmsTypeDto(1028,"MG/FSS B","MG/FSS B"),
            new DocumentCmsTypeDto(516,"MG17","MG17"),
            new DocumentCmsTypeDto(1025,"MG19","MG19"),
            new DocumentCmsTypeDto(1203,"MG22 SFR","MG22 SFR"),
            new DocumentCmsTypeDto(101,"MG3","MG3"),
            new DocumentCmsTypeDto(102,"MG3A","MG3A"),
            new DocumentCmsTypeDto(104,"MG3AS","MG3A (with Schedule of Charges)"),
            new DocumentCmsTypeDto(103,"MG3S","MG3 (with Schedule of Charges)"),
            new DocumentCmsTypeDto(1007,"MG6","MG6"),
            new DocumentCmsTypeDto(1050,"MGDD","MGDD"),
            new DocumentCmsTypeDto(69,"MIC01","MIC1"),
            new DocumentCmsTypeDto(100082,"MSCTEST","TEST2"),
            new DocumentCmsTypeDto(100055,"MYDOC10","MYDOC10NAME"),
            new DocumentCmsTypeDto(100187,"MoreNeeds","MoreNeeds"),
            new DocumentCmsTypeDto(70,"NEA01","Offer No Evidence (CC)"),
            new DocumentCmsTypeDto(71,"NFE01","Notice Further Evidence"),
            new DocumentCmsTypeDto(72,"NFE02","Letter (CC)"),
            new DocumentCmsTypeDto(73,"NFE03","Letter (Police)"),
            new DocumentCmsTypeDto(74,"NFE04","Letter (Def)"),
            new DocumentCmsTypeDto(175,"NFR-CCF1","Report to Supervising Lawyer"),
            new DocumentCmsTypeDto(176,"NFR-CCF2","Case Diary Plan"),
            new DocumentCmsTypeDto(177,"NFR-CCF3","Case Activity Log"),
            new DocumentCmsTypeDto(158,"NFR-HE1","Hearsay Notice"),
            new DocumentCmsTypeDto(159,"NFR-HE2","Hearsay Exclusion Application after Notice"),
            new DocumentCmsTypeDto(196,"NFR-HE3","Hearsay Exclusion Application without Notice"),
            new DocumentCmsTypeDto(517,"NFR-PS1","Plea and Sentence"),
            new DocumentCmsTypeDto(100115,"NH2","NH2"),
            new DocumentCmsTypeDto(75,"NT01","Form 1 Notice (CC)"),
            new DocumentCmsTypeDto(76,"NT02","Form 2 Notice (Def)"),
            new DocumentCmsTypeDto(77,"NT03","Consent Form (Custody)"),
            new DocumentCmsTypeDto(100186,"Needs","needs"),
            new DocumentCmsTypeDto(100074,"OR18929","Check"),
            new DocumentCmsTypeDto(100075,"OR18929-2","Both Logo and text"),
            new DocumentCmsTypeDto(100161,"OR19559","OR19559 Test"),
            new DocumentCmsTypeDto(1030,"OTHER EXHIBIT","Other Exhibit"),
            new DocumentCmsTypeDto(1200,"OTHER MATERIAL","Other Material"),
            new DocumentCmsTypeDto(1056,"PCN 1","PCN1"),
            new DocumentCmsTypeDto(1057,"PCN 2","PCN2"),
            new DocumentCmsTypeDto(1058,"PCN 3","PCN3"),
            new DocumentCmsTypeDto(218,"PCREng","Requisition (English)"),
            new DocumentCmsTypeDto(219,"PCRWel","Requisition (Welsh)"),
            new DocumentCmsTypeDto(1051,"PE 1","PE1"),
            new DocumentCmsTypeDto(1052,"PE 2","PE2"),
            new DocumentCmsTypeDto(1053,"PE 3","PE3"),
            new DocumentCmsTypeDto(1054,"PE 4","PE4"),
            new DocumentCmsTypeDto(100235,"PFD01","Protection of Children - Request for Disc"),
            new DocumentCmsTypeDto(225583,"PFD01","Protection of Children - Request for Disc"),
            new DocumentCmsTypeDto(100234,"PFD02-","Standard Request for Police Information"),
            new DocumentCmsTypeDto(225584,"PFD02-","Standard Request for Police Information"),
            new DocumentCmsTypeDto(100236,"PFD03","Notice to Local Auth - CPIA Disclosure Test"),
            new DocumentCmsTypeDto(225581,"PFD03","Notice to Local Auth - CPIA Disclosure Test"),
            new DocumentCmsTypeDto(100233,"PFD04","Notice from Local Auth - Representations on Disc"),
            new DocumentCmsTypeDto(225582,"PFD04","Notice from Local Auth - Representations on Disc"),
            new DocumentCmsTypeDto(100204,"PJM1","Paula"),
            new DocumentCmsTypeDto(100214,"PLEA1","PLEA1"),
            new DocumentCmsTypeDto(100242,"POC01","Proceeds of Crime"),
            new DocumentCmsTypeDto(100251,"POC02-new","POC02-local"),
            new DocumentCmsTypeDto(100244,"POL02","Proceeds of Crime-local"),
            new DocumentCmsTypeDto(68,"POL1","Police Memo"),
            new DocumentCmsTypeDto(110,"POL2","Pre-charge Police Memo"),
            new DocumentCmsTypeDto(160,"POL3","Quick Police Memo"),
            new DocumentCmsTypeDto(203,"PRMB","Post Review Meeting Briefing"),
            new DocumentCmsTypeDto(78,"PSR","PSR (MC)"),
            new DocumentCmsTypeDto(183,"PSR02","PSR (CC)"),
            new DocumentCmsTypeDto(100224,"PTPH","PTPH Form"),
            new DocumentCmsTypeDto(100223,"PTPH-RG1","Test PTPH Final"),
            new DocumentCmsTypeDto(100215,"PTPH1","Plea and Trial Hearing Form"),
            new DocumentCmsTypeDto(100216,"PTPH2","Plea and Trial Preparation Hearing Form 2"),
            new DocumentCmsTypeDto(100217,"PTPH3","Plea and Trial Hearing Form 1"),
            new DocumentCmsTypeDto(100218,"PTPH5","Plea and Trial Preparation Hearing Form"),
            new DocumentCmsTypeDto(100221,"PTPH6","PTPH DCS RP"),
            new DocumentCmsTypeDto(100222,"PTPHTest","PTPH Final Version"),
            new DocumentCmsTypeDto(100016,"Pre-Deploy","Pre-Deploy"),
            new DocumentCmsTypeDto(100243,"Proceeds of Crime","POC01"),
            new DocumentCmsTypeDto(189,"REV1","Review Document"),
            new DocumentCmsTypeDto(212,"REVIEW","Standard Review"),
            new DocumentCmsTypeDto(100219,"RG1","PTPH Test"),
            new DocumentCmsTypeDto(100220,"RG2","PTPH Test DCS"),
            new DocumentCmsTypeDto(79,"RID1","RID1"),
            new DocumentCmsTypeDto(181,"RP1","Rape Prosecution Essential Steps Monitoring"),
            new DocumentCmsTypeDto(182,"RP2","Rape Pros Decision Making Quality Monitoring"),
            new DocumentCmsTypeDto(512,"RRA01","Reporting Restrictions (MC)"),
            new DocumentCmsTypeDto(513,"RRA02","Reporting Restrictions (CC)"),
            new DocumentCmsTypeDto(100141,"Rubbish","Rubbish"),
            new DocumentCmsTypeDto(80,"S9","S9 Notice"),
            new DocumentCmsTypeDto(100067,"SB AP4 Two","SB AP4 Two"),
            new DocumentCmsTypeDto(81,"SC01","Schedule of Charges"),
            new DocumentCmsTypeDto(1202,"SDC","Streamlined Disclosure Certificate"),
            new DocumentCmsTypeDto(100068,"SJB AP4 Tw","SJB Ap4 Two"),
            new DocumentCmsTypeDto(100249,"SMOKE 04MAR","New 04MAR"),
            new DocumentCmsTypeDto(100237,"SMOKE0502","New0502"),
            new DocumentCmsTypeDto(100130,"SMOKE1","Local Doc"),
            new DocumentCmsTypeDto(100149,"SMOKE1","New18JUN"),
            new DocumentCmsTypeDto(100139,"SMOKE11","New17MAY"),
            new DocumentCmsTypeDto(100150,"SMOKE2","new19JUN"),
            new DocumentCmsTypeDto(100162,"SMOKE2","New09JUL"),
            new DocumentCmsTypeDto(100151,"SMOKE2a","44731"),
            new DocumentCmsTypeDto(100194,"SMOKEE1","New25Oct"),
            new DocumentCmsTypeDto(100238,"SMOKEe0502","NEWNEW0502"),
            new DocumentCmsTypeDto(100231,"STWAC01","Record Conversation(s) with Witnesses"),
            new DocumentCmsTypeDto(100020,"Stephen28","Stephen28"),
            new DocumentCmsTypeDto(100060,"TEAM","TESTING"),
            new DocumentCmsTypeDto(100001,"TEMP1","Local Temp CoverLetter"),
            new DocumentCmsTypeDto(100129,"TEMP1a","Local Temp Cover Letter"),
            new DocumentCmsTypeDto(100002,"TEMP2","Local Temp CoverLetter2"),
            new DocumentCmsTypeDto(100179,"TEMP2","Local Temp CoverLetter"),
            new DocumentCmsTypeDto(100094,"TEST","ZZLHTEST"),
            new DocumentCmsTypeDto(100246,"TEST-LOCAL_doc","LOCAL-DOC"),
            new DocumentCmsTypeDto(100229,"TESTWW","TESTWW"),
            new DocumentCmsTypeDto(100202,"TFS1126","Abbrev. no.space def. and charg."),
            new DocumentCmsTypeDto(100203,"TFS1127","Abbrev. no.space def. and charg."),
            new DocumentCmsTypeDto(100018,"TH01","Template1"),
            new DocumentCmsTypeDto(100019,"THA02","Temp2forTestingMissingTemplates"),
            new DocumentCmsTypeDto(100000,"Test","Test"),
            new DocumentCmsTypeDto(100180,"Test temp2","Local temp coverletter test"),
            new DocumentCmsTypeDto(100189,"TestDot","AW"),
            new DocumentCmsTypeDto(100152,"TestExplos","TestExplosion"),
            new DocumentCmsTypeDto(1029,"UNKNOWN","Other Comm (In)"),
            new DocumentCmsTypeDto(100069,"URNx","URNx"),
            new DocumentCmsTypeDto(180,"VFS1","Victim Focus Scheme"),
            new DocumentCmsTypeDto(165,"VHCC1","Advice/Pre-send Reduced Scheme"),
            new DocumentCmsTypeDto(166,"VHCC2","Higher Court Reduced Scheme"),
            new DocumentCmsTypeDto(167,"VHCC3","Advice/Pre-send Full Scheme"),
            new DocumentCmsTypeDto(168,"VHCC4","Crown Court Case"),
            new DocumentCmsTypeDto(169,"VHCC5","Higher Court Full Scheme"),
            new DocumentCmsTypeDto(170,"VHCC6","Crown Court Fee Scheme"),
            new DocumentCmsTypeDto(171,"VHCC7","Magistrates' Court Case"),
            new DocumentCmsTypeDto(172,"VHCC8","VHCC - Stage Plan"),
            new DocumentCmsTypeDto(173,"VHCC9","VHCC - Case Plan"),
            new DocumentCmsTypeDto(514,"VIW01","Record of ESM Meeting"),
            new DocumentCmsTypeDto(515,"VIW02","Record of Prosecutors Meeting"),
            new DocumentCmsTypeDto(86,"VIW03","Special Measures Application (MC)"),
            new DocumentCmsTypeDto(87,"VIW04","Special Measures Application (CC)"),
            new DocumentCmsTypeDto(88,"VIW05","Transcript Request (VIW05)"),
            new DocumentCmsTypeDto(106,"VIW07","Special Measures Extension Applic"),
            new DocumentCmsTypeDto(107,"VIW08","Special Measures Applic Out of Time"),
            new DocumentCmsTypeDto(187,"VIW11","Special Measures Application (MC/CC)"),
            new DocumentCmsTypeDto(100117,"WCU","WCU"),
            new DocumentCmsTypeDto(82,"WEF04","LWAC"),
            new DocumentCmsTypeDto(135,"WEF04(Cont)","LWAC Continuation"),
            new DocumentCmsTypeDto(179,"WEFLabel","Witness Expense Form Labels"),
            new DocumentCmsTypeDto(226,"WIH01","Witnesses In Hearing"),
            new DocumentCmsTypeDto(10002,"WMS-B1","Introduction - no PMoC identified"),
            new DocumentCmsTypeDto(10011,"WMS-B10","Def on Warrant"),
            new DocumentCmsTypeDto(100211,"WMS-B10","blobby"),
            new DocumentCmsTypeDto(10509,"WMS-B10G","Def on Warrant (Guardian)"),
            new DocumentCmsTypeDto(10609,"WMS-B10GW","Def on Warrant (G) (W)"),
            new DocumentCmsTypeDto(10028,"WMS-B10W","Def on Warrant (Welsh)"),
            new DocumentCmsTypeDto(10012,"WMS-B11","Guilty Plea - Adj For Sentence"),
            new DocumentCmsTypeDto(10510,"WMS-B11G","Guilty Plea - Adj For Sentence (Guardian)"),
            new DocumentCmsTypeDto(10610,"WMS-B11GW","Guilty Plea - Adj For Sentence (G) (W)"),
            new DocumentCmsTypeDto(10029,"WMS-B11W","Guilty Plea - Adj For Sentence (Welsh)"),
            new DocumentCmsTypeDto(10013,"WMS-B12","Guilty Plea - Def Sentenced"),
            new DocumentCmsTypeDto(10511,"WMS-B12G","Guilty Plea - Def Sentenced (Guardian)"),
            new DocumentCmsTypeDto(10611,"WMS-B12GW","Guilty Plea - Def Sentenced (G) (W)"),
            new DocumentCmsTypeDto(10030,"WMS-B12W","Guilty Plea - Def Sentenced (Welsh)"),
            new DocumentCmsTypeDto(10014,"WMS-B13","Conviction After Trial - Adj For Sentence"),
            new DocumentCmsTypeDto(10512,"WMS-B13G","Conviction After Trial - Adj For Sentence (G)"),
            new DocumentCmsTypeDto(10612,"WMS-B13GW","Conviction After Trial - Adj For Sentence (G) (W)"),
            new DocumentCmsTypeDto(10031,"WMS-B13W","Conviction After Trial - Adj For Sentence (Welsh)"),
            new DocumentCmsTypeDto(10015,"WMS-B14","Conviction After Trial - Def Sentenced"),
            new DocumentCmsTypeDto(10513,"WMS-B14G","Conviction After Trial - Def Sentenced (Guardian)"),
            new DocumentCmsTypeDto(10613,"WMS-B14GW","Conviction After Trial - Def Sentenced (G) (W)"),
            new DocumentCmsTypeDto(10032,"WMS-B14W","Conviction After Trial - Def Sentenced (Welsh)"),
            new DocumentCmsTypeDto(10016,"WMS-B15","Not Guilty After Trial"),
            new DocumentCmsTypeDto(10514,"WMS-B15G","Not Guilty After Trial (Guardian)"),
            new DocumentCmsTypeDto(10614,"WMS-B15GW","Not Guilty After Trial (G) (W)"),
            new DocumentCmsTypeDto(10033,"WMS-B15W","Not Guilty After Trial (Welsh)"),
            new DocumentCmsTypeDto(10500,"WMS-B1G","Introduction - no PMoC identified  (Guardian)"),
            new DocumentCmsTypeDto(10600,"WMS-B1GW","Introduction - no PMoC identified  (G) (W)"),
            new DocumentCmsTypeDto(10019,"WMS-B1W","Introduction - no PMoC identified (Welsh)"),
            new DocumentCmsTypeDto(10003,"WMS-B2","Introduction - PMoC letter"),
            new DocumentCmsTypeDto(10020,"WMS-B2W","Introduction - PMoC letter (Welsh)"),
            new DocumentCmsTypeDto(10004,"WMS-B3","Introduction - PMoC telephone"),
            new DocumentCmsTypeDto(10021,"WMS-B3W","Introduction - PMoC telephone (Welsh)"),
            new DocumentCmsTypeDto(10005,"WMS-B4","Guilty Plea and Sentence at First Hearing"),
            new DocumentCmsTypeDto(10501,"WMS-B4G","Guilty Plea and Sentence First Hearing (Guardian)"),
            new DocumentCmsTypeDto(10601,"WMS-B4GW","Guilty Plea and Sentence First Hearing (G) (W)"),
            new DocumentCmsTypeDto(10022,"WMS-B4W","Guilty Plea and Sentence at First Hearing (Welsh)"),
            new DocumentCmsTypeDto(10006,"WMS-B5","Not Guilty Plea at First Hearing"),
            new DocumentCmsTypeDto(10502,"WMS-B5G","Not Guilty Plea at First Hearing (Guardian)"),
            new DocumentCmsTypeDto(10602,"WMS-B5GW","Not Guilty Plea at First Hearing (G) (W)"),
            new DocumentCmsTypeDto(10023,"WMS-B5W","Not Guilty Plea at First Hearing (Welsh)"),
            new DocumentCmsTypeDto(10007,"WMS-B6","Availability for Trial"),
            new DocumentCmsTypeDto(10503,"WMS-B6G","Availability for Trial (Guardian)"),
            new DocumentCmsTypeDto(10603,"WMS-B6GW","Availability for Trial (G) (W)"),
            new DocumentCmsTypeDto(10024,"WMS-B6W","Availability for Trial (Welsh)"),
            new DocumentCmsTypeDto(10008,"WMS-B7","Witness Warning - MC"),
            new DocumentCmsTypeDto(10504,"WMS-B7G","Witness Warning - MC (Guardian)"),
            new DocumentCmsTypeDto(10604,"WMS-B7GW","Witness Warning - MC (G) (W)"),
            new DocumentCmsTypeDto(10025,"WMS-B7W","Witness Warning - MC (Welsh)"),
            new DocumentCmsTypeDto(10009,"WMS-B8","Witness Warning - CC"),
            new DocumentCmsTypeDto(10505,"WMS-B8G","Witness Warning - CC (Guardian)"),
            new DocumentCmsTypeDto(10605,"WMS-B8GW","Witness Warning - CC (G) (W)"),
            new DocumentCmsTypeDto(10506,"WMS-B8R","Witness Warning - CC (Reserve)"),
            new DocumentCmsTypeDto(10507,"WMS-B8RG","Witness Warning - CC ( Reserve Guardian)"),
            new DocumentCmsTypeDto(10607,"WMS-B8RGW","Witness Warning - CC ( Reserve Guardian) (W)"),
            new DocumentCmsTypeDto(10606,"WMS-B8RW","Witness Warning - CC (Reserve) (W)"),
            new DocumentCmsTypeDto(10026,"WMS-B8W","Witness Warning - CC (Welsh)"),
            new DocumentCmsTypeDto(10010,"WMS-B9","Attendance Not Required at Court"),
            new DocumentCmsTypeDto(10508,"WMS-B9G","Attendance Not Required at Court  (Guardian)"),
            new DocumentCmsTypeDto(10608,"WMS-B9GW","Attendance Not Required at Court  (G) (W)"),
            new DocumentCmsTypeDto(10027,"WMS-B9W","Attendance Not Required at Court (Welsh)"),
            new DocumentCmsTypeDto(10517,"WMS-GU","General update - Case"),
            new DocumentCmsTypeDto(10518,"WMS-GUG","General update - Case (Guardian)"),
            new DocumentCmsTypeDto(10618,"WMS-GUGW","General update - Case (G) (W)"),
            new DocumentCmsTypeDto(10617,"WMS-GUW","General update - Case (W)"),
            new DocumentCmsTypeDto(10018,"WMS-LogoLeft","LetterheadLogoLeft"),
            new DocumentCmsTypeDto(10017,"WMS-LogoRight","LetterheadLogoRight"),
            new DocumentCmsTypeDto(10515,"WMS-PWLC","Requirement to attend court - Crown"),
            new DocumentCmsTypeDto(10516,"WMS-PWLM","Requirement to attend court - Magistrates"),
            new DocumentCmsTypeDto(10034,"WMS-WEFLabel","Witness Expense Form Labels"),
            new DocumentCmsTypeDto(10001,"WMS001","Blank Needs Assessment Form"),
            new DocumentCmsTypeDto(100135,"Witness99","Witness99"),
            new DocumentCmsTypeDto(100061,"Z2TEST1","TEST11"),
            new DocumentCmsTypeDto(100188,"ZNeeds","ZNeeds"),
            new DocumentCmsTypeDto(100127,"ZZDEF1","ZZDEF1NAME"),
            new DocumentCmsTypeDto(100128,"ZZDEF2","ZZDEF2NAME"),
            new DocumentCmsTypeDto(100210,"ZZ_A","ZZ_A_NAME"),
            new DocumentCmsTypeDto(100205,"ZZ_BD18","ZZ_BD18test"),
            new DocumentCmsTypeDto(100145,"a1","a1"),
            new DocumentCmsTypeDto(100144,"a11","a11"),
            new DocumentCmsTypeDto(100148,"a1b","a1b"),
            new DocumentCmsTypeDto(100146,"a2","s2"),
            new DocumentCmsTypeDto(100159,"aOr19513","aOr19513"),
            new DocumentCmsTypeDto(100208,"aaa","aaaaarrow"),
            new DocumentCmsTypeDto(100191,"aaaaa","aaaaa"),
            new DocumentCmsTypeDto(100133,"aaaaaa","aaaaaa"),
            new DocumentCmsTypeDto(100012,"aaaaaaaa","bbbbbb"),
            new DocumentCmsTypeDto(100005,"aaaaaaaaaa","aaaaaaaaaa"),
            new DocumentCmsTypeDto(100105,"aaacode","zortest"),
            new DocumentCmsTypeDto(100132,"aazacube","aazacube"),
            new DocumentCmsTypeDto(100131,"aazcube","aazcube"),
            new DocumentCmsTypeDto(100171,"abacode","abarcode"),
            new DocumentCmsTypeDto(100134,"abc","abc"),
            new DocumentCmsTypeDto(100137,"abtest","abtest"),
            new DocumentCmsTypeDto(100048,"ap4 test","ap4 test"),
            new DocumentCmsTypeDto(100172,"aplam","aplam"),
            new DocumentCmsTypeDto(100039,"apt 4 thre","ap4 thre"),
            new DocumentCmsTypeDto(100158,"atemplateN","atemplatfgtrgfredsefghhjjkkkll"),
            new DocumentCmsTypeDto(100138,"awms","awms"),
            new DocumentCmsTypeDto(100006,"bbbbb","bbbbb"),
            new DocumentCmsTypeDto(100142,"bottom","bottom"),
            new DocumentCmsTypeDto(100007,"ccc","ccc"),
            new DocumentCmsTypeDto(100174,"ccr4561","ccr4561"),
            new DocumentCmsTypeDto(100080,"cha","cha"),
            new DocumentCmsTypeDto(100081,"cha1","cha1"),
            new DocumentCmsTypeDto(100125,"chacourt","chacourt"),
            new DocumentCmsTypeDto(100124,"chadd2","chadd2"),
            new DocumentCmsTypeDto(100035,"cmsap4","cmsap4"),
            new DocumentCmsTypeDto(100147,"con","con"),
            new DocumentCmsTypeDto(100079,"createddat","createddate"),
            new DocumentCmsTypeDto(100066,"d2","d2"),
            new DocumentCmsTypeDto(100014,"datr","dater"),
            new DocumentCmsTypeDto(100086,"db1","db1"),
            new DocumentCmsTypeDto(100091,"db1","db1"),
            new DocumentCmsTypeDto(100087,"dbwithtext","dbwithtext"),
            new DocumentCmsTypeDto(100072,"dc","dc"),
            new DocumentCmsTypeDto(100008,"dddd","dddd"),
            new DocumentCmsTypeDto(100184,"fantasy","fantasy"),
            new DocumentCmsTypeDto(100164,"jgtemp1","jglocal temp cover letter"),
            new DocumentCmsTypeDto(100043,"m1","m1"),
            new DocumentCmsTypeDto(100044,"m11","m11"),
            new DocumentCmsTypeDto(100042,"ma1","ma1"),
            new DocumentCmsTypeDto(100073,"new boy","newboy"),
            new DocumentCmsTypeDto(100078,"none","none"),
            new DocumentCmsTypeDto(100088,"noneincl","noneincl"),
            new DocumentCmsTypeDto(100089,"noneincl","noneincl"),
            new DocumentCmsTypeDto(100054,"or18850","test"),
            new DocumentCmsTypeDto(100136,"rach1","rach1"),
            new DocumentCmsTypeDto(100163,"rachel","rachel"),
            new DocumentCmsTypeDto(100143,"red","red"),
            new DocumentCmsTypeDto(192,"s51(Ct)","s51 Cover (Court)"),
            new DocumentCmsTypeDto(193,"s51(Def)","s51 Cover (Defence)"),
            new DocumentCmsTypeDto(194,"s51(Pol)","s51 Cover (Police)"),
            new DocumentCmsTypeDto(100197,"sdfsd","sdfsdfsdf"),
            new DocumentCmsTypeDto(100195,"smoke6","new28oct"),
            new DocumentCmsTypeDto(100167,"ssss","ssss"),
            new DocumentCmsTypeDto(100021,"stephen29","zzz10"),
            new DocumentCmsTypeDto(100207,"sum","sum"),
            new DocumentCmsTypeDto(100049,"systemtest","systemtest"),
            new DocumentCmsTypeDto(100250,"temp","local temp cover letter"),
            new DocumentCmsTypeDto(100010,"temp1","Local Temp Cover letter"),
            new DocumentCmsTypeDto(100093,"temp12","TempLocalCoverLetter2"),
            new DocumentCmsTypeDto(100050,"template","template"),
            new DocumentCmsTypeDto(100045,"test2010","test20"),
            new DocumentCmsTypeDto(100046,"test20101","test20101"),
            new DocumentCmsTypeDto(100192,"tst spc ch","Test on 17/10/2013"),
            new DocumentCmsTypeDto(100193,"tst- ash","Ashley doc on 17/10"),
            new DocumentCmsTypeDto(100070,"ttttcode","ttttname"),
            new DocumentCmsTypeDto(100063,"urn","urn"),
            new DocumentCmsTypeDto(100064,"urn2","urn2"),
            new DocumentCmsTypeDto(100003,"uy","u6"),
            new DocumentCmsTypeDto(100013,"w","q"),
            new DocumentCmsTypeDto(100206,"xtl","xtl"),
            new DocumentCmsTypeDto(100095,"xx19119","xx19119"),
            new DocumentCmsTypeDto(100166,"xxx","xxxx"),
            new DocumentCmsTypeDto(100062,"xyz","xyz"),
            new DocumentCmsTypeDto(100009,"yygygyyhy","vytfty"),
            new DocumentCmsTypeDto(100017,"yyy","yyy"),
            new DocumentCmsTypeDto(100025,"z1","z1"),
            new DocumentCmsTypeDto(100100,"z1","z1"),
            new DocumentCmsTypeDto(100028,"z10","z10 word2010 bc"),
            new DocumentCmsTypeDto(100029,"z11","2010 template"),
            new DocumentCmsTypeDto(100026,"z2","z2"),
            new DocumentCmsTypeDto(100033,"z55","z55"),
            new DocumentCmsTypeDto(100027,"z9","z9"),
            new DocumentCmsTypeDto(100114,"zRevCat","zRevCat"),
            new DocumentCmsTypeDto(100185,"zdec","zdec"),
            new DocumentCmsTypeDto(100106,"zortest","zortest"),
            new DocumentCmsTypeDto(100201,"zpaula","zpaula"),
            new DocumentCmsTypeDto(100111,"zubairtest","zubairtest"),
            new DocumentCmsTypeDto(100036,"zz","zz"),
            new DocumentCmsTypeDto(100098,"zz A4 One","zz AP4 One"),
            new DocumentCmsTypeDto(100096,"zz AP4 Two","zz AP4 Two"),
            new DocumentCmsTypeDto(100030,"zz11","zz11 2010 template"),
            new DocumentCmsTypeDto(100032,"zzStephen2","zzStephen2"),
            new DocumentCmsTypeDto(100031,"zzstephen","zzstephen"),
            new DocumentCmsTypeDto(100037,"zzz","zzz"),
            new DocumentCmsTypeDto(100015,"zzz","zzz"),
            new DocumentCmsTypeDto(100022,"zzzurn2","zzzurn2"),
            new DocumentCmsTypeDto(100023,"zzzurn3","zzzurn3"),
            new DocumentCmsTypeDto(100024,"zzzzz","zzzzz"),
            new DocumentCmsTypeDto(100047,"zzzzz1999","zzzzz1999"),
#endregion
        };

        static Dictionary<int, DocumentCmsTypeDto> _documentCmsTypeLookups = new Dictionary<int, DocumentCmsTypeDto>();

        static DocumentCmsTypes()
        {
            foreach (var documentCmsType in _documentCmsTypes)
            {
                _documentCmsTypeLookups[documentCmsType.Id] = documentCmsType;
            }
        }

        public static DocumentCmsTypeDto Lookup(int id)
        {
            return _documentCmsTypeLookups[id];
        }
    }
}