trigger:
  branches:
    include:
    - main
    - feature/*
    - release/*
    - bug/*

  paths:
    include:
    - "polaris-pipeline/text-extractor/*"

pool:
  vmImage: "ubuntu-latest"

variables:
  rootFolder: "polaris-pipeline"
  functionName: "text-extractor"
  buildConfiguration: "Release"

steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: "build"
      projects: "$(rootFolder)/$(functionName)/$(functionName).csproj"
      arguments: "--configuration $(buildConfiguration)"
    displayName: "Build"

  - task: DotNetCoreCLI@2
    inputs:
      command: "test"
      projects: "$(rootFolder)/$(functionName)*tests/$(functionName)*tests.csproj"
      arguments: "--configuration $(buildConfiguration)"
    displayName: "Run tests"

  - task: DotNetCoreCLI@2
    inputs:
      command: publish
      publishWebProjects: false
      projects: "$(rootFolder)/$(functionName)/$(functionName).csproj"
      arguments: "--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)"
      zipAfterPublish: False
    displayName: "Publish"

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: "$(Build.ArtifactStagingDirectory)"
      artifactName: "$(functionName)-drop"
      publishLocation: "Container"
