# Build and Publish Artifact Azure DevOps pipeline for Polaris Terraform and Codebase

name: '$(majorMinorVersion).$(Year:yy)$(DayOfYear).$(semanticVersion)'

trigger: none
#  batch: true
#  branches:
#    include:
#      - main

#  paths:
#    include:
#      - "polaris-gateway/polaris-auth-handover/*"
#      - "polaris-pipeline/Common/*"
#      - "polaris-pipeline/Common.tests/*"
#      - "polaris-gateway/polaris-gateway/*"
#      - "polaris-gateway/polaris-gateway.tests/*"
#      - "polaris-gateway/polaris-gateway.common/*"
#      - "polaris-pipeline/coordinator/*"
#      - "polaris-pipeline/coordinator.tests/*"
#      - "polaris-pipeline/pdf-generator/*"
#      - "polaris-pipeline/pdf-generator.tests/*"
#      - "polaris-pipeline/text-extractor/*"
#      - "polaris-pipeline/text-extractor.tests/*"
#      - "polaris-terraform/pipeline-terraform/*"
#      - "polaris-terraform/pipeline-events-terraform/*"
#      - "polaris-terraform/ui-terraform/*"
#      - "polaris-terraform/ui-events-terraform/*"
        
