---
trigger: none
pr: none

resources:
  pipelines:
    - pipeline: PolarisTerraformBuild
      source: Polaris Terraform - Build
      trigger:
        branches:
          include:
            - refs/heads/main
        stages:
          - Publish_Artifacts

variables:
  - group: kv-dev-terraform
  - group: kv-qa-terraform
  - group: kv-prod-terraform
  - group: polaris-global
  - group: terraform-containers

stages:
  # Apply terraform to DEV
  - template: ../templates/stages/stage_deploy-terraform.yml
    parameters:
      stageBuildAgent: $(dev-build-agent)
      stageDependsOn:
      envLabel: "Dev"
      targetBuild: PolarisTerraformBuild
      targetLabel: "DEV"
      targetSuffix: "-dev"
      targetPlanName: "dev"
      appInsightsKey: "$(innovation-development-app-insights-instrumentation-key)"
      terraformStorageAccount: $(dev-terraform-storage-account)
      terraformPipelineContainerName: $(pipeline-terraform-container-name)
      terraformPipelineEventsContainerName: $(pipeline-events-terraform-container-name)
      terraformUIContainerName: $(ui-terraform-container-name)
      terraformUIEventsContainerName: $(ui-events-terraform-container-name)
      terraformStateKey: $(terraform-key)
      terraformStateAccessKey: $(cpsdevstorageterraform-key1)
      armClientId: $(innovation-development-spn-client-id)
      armClientSecret: $(innovation-development-spn-secret)
      armTenantId: $(innovation-development-spn-tenant-id)
      armSubscriptionId: $(innovation-development-subscription-id)
      devOpsPatToken: $(devops-pat-token)
      azureSubscription: $(dev-azure-subscription)
      logRetentionTime: $(log-retention-time)
      totalLogRetentionTime: $(total-log-retention-time)
      
  # Env Check: Run e2e Tests against DEV
  - template: ../templates/stages/stage_run-e2e-tests.yml
    parameters:
      stageBuildAgent: $(dev-build-agent)
      stageDependsOn: Terraform_DEV
      targetBuild: PolarisTerraformBuild
      targetLabel: "DEV"
      targetName: "e2e Tests"
      buildDefinitionId: 129
      appInsightsKey: "$(innovation-development-app-insights-instrumentation-key)"
      devOpsPatToken: "$(devops-pat-token)"
      
  # Apply Terraform to QA
  - template: ../templates/stages/stage_deploy-pipeline-terraform.yml
    parameters:
      stageBuildAgent: $(qa-build-agent)
      stageDependsOn: Run_e2e_Tests_DEV
      envLabel: "QA"
      targetBuild: PolarisTerraformBuild
      targetLabel: "QA"
      targetSuffix: "-qa"
      targetPlanName: "qa"
      appInsightsKey: "$(innovation-qa-app-insights-instrumentation-key)"
      terraformStorageAccount: $(qa-terraform-storage-account)
      terraformPipelineContainerName: $(pipeline-terraform-container-name)
      terraformPipelineEventsContainerName: $(pipeline-events-terraform-container-name)
      terraformUIContainerName: $(ui-terraform-container-name)
      terraformUIEventsContainerName: $(ui-events-terraform-container-name)
      terraformStateKey: $(terraform-key)
      terraformStateAccessKey: $(cpsqastorageterraform-key1)
      armClientId: $(innovation-qa-spn-client-id)
      armClientSecret: $(innovation-qa-spn-secret)
      armTenantId: $(innovation-qa-spn-tenant-id)
      armSubscriptionId: $(innovation-qa-subscription-id)
      devOpsPatToken: $(devops-pat-token)
      azureSubscription: $(qa-azure-subscription)
      logRetentionTime: $(log-retention-time)
      totalLogRetentionTime: $(total-log-retention-time)

  # Env Check: Run e2e Tests Against QA
  - template: ../templates/stages/stage_run-e2e-tests.yml
    parameters:
      stageBuildAgent: $(qa-build-agent)
      stageDependsOn: Terraform_QA
      targetBuild: PolarisTerraformBuild
      targetLabel: "QA"
      targetName: "e2e Tests"
      buildDefinitionId: 210
      appInsightsKey: "$(innovation-qa-app-insights-instrumentation-key)"
      devOpsPatToken: "$(devops-pat-token)"

  # Apply Terraform to PROD
  - template: ../templates/stages/stage_deploy-terraform.yml
    parameters:
      stageBuildAgent: $(prod-build-agent)
      stageDependsOn: Run_e2e_Tests_DEV
      envLabel: "Prod"
      targetBuild: PolarisTerraformBuild
      targetLabel: "PROD"
      targetSuffix: ""
      targetPlanName: "prod"
      appInsightsKey: "$(innovation-prod-app-insights-instrumentation-key)"
      terraformStorageAccount: $(prod-terraform-storage-account)
      terraformPipelineContainerName: $(pipeline-terraform-container-name)
      terraformPipelineEventsContainerName: $(pipeline-events-terraform-container-name)
      terraformUIContainerName: $(ui-terraform-container-name)
      terraformUIEventsContainerName: $(ui-events-terraform-container-name)
      terraformStateKey: $(terraform-key)
      terraformStateAccessKey: $(cpsprodstorageterraform-key1)
      armClientId: $(innovation-prod-spn-client-id)
      armClientSecret: $(innovation-prod-spn-secret)
      armTenantId: $(innovation-prod-spn-tenant-id)
      armSubscriptionId: $(innovation-prod-subscription-id)
      devOpsPatToken: $(devops-pat-token)
      azureSubscription: $(prod-azure-subscription)
      logRetentionTime: $(log-retention-time)
      totalLogRetentionTime: $(total-log-retention-time)
      
  # Env Check: Run e2e Tests Against PROD  
  - template: ../templates/stages/stage_run-e2e-tests.yml
    parameters:
      stageBuildAgent: $(prod-build-agent)
      stageDependsOn: Terraform_PROD
      targetBuild: PolarisTerraformBuild
      targetLabel: "PROD"
      targetName: "e2e Tests"
      buildDefinitionId: 240
      appInsightsKey: "$(innovation-prod-app-insights-instrumentation-key)"
      devOpsPatToken: "$(devops-pat-token)"
