---
trigger: none
pr: none

resources:
  pipelines:
    - pipeline: $(TargetBuild)
      source: Polaris Terraform - Build
      trigger:
        branches:
          include:
            - refs/heads/main
        stages:
          - Publish_Artifacts

variables:
  - group: kv-dev-terraform
  - group: kv-qa-terraform
  - group: kv-prod-terraform
  - group: polaris-global
  - group: polaris-status-check-endpoints
  - group: terraform-containers

stages:
  # Apply terraform to DEV
  - template: ../templates/stages/stage_deploy-terraform.yml
    parameters:
      stageBuildAgent: $(dev-build-agent)
      stageDependsOn:
      envLabel: "Dev"
      targetBuild: $(TargetBuild)
      targetLabel: "DEV"
      targetSuffix: "-dev"
      targetPlanName: "dev"
      appInsightsKey: "$(innovation-development-app-insights-instrumentation-key)"
      terraformStorageAccount: $(dev-terraform-storage-account)
      terraformPipelineContainerName: $(pipeline-terraform-container-name)
      terraformPipelineEventsContainerName: $(pipeline-events-terraform-container-name)
      terraformUIContainerName: $(ui-terraform-container-name)
      terraformUIEventsContainerName: $(ui-events-terraform-container-name)
      terraformNetworkingContainerName: $(networking-terraform-container-name)
      terraformStateKey: $(terraform-key)
      terraformStateAccessKey: $(cpsdevstorageterraform-key1)
      armClientId: $(innovation-development-spn-client-id)
      armClientSecret: $(innovation-development-spn-secret)
      armTenantId: $(innovation-development-spn-tenant-id)
      armSubscriptionId: $(innovation-development-subscription-id)
      devOpsPatToken: $(devops-pat-token)
      azureSubscription: $(dev-azure-subscription)
      logRetentionTime: $(log-retention-time)
      totalLogRetentionTime: $(total-log-retention-time)
      
  - template: ../templates/stages/stage_build-checks.yml
    parameters:
      stageBuildAgent: $(dev-build-agent)
      stageDependsOn: Terraform_DEV
      envLabel: "Dev"
      targetBuild: $(TargetBuild)
      targetSuffix: "-dev"
      targetLabel: "DEV"
      targetName: "Codebase CI Status Checks"
      appInsightsKey: "$(innovation-development-app-insights-instrumentation-key)"
      statusCheckMethod: $(status-check-method)
      statusCheckRetries: $(status-check-retries)
      statusCheckDelaySeconds: $(status-check-delay-seconds)
      statusCheckTimeoutSeconds: $(status-check-timeout-seconds)
      devOpsPatToken: "$(devops-pat-token)"
      armClientId: $(innovation-development-spn-client-id)
      armClientSecret: $(innovation-development-spn-secret)
      armTenantId: $(innovation-development-spn-tenant-id)
      armSubscriptionId: $(innovation-development-subscription-id)
      
  # Apply Terraform to QA
  - template: ../templates/stages/stage_deploy-terraform.yml
    parameters:
      stageBuildAgent: $(qa-build-agent)
      stageDependsOn: Check_DEV
      envLabel: "QA"
      targetBuild: $(TargetBuild)
      targetLabel: "QA"
      targetSuffix: "-qa"
      targetPlanName: "qa"
      appInsightsKey: "$(innovation-qa-app-insights-instrumentation-key)"
      terraformStorageAccount: $(qa-terraform-storage-account)
      terraformPipelineContainerName: $(pipeline-terraform-container-name)
      terraformPipelineEventsContainerName: $(pipeline-events-terraform-container-name)
      terraformUIContainerName: $(ui-terraform-container-name)
      terraformUIEventsContainerName: $(ui-events-terraform-container-name)
      terraformNetworkingContainerName: $(networking-terraform-container-name)
      terraformStateKey: $(terraform-key)
      terraformStateAccessKey: $(cpsqastorageterraform-key1)
      armClientId: $(innovation-qa-spn-client-id)
      armClientSecret: $(innovation-qa-spn-secret)
      armTenantId: $(innovation-qa-spn-tenant-id)
      armSubscriptionId: $(innovation-qa-subscription-id)
      devOpsPatToken: $(devops-pat-token)
      azureSubscription: $(qa-azure-subscription)
      logRetentionTime: $(log-retention-time)
      totalLogRetentionTime: $(total-log-retention-time)
      
  - template: ../templates/stages/stage_build-checks.yml
    parameters:
      stageBuildAgent: $(qa-build-agent)
      stageDependsOn: Terraform_QA
      envLabel: "QA"
      targetBuild: $(TargetBuild)
      targetSuffix: "-qa"
      targetLabel: "QA"
      targetName: "Codebase CI Status Checks"
      appInsightsKey: "$(innovation-qa-app-insights-instrumentation-key)"
      statusCheckMethod: $(status-check-method)
      statusCheckRetries: $(status-check-retries)
      statusCheckDelaySeconds: $(status-check-delay-seconds)
      statusCheckTimeoutSeconds: $(status-check-timeout-seconds)
      devOpsPatToken: "$(devops-pat-token)"
      armClientId: $(innovation-qa-spn-client-id)
      armClientSecret: $(innovation-qa-spn-secret)
      armTenantId: $(innovation-qa-spn-tenant-id)
      armSubscriptionId: $(innovation-qa-subscription-id)

  # Apply Terraform to PROD
  - template: ../templates/stages/stage_deploy-terraform.yml
    parameters:
      stageBuildAgent: $(prod-build-agent)
      stageDependsOn: Check_DEV
      envLabel: "Prod"
      targetBuild: $(TargetBuild)
      targetLabel: "PROD"
      targetSuffix: ""
      targetPlanName: "prod"
      appInsightsKey: "$(innovation-prod-app-insights-instrumentation-key)"
      terraformStorageAccount: $(prod-terraform-storage-account)
      terraformPipelineContainerName: $(pipeline-terraform-container-name)
      terraformPipelineEventsContainerName: $(pipeline-events-terraform-container-name)
      terraformUIContainerName: $(ui-terraform-container-name)
      terraformUIEventsContainerName: $(ui-events-terraform-container-name)
      terraformNetworkingContainerName: $(networking-terraform-container-name)
      terraformStateKey: $(terraform-key)
      terraformStateAccessKey: $(cpsprodstorageterraform-key1)
      armClientId: $(innovation-prod-spn-client-id)
      armClientSecret: $(innovation-prod-spn-secret)
      armTenantId: $(innovation-prod-spn-tenant-id)
      armSubscriptionId: $(innovation-prod-subscription-id)
      devOpsPatToken: $(devops-pat-token)
      azureSubscription: $(prod-azure-subscription)
      logRetentionTime: $(log-retention-time)
      totalLogRetentionTime: $(total-log-retention-time)
      
  - template: ../templates/stages/stage_build-checks.yml
    parameters:
      stageBuildAgent: $(prod-build-agent)
      stageDependsOn: Terraform_PROD
      envLabel: "Prod"
      targetBuild: $(TargetBuild)
      targetSuffix: ""
      targetLabel: "PROD"
      targetName: "Codebase CI Status Checks"
      appInsightsKey: "$(innovation-prod-app-insights-instrumentation-key)"
      statusCheckMethod: $(status-check-method)
      statusCheckRetries: $(status-check-retries)
      statusCheckDelaySeconds: $(status-check-delay-seconds)
      statusCheckTimeoutSeconds: $(status-check-timeout-seconds)
      devOpsPatToken: "$(devops-pat-token)"
      armClientId: $(innovation-prod-spn-client-id)
      armClientSecret: $(innovation-prod-spn-secret)
      armTenantId: $(innovation-prod-spn-tenant-id)
      armSubscriptionId: $(innovation-prod-subscription-id)
