---
name: '$(majorMinorVersion).$(Year:yy)$(DayOfYear).$(semanticVersion)-ci'

trigger: none
pr: none

variables:
  - group: polaris-global
  - name: buildConfiguration
    value: "Release"
  - name: majorMinorVersion
    value: "1.0"
  - name: semanticVersion
    value: "$[counter(variables['majorMinorVersion'], 1)]"
      
pool:
  name: $(uat-build-agent)

stages:
  - stage: Publish_Artifacts
    displayName: Publish Pipeline Scripts
    jobs:
      - job: Build_Pipeline_Scripts
        steps:
          - task: PublishPipelineArtifact@1
            displayName: "Publish pipeline scripts"
            inputs:
              targetPath: "$(Pipeline.Workspace)/s/polaris-devops-pipelines/scripts"
              artifact: "polaris-script-files"
              publishLocation: "pipeline"
  
      - job: Build_Coordinator_Artifact
        steps:
          - task: DotNetCoreCLI@2
            inputs:
              command: publish
              publishWebProjects: false
              projects: "polaris-pipeline/coordinator/coordinator.csproj"
              arguments: "--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory) /p:Version=$(Build.BuildNumber) /p:SourceRevisionId=$(Build.SourceVersion)"
              zipAfterPublish: false
            displayName: "Build Coordinator artifact"

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: "$(Build.ArtifactStagingDirectory)/coordinator"
              artifact: "polaris-coordinator-drop"
            displayName: "Publish Coordinator artifact"
