---
trigger: none
pr: none

resources:
  pipelines:
    - pipeline: PolarisBuild
      source: Polaris Build - DEV
      trigger:
        branches:
          include:
            - refs/heads/main
        stages:
          - Publish_Artifacts

pool:
  name: $(dev-build-agent)

variables:
  - group: kv-dev-terraform
  - group: polaris-global
  - group: polaris-status-check-endpoints
  - group: terraform-containers
  - group: polaris-integration-tests

stages:
  - template: stages/stage_apply-terraform.yml
    parameters:
      targetEnv: "Dev"
      targetBuild: PolarisBuild
      targetLabel: "DEV"
      appInsightsKey: $(innovation-development-app-insights-instrumentation-key)
      azureSubscription: $(dev-azure-subscription)
      targetPlanName: "dev"
      terraformStorageAccount: $(dev-terraform-storage-account)
      mainTerraformContainerName: $(main-terraform-container-name)
      indexTerraformContainerName: $(index-terraform-container-name)
      terraformStateKey: $(terraform-key)
      terraformStateAccessKey: $(cpsdevstorageterraform-key1)
      targetSuffix: "-dev"
      logRetentionTime: $(log-retention-time)
      totalLogRetentionTime: $(total-log-retention-time)

  - template: stages/stage_deploy-codebase.yml
    parameters:
      targetBuild: PolarisBuild
      targetLabel: "DEV"
      appInsightsKey: $(innovation-development-app-insights-instrumentation-key)
      targetSuffix: "-dev"
      azureSubscription: $(dev-azure-subscription)

  # Step temporarily removed until integration user is enabled
  # - template: stages/stage_run-gateway-integration-tests.yml
  #   parameters:
  #     targetBuild: PolarisBuild
  #     targetLabel: "DEV"
  #     appInsightsKey: $(innovation-development-app-insights-instrumentation-key)
  #     stageDependsOn: Deploy
  #     polarisGatewayUri: $(test-polaris-gateway-uri)
  #     cmsProxyUri: $(test-cms-proxy-uri)
  #     cmsUsername: $(test-cms-username)
  #     cmsPassword: $(test-cms-password)
  #     tokenAuthUri: $(test-token-auth-uri)
  #     clientId: $(test-client-id)
  #     grantType: $(test-grant-type)
  #     scope: $(test-scope)
  #     clientSecret: $(test-client-secret)
  #     username: $(test-username)
  #     password: $(test-password)

  - template: stages/stage_swap-slots.yml
    parameters:
      targetBuild: PolarisBuild
      targetLabel: "DEV"
      appInsightsKey: $(innovation-development-app-insights-instrumentation-key)
      targetSuffix: "-dev"
      azureSubscription: $(dev-azure-subscription)
      stageDependsOn: Deploy #Run_Integration_Tests

  - template: stages/stage_check-status.yml
    parameters:
      targetBuild: PolarisBuild
      targetLabel: "DEV"
      appInsightsKey: $(innovation-development-app-insights-instrumentation-key)
      targetSuffix: "-dev"
      azureSubscription: $(dev-azure-subscription)
      statusCheckMethod: $(status-check-method)
      statusCheckRetries: $(status-check-retries)
      statusCheckDelaySeconds: $(status-check-delay-seconds)
      statusCheckTimeoutSeconds: $(status-check-timeout-seconds)

  - template: stages/stage_create-commit-report.yml
    parameters:
      targetBuild: PolarisBuild
      targetLabel: "DEV"
      targetLabelLower: "dev"
      appInsightsKey: $(innovation-development-app-insights-instrumentation-key)

  - template: stages/stage_update-git-hub-tag.yml
    parameters:
      targetBuild: PolarisBuild
      targetLabel: "DEV"
      appInsightsKey: $(innovation-development-app-insights-instrumentation-key)

  # - template: stages/stage_run-e2e-tests.yml
  #   parameters:
  #     targetBuild: PolarisBuild
  #     targetLabel: "DEV"
  #     appInsightsKey: $(innovation-development-app-insights-instrumentation-key)
  #     buildDefinitionId: 588
  #     stageDependsOn: Update_GitHub_Tag

  - template: stages/stage_schedule-releases.yml
    parameters:
      targetBuild: PolarisBuild
      targetLabel: "DEV"
      appInsightsKey: $(innovation-development-app-insights-instrumentation-key)
      environments:
        - name: QA
          targetLabel: 'QA'
          buildDefinitionId: '352'