---
trigger: none
pr: none

resources:
  pipelines:
    - pipeline: PolarisBuild
      source: Polaris Build - QA
      trigger:
        branches:
          include:
            - refs/heads/main
        stages:
          - Publish_Artifacts
            
pool:
  name: $(qa-build-agent)

variables:
  - group: kv-qa-terraform
  - group: polaris-global
  - group: polaris-status-check-endpoints
  - group: terraform-containers

stages:
  - template: stages/stage_apply-terraform.yml
    parameters:
      targetEnv: "QA"
      targetBuild: PolarisBuild
      targetLabel: "QA"
      appInsightsKey: $(innovation-qa-app-insights-instrumentation-key)
      azureSubscription: $(qa-azure-subscription)
      targetPlanName: "qa"
      terraformStorageAccount: $(qa-terraform-storage-account)
      terraformContainerName: $(pipeline-terraform-container-name)
      terraformStateKey: $(terraform-key)
      terraformStateAccessKey: $(cpsqastorageterraform-key1)
      targetSuffix: "-qa"
      logRetentionTime: $(log-retention-time)
      totalLogRetentionTime: $(total-log-retention-time)

  - template: stages/stage_deploy-codebase.yml
    parameters:
      targetBuild: PolarisBuild
      targetLabel: "QA"
      appInsightsKey: $(innovation-qa-app-insights-instrumentation-key)
      targetSuffix: "-qa"
      azureSubscription: $(qa-azure-subscription)

  - template: stages/stage_swap-slots.yml
    parameters:
      targetBuild: PolarisBuild
      targetLabel: "QA"
      appInsightsKey: $(innovation-qa-app-insights-instrumentation-key)
      targetSuffix: "-qa"
      azureSubscription: $(qa-azure-subscription)

  - template: stages/stage_check-status.yml
    parameters:
      targetBuild: PolarisBuild
      targetLabel: "QA"
      appInsightsKey: $(innovation-qa-app-insights-instrumentation-key)
      targetSuffix: "-qa"
      azureSubscription: $(qa-azure-subscription)
      statusCheckMethod: $(status-check-method)
      statusCheckRetries: $(status-check-retries)
      statusCheckDelaySeconds: $(status-check-delay-seconds)
      statusCheckTimeoutSeconds: $(status-check-timeout-seconds)

  - template: stages/stage_create-commit-report.yml
    parameters:
      targetBuild: PolarisBuild
      targetLabel: "QA"
      targetLabelLower: "qa"
      appInsightsKey: $(innovation-qa-app-insights-instrumentation-key)

  - template: stages/stage_update-git-hub-tag.yml
    parameters:
      targetBuild: PolarisBuild
      targetLabel: "QA"
      appInsightsKey: $(innovation-qa-app-insights-instrumentation-key)

  - template: stages/stage_run-e2e-tests.yml
    parameters:
      targetBuild: PolarisBuild
      targetLabel: "QA"
      appInsightsKey: $(innovation-qa-app-insights-instrumentation-key)
      buildDefinitionId: 210
