---
name: '$(majorMinorVersion).$(Year:yy)$(DayOfYear).$(semanticVersion)-ci'

trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - polaris-terraform/main-terraform/*
      - polaris-gateway/*
      - polaris-maintenance/*
      - polaris-pipeline/*
      - polaris-ui/*
      - polaris-e2e/*

pr: none

variables:
  - name: buildConfiguration
    value: "Release"
  - name: majorMinorVersion
    value: "1.0"
  - name: semanticVersion
    value: "$[counter(variables['majorMinorVersion'], 1)]"

pool:
  name: $(build-agent)

stages:
- stage: Setup
  displayName: Setup .NET
  jobs:
  - job: InstallDotNet
    steps:
    - script: |
        sudo apt-get update
        sudo apt-get install -y dotnet-sdk-10.0
      displayName: Install .NET 10 via apt

    - script: 'dotnet --version'
      displayName: 'Check dotnet version'

    - template: stages/stage_publish-all-artifacts.yml
      parameters:
        environment: $(environment)