---
trigger: none
pr: none

resources:
  pipelines:
    - pipeline: PolarisBuild
      source: Polaris Build - UAT
      trigger: true

pool:
  name: $(uat-build-agent)

variables:
  - group: kv-uat-terraform
  - group: polaris-global
  - group: polaris-status-check-endpoints
  - group: terraform-containers

stages:
  - template: stages/stage_apply-terraform.yml
    parameters:
      targetEnv: "UAT"
      targetBuild: PolarisBuild
      targetLabel: "UAT"
      appInsightsKey: $(innovation-uat-app-insights-instrumentation-key)
      azureSubscription: $(uat-azure-subscription)
      targetPlanName: "uat"
      terraformStorageAccount: $(uat-terraform-storage-account)
      pipelineTerraformContainerName: $(pipeline-terraform-container-name)
      uiTerraformContainerName: $(ui-terraform-container-name)
      terraformStateKey: $(terraform-key)
      terraformStateAccessKey: $(cpsuatstorageterraform-key1)
      targetSuffix: "-uat"
      logRetentionTime: $(log-retention-time)
      totalLogRetentionTime: $(total-log-retention-time)

  - template: stages/stage_deploy-codebase.yml
    parameters:
      targetBuild: PolarisBuild
      targetLabel: "UAT"
      appInsightsKey: $(innovation-uat-app-insights-instrumentation-key)
      targetSuffix: "-uat"
      azureSubscription: $(uat-azure-subscription)

  - template: stages/stage_swap-slots.yml
    parameters:
      targetBuild: PolarisBuild
      targetLabel: "UAT"
      appInsightsKey: $(innovation-uat-app-insights-instrumentation-key)
      targetSuffix: "-uat"
      azureSubscription: $(uat-azure-subscription)

  - template: stages/stage_check-status.yml
    parameters:
      targetBuild: PolarisBuild
      targetLabel: "UAT"
      appInsightsKey: $(innovation-uat-app-insights-instrumentation-key)
      targetSuffix: "-uat"
      azureSubscription: $(uat-azure-subscription)
      statusCheckMethod: $(status-check-method)
      statusCheckRetries: $(status-check-retries)
      statusCheckDelaySeconds: $(status-check-delay-seconds)
      statusCheckTimeoutSeconds: $(status-check-timeout-seconds)

  - template: stages/stage_run-e2e-tests.yml
    parameters:
      targetBuild: PolarisBuild
      targetLabel: "UAT"
      appInsightsKey: $(innovation-uat-app-insights-instrumentation-key)
      buildDefinitionId: 421
      stageDependsOn: Check_Status
