---
trigger: none
pr: none

schedules:
  - cron: "0 0 * * 0"  # Weekly at Sunday night - ensure the build agent image is up-to-date
    displayName: Weekly Sunday night build-agent refresh
    branches:
      include:
        - main
    always: true

variables:
  - group: polaris-build-agent
  - group: polaris-global
    
pool:
  vmImage: ubuntu-latest
  
stages:
  - stage: create_version
    displayName: Determine version number
    jobs:
      - job: determine_version
        displayName: Determine version
        steps:
          - template: steps/git-version.yml

  - stage: image_builder_uat
    displayName: UAT - Build VM Image
    dependsOn: create_version
    pool:
      name: $(uat-build-agent)
    variables:
      versionSha: $[format('{0}{1}',stageDependencies.create_version.determine_version.outputs['versioning.versionShortSha'], variables['Build.BuildId']) ]
    jobs:
      - job: build
        displayName: UAT - Build Image
        steps:
          - template: steps/get-credentials.yml
            parameters:
              azureSubscriptionId: $(uat-azure-subscription)

          - template: steps/create-build-agent-image.yml
            parameters:
              clientId: $(clientId)
              clientSecret: $(clientSecret)
              tenantId: $(tenantId)
              subscriptionId: $(subscriptionId)
              subscriptionName: $(uat-azure-subscription)
              resourceGroup: $(innovation-uat-build-agent-resource-group)
              storageAccount: $(innovation-uat-build-agent-storage-account)
              versionSha: $(versionSha)
              baseImage: "Canonical:0001-com-ubuntu-server-mantic:23_10:linux"
              additionalBuilderParams: '{"vm_size":"Standard_D2_v3","virtual_network_resource_group_name":"rg-networking","virtual_network_name":"vnet-innovation-uat","virtual_network_subnet_name":"polaris-scale-set-subnet"}'

  - stage: update_scale_set_uat
    displayName: Update UAT Resources
    dependsOn:
      - create_version
      - image_builder_uat
    variables:
      versionSha: $[format('{0}{1}',stageDependencies.create_version.determine_version.outputs['versioning.versionShortSha'], variables['Build.BuildId']) ]
    jobs:
      - job: update
        displayName: Update UAT
        steps:
          - template: steps/get-credentials.yml
            parameters:
              azureSubscriptionId: $(uat-azure-subscription)

          - template: steps/update-image-version.yml
            parameters:
              clientId: $(clientId)
              clientSecret: $(clientSecret)
              tenantId: $(tenantId)
              subscriptionId: $(subscriptionId)
              resourceGroup: $(innovation-uat-build-agent-resource-group)
              agentPoolName: $(innovation-uat-agent-pool-name)
              versionSha: $(versionSha)
