trigger:
  branches:
    include:
    - main
    - qa
    - release

  paths:
    include:
      - "polaris-terraform/pipeline-events-terraform/*"

steps:
  - task: PublishPipelineArtifact@1
    displayName: "Publish Terraform Artifacts"
    inputs:
      targetPath: "$(Pipeline.Workspace)/s/polaris-terraform/pipeline-events-terraform/"
      artifact: "pipeline-events-terraform-files"
      publishLocation: "pipeline"
