---
parameters:
  - name: checkoutRef

jobs:
  - job: Prepare_DotNet_Tests
    displayName: Prepare DotNet Tests
    pool:
      vmImage: 'windows-latest'
    steps:
      - checkout: ${{ parameters.checkoutRef }}
        clean: true
        persistCredentials: true
        fetchDepth: 1
        displayName: "Checkout polaris-e2e"

      - task: DownloadSecureFile@1
        name: licence
        inputs:
          secureFile: "Aspose.Total.NET.lic"
        displayName: "Download Aspose Licence"

      - task: DotNetCoreCLI@2
        inputs:
          command: "build"
          projects: "polaris-pipeline/pdf-redactor.integration.tests/pdf-redactor.integration.tests.csproj"
          arguments: "--configuration Release"
        displayName: "Build PDF Redactor Integration Tests"

      - task: FileTransform@2
        displayName: "Transform Integration Test Settings"
        inputs:
          folderPath: "$(System.DefaultWorkingDirectory)/polaris-pipeline/pdf-redactor.integration.tests/bin/Release/net8.0"
          jsonTargetFiles: "appSettings.json"
          xmlTransformationRules: "" # disabled, prevents non-windows-platform error

      - task: CopyFiles@2
        inputs:
          sourceFolder: $(Agent.TempDirectory)
          contents: Aspose.Total.NET.lic
          targetFolder: "$(System.DefaultWorkingDirectory)/polaris-pipeline/pdf-redactor.integration.tests/bin/Release/net8.0"
        displayName: "Copy Aspose.Total.NET.lic"

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: "$(System.DefaultWorkingDirectory)/polaris-pipeline/pdf-redactor.integration.tests/bin/Release/net8.0"
          artifact: "pdf-redactor-tests-drop"
        displayName: "Publish PDF Redactor tests artifact"
