---
parameters:
  - name: checkoutRef
  - name: cypressEnvironment
  
jobs:
  - job: Run_Cypress_Tests_B
    displayName: Run Cypress Tests B
    steps:
      - checkout: ${{ parameters.checkoutRef }}
        clean: true
        persistCredentials: true
        fetchDepth: 1
        displayName: "Checkout polaris-e2e"

      - task: Bash@3
        inputs:
          targetType: "inline"
          script: "env | sort"

      - task: Npm@1
        inputs:
          command: "ci"
          workingDir: "polaris-e2e"
        displayName: "npm ci"
        
      #before running the tests replace the clientId placeholder in env-specific config file
      - bash: |
          sed -i -e  "s/--spa-client-id--/$SPA_CLIENT_ID/g" "env.$CURRENT_ENV.json"
        displayName: 'Substitute Client Id'
        workingDirectory: "polaris-e2e/config"
        env:
          SPA_CLIENT_ID: $(polaris-spa-client-id)
          CURRENT_ENV: ${{ parameters.cypressEnvironment }}

      - task: CmdLine@2
        env:
          CYPRESS_CLIENTSECRET: $(polaris-spa-client-secret)
          CYPRESS_AD_USERNAME: $(cypress-ad-username)
          CYPRESS_AD_PASSWORD: $(cypress-ad-password)
          CYPRESS_ENVIRONMENT: ${{ parameters.cypressEnvironment }}
          CYPRESS_PRE_SEARCH_DELAY_MS: $(cypress-pre-search-delay-ms)
          CYPRESS_grepTags: $(cypress-grep-tags-b)
        condition: succeeded()
        inputs:
          workingDirectory: "polaris-e2e"
          script: "npm run cy:ci"
        displayName: "cypress run tests"

#     Commenting out this step as videos have been disabled to improve E2E performance under PR#1606
#      - task: PublishBuildArtifacts@1
#        condition: always() # this step will always run, helpful to diagnose failing cypress tests
#        inputs:
#          PathtoPublish: "polaris-e2e/cypress/videos"
#          ArtifactName: "Cypress failure vidoes"
#          publishLocation: "Container"

      - task: PublishBuildArtifacts@1
        condition: always() # this step will always run, helpful to diagnose failing cypress tests
        inputs:
          PathtoPublish: "polaris-e2e/cypress/screenshots"
          ArtifactName: "Cypress failure screenshots"
          publishLocation: "Container"
