parameters:
  buildAgent: ""
  buildLabel: ""
  appInsightsKey: ""
  devOpsEnv: ""
  envLabel: ""
  envSuffix: ""
  azureSubscription: ""
  devOpsPatToken: ""
  
jobs:
- deployment: DeployUIComponents
  environment: ${{ parameters.devOpsEnv }}
  pool:
    name: ${{ parameters.buildAgent }}
  strategy:
    runOnce:
      deploy:
        steps:
        #download scripts artifact
        - download: ${{ parameters.buildLabel }}
          displayName: Download Scripts
          artifact: 'polaris-script-files'
          
          #send custom event to AppInsights
        - template: steps/tasks/send-to-app-insights.yml
          parameters:
            appInsightsKey: "${{ parameters.appInsightsKey }}"
            message: "${{ parameters.envLabel }} UI Component Deployment: Started"
          
        - template: steps/deploy-spa.yml
          parameters:
            appInsightsKey: "${{ parameters.appInsightsKey }}"
            envLabel: "${{ parameters.envLabel }}"
            buildLabel: "${{ parameters.buildLabel }}"
            envSuffix: "${{ parameters.envSuffix }}"
            azureSubscription: "${{ parameters.azureSubscription }}"
          
        - template: steps/deploy-gateway.yml
          parameters:
            appInsightsKey: "${{ parameters.appInsightsKey }}"
            envLabel: "${{ parameters.envLabel }}"
            buildLabel: "${{ parameters.buildLabel }}"
            envSuffix: "${{ parameters.envSuffix }}"
            azureSubscription: "${{ parameters.azureSubscription }}" 
          
        - template: steps/deploy-auth-handover.yml
          parameters:
            appInsightsKey: "${{ parameters.appInsightsKey }}"
            envLabel: "${{ parameters.envLabel }}"
            buildLabel: "${{ parameters.buildLabel }}"
            envSuffix: "${{ parameters.envSuffix }}"
            azureSubscription: "${{ parameters.azureSubscription }}"
            
        - template: steps/restart-spa.yml
          parameters:
            appInsightsKey: "${{ parameters.appInsightsKey }}"
            envLabel: "${{ parameters.envLabel }}"
            envSuffix: "${{ parameters.envSuffix }}"
            azureSubscription: "${{ parameters.azureSubscription }}" 
          
          #send custom event to AppInsights
        - template: steps/tasks/send-to-app-insights.yml
          parameters:
            appInsightsKey: "${{ parameters.appInsightsKey }}"
            message: "${{ parameters.envLabel }} UI Component Deployment: Completed"

          #send any failures to AppInsights  
        - template: steps/tasks/send-failure-to-app-insights.yml
          parameters:
            appInsightsKey: "${{ parameters.appInsightsKey }}"
            devOpsPatToken: "${{ parameters.devOpsPatToken }}"
            message: "${{ parameters.envLabel }} UI Component Deployment: Failed"