---
parameters:
  - name: targetLabel
    type: string
  - name: jobDependsOn
    type: object

jobs:
  - job: UpdateGithubTag
    dependsOn: ${{ parameters.jobDependsOn }}
    steps:
      - checkout: self
        persistCredentials: true
      - task: PowerShell@2
        displayName: 'Update Tag for: ${{ parameters.targetLabel }}'
        inputs:
          targetType: 'inline'
          script: |
            $targetLabel = "${{ parameters.targetLabel }}"
            $lowercaseTargetLabel = $targetLabel.ToLower()
            git config user.name "$BUILD_REQUESTEDFOR"
            git config user.email "$BUILD_REQUESTEDFOREMAIL"
            
            git push origin :refs/tags/$lowercaseTargetLabel
            git tag -f $lowercaseTargetLabel
            git push origin $lowercaseTargetLabel
