---
parameters:
  - name: envLabel
    type: string
  - name: targetBuild
    type: string
  - name: targetLabel
    type: string
  - name: targetName
    type: string
  - name: targetSuffix
    type: string
  - name: appInsightsKey
    type: string
  - name: armClientId
    type: string
  - name: armClientSecret
    type: string
  - name: armTenantId
    type: string
  - name: armSubscriptionId
    type: string
  - name: jobDependsOn
    type: object

jobs:
  - deployment: UpdateUIComponentAppKeys
    dependsOn: ${{ parameters.jobDependsOn }}
    environment: ${{ parameters.envLabel }}
    strategy:
      runOnce:
        deploy:
          steps:
            # download scripts artifact
            - download: ${{ parameters.targetBuild }}
              displayName: Download Scripts
              artifact: 'polaris-script-files'

            # send custom event to AppInsights
            - template: steps/tasks/task_send-to-app-insights.yml
              parameters:
                appInsightsKey: ${{ parameters.appInsightsKey }}
                targetBuild: ${{ parameters.targetBuild }}
                message: "${{ parameters.targetLabel }} ${{ parameters.targetName }}: Update Coordinator App Keys in Gateway - Started"

            # Set Durable Extension Code app settings
            - bash: |
                az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID
                az account set --subscription $ARM_SUBSCRIPTION_ID
                coordinator_default_code=$(az functionapp keys list --resource-group rg-polaris-pipeline$ARM_SUFFIX --name fa-polaris-pipeline$ARM_SUFFIX-coordinator --query 'functionKeys.default' --output tsv)
                coordinator_durable_code=$(az functionapp keys list --resource-group rg-polaris-pipeline$ARM_SUFFIX --name fa-polaris-pipeline$ARM_SUFFIX-coordinator --query 'systemKeys.durabletask_extension' --output tsv)
                ddei_default_code=$(az functionapp keys list --resource-group rg-polaris-ddei$ARM_SUFFIX --name fa-polaris-ddei$ARM_SUFFIX --query 'functionKeys.default' --output tsv)
                az functionapp config appsettings set --name fa-polaris$ARM_SUFFIX-gateway --resource-group rg-polaris$ARM_SUFFIX --settings "PolarisPipelineCoordinatorFunctionAppKey=$coordinator_default_code"
                az functionapp config appsettings set --name fa-polaris$ARM_SUFFIX-gateway --resource-group rg-polaris$ARM_SUFFIX --settings "PolarisPipelineCoordinatorDurableExtensionCode=$coordinator_durable_code"
                az functionapp config appsettings set --name fa-polaris$ARM_SUFFIX-gateway --resource-group rg-polaris$ARM_SUFFIX --settings "DdeiAccessKey=$ddei_default_code"
                az webapp config appsettings set --name polaris$ARM_SUFFIX-cmsproxy --resource-group rg-polaris$ARM_SUFFIX --settings "DDEI_ENDPOINT_FUNCTION_APP_KEY=$ddei_default_code"
                az functionapp config appsettings set --name fa-polaris$ARM_SUFFIX-auth-handover --resource-group rg-polaris$ARM_SUFFIX --settings "DdeiAccessKey=$ddei_default_code"
              displayName: Script > Update Coordinator Keys In Gateway Config
              env:
                ARM_CLIENT_ID: ${{ parameters.armClientId }}
                ARM_CLIENT_SECRET: ${{ parameters.armClientSecret }}
                ARM_TENANT_ID: ${{ parameters.armTenantId }}
                ARM_SUBSCRIPTION_ID: ${{ parameters.armSubscriptionId }}
                ARM_SUFFIX: ${{ parameters.targetSuffix }}

            # send custom event to AppInsights
            - template: steps/tasks/task_send-to-app-insights.yml
              parameters:
                appInsightsKey: ${{ parameters.appInsightsKey }}
                targetBuild: ${{ parameters.targetBuild }}
                message: "${{ parameters.targetLabel }} ${{ parameters.targetName }}: Update Coordinator App Keys in Gateway - Completed"
