---
parameters:
  - name: targetLabel
    type: string
  - name: jobDependsOn
    type: object
  - name: message
    type: string
  - name: webhookUrl
    type: string
    
jobs:
  - job: SendMessageToTeams
    dependsOn: ${{ parameters.jobDependsOn }}
    steps:
      - bash: |
          curl -v -X POST ${{ parameters.webhookUrl }} -H 'Content-Type: application/json; charset=utf-8' \
            --data-binary @- << EOF
            {
              "type": "message",
              "attachments": [
                {
                  "contentType": "application/vnd.microsoft.card.adaptive",
                  "contentUrl": null,
                  "content": {
                    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                    "type": "AdaptiveCard",
                    "version": "1.2",
                    "body": [
                      {
                        "type": "TextBlock",
                        "size": "Medium",
                        "weight": "Bolder",
                        "text": "Polaris Release Report"
                      },
                      {
                        "type": "ColumnSet",
                        "columns": [
                          {
                            "type": "Column",
                            "items": [
                              {
                                "type": "TextBlock",
                                "weight": "Bolder",
                                "text": "Mark Jones",
                                "wrap": true
                              },
                              {
                                "type": "TextBlock",
                                "spacing": "None",
                                "text": "Released {{DATE(2017-02-14T06:08:39Z, SHORT)}}",
                                "isSubtle": true,
                                "wrap": true
                              },
                              {
                                "type": "TextBlock",
                                "weight": "Bolder",
                                "text": "Included Commits:",
                                "wrap": true
                              },
                              {
                                "type": "FactSet",
                                "facts": [
                                  {
                                    "title": "Fact 1",
                                    "value": "Value 1"
                                  },
                                  {
                                    "title": "Fact 2",
                                    "value": "Value 2"
                                  }
                                ]
                              }
                            ],
                            "width": "stretch"
                          }
                        ]
                      },
                      {
                        "type": "TextBlock",
                        "text": "✔ Pipeline was run successfully! [Results]($(System.TeamFoundationCollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId))",
                        "wrap": true
                      },
                      {
                        "type": "TextBlock",
                        "text": "❗ Pipeline failed!",
                        "wrap": true
                      }
                    ]
                  }
                }
              ]
            }
          EOF
        displayName: Send message to Teams
