---
parameters:
  - name: targetSuffix
    type: string
  - name: azureSubscription
    type: string
  - name: jobDependsOn
    type: object
  
jobs:
  - job: Swap_Pipeline_Slots
    dependsOn: ${{ parameters.jobDependsOn }}
    strategy:
      matrix:
        Coordinator:
          Name: "Coordinator"
          AppServiceName: "fa-polaris${{ parameters.targetSuffix }}-coordinator"
        PDFGenerator:
          Name: "PDF Generator"
          AppServiceName: "fa-polaris${{ parameters.targetSuffix }}-pdf-generator"
        TextExtractor:
          Name: "Text Extractor"
          AppServiceName: "fa-polaris${{ parameters.targetSuffix }}-text-extractor"
    displayName: Swap
    steps:
      - checkout: none
      - task: AzureAppServiceManage@0
        displayName: Swap slot
        inputs:
          action: "Swap Slots"
          sourceSlot: "staging1"
          azureSubscription: ${{ parameters.azureSubscription }}
          resourceGroupName: "rg-polaris-pipeline${{ parameters.targetSuffix }}"
          webAppName: $(AppServiceName)
          PreserveVnet: true
          
  - job: Swap_UI_Slots
    dependsOn: ${{ parameters.jobDependsOn }}
    strategy:
      matrix:
        SPA:
          Name: "SPA"
          AppServiceName: "as-web-polaris${{ parameters.targetSuffix }}"
        PolarisGateway:
          Name: "Polaris Gateway"
          AppServiceName: "fa-polaris${{ parameters.targetSuffix }}-gateway"
    displayName: Swap
    steps:
      - checkout: none
      - task: AzureAppServiceManage@0
        displayName: Swap slot
        inputs:
          action: "Swap Slots"
          sourceSlot: "staging1"
          azureSubscription: ${{ parameters.azureSubscription }}
          resourceGroupName: "rg-polaris${{ parameters.targetSuffix }}"
          webAppName: $(AppServiceName)
          PreserveVnet: true
