parameters:
  - name: envLabel
    type: string
  - name: targetBuild
    type: string
  - name: targetLabel
    type: string
  - name: targetName
    type: string
  - name: appInsightsKey
    type: string
  - name: devOpsPatToken
    type: string
  - name: dependsOn
    type: object
    
jobs:
  - deployment: LogResult
    dependsOn: ${{ parameters.dependsOn }}
    environment: ${{ parameters.envLabel }}
    strategy:
      runOnce:
        deploy:
          steps:
            #download scripts artifact
            - download: ${{ parameters.targetBuild }}
              displayName: Download Scripts
              artifact: 'polaris-script-files'

            #send custom event to AppInsights
            - template: steps/tasks/send-to-app-insights.yml
              parameters:
                appInsightsKey: ${{ parameters.appInsightsKey }}
                message: "${{ parameters.targetLabel }} ${{ parameters.targetName }}: Completed"
                
            - template: steps/tasks/send-failure-to-app-insights.yml
              parameters:
                appInsightsKey: ${{ parameters.appInsightsKey }}
                devOpsPatToken: ${{ parameters.devOpsPatToken }}
                message: "${{ parameters.targetLabel }} ${{ parameters.targetName }}: Failed"