parameters:
  stageName: ""
  displayName: ""
  buildAgent: ""
  buildLabel: ""
  appInsightsKey: ""
  dependsOn1: ""
  dependsOn2: ""
  dependsOn3: ""
  envLabel: ""
  buildDefinitionId: ""
  devOpsPatToken: ""
  
stages:
  - stage: ${{ parameters.stageName }}
    displayName: ${{ parameters.displayName }}
    dependsOn:
      - ${{ parameters.dependsOn1 }}
      - ${{ parameters.dependsOn2 }}
      - ${{ parameters.dependsOn3 }}
    condition: succeeded()
    jobs:
      - job: Run_e2e_Tests
        pool:
          name: $(dev-build-agent)
        steps:
          #download scripts artifact
          - download: PolarisCodebaseBuild
            displayName: Download Scripts
            artifact: 'polaris-script-files'
            
          #send custom event to AppInsights
          - template: jobs/steps/tasks/send-to-app-insights.yml
            parameters:
              appInsightsKey: "${{ parameters.appInsightsKey }}"
              message: "${{ parameters.envLabel }} Run e2e Tests: Started"

          - task: benjhuser.tfs-extensions-build-tasks.trigger-build-task.TriggerBuild@4
            displayName: 'Run the e2e tests: ${{ parameters.envLabel }}'
            inputs:
              buildDefinition: ${{ parameters.buildDefinitionId }}
              waitForQueuedBuildsToFinish: true
              cancelBuildsIfAnyFails: true
              password: ${{ parameters.devOpsToken }}

          #send custom event to AppInsights
          - template: jobs/steps/tasks/send-to-app-insights.yml
            parameters:
              appInsightsKey: "${{ parameters.appInsightsKey }}"
              message: "${{ parameters.envLabel }} Run e2e Tests: Completed"

            #send any failures to AppInsights  
          - template: jobs/steps/tasks/send-failure-to-app-insights.yml
            parameters:
              appInsightsKey: "${{ parameters.appInsightsKey }}"
              devOpsPatToken: "${{ parameters.devOpsPatToken }}"
              message: "${{ parameters.envLabel }} Run e2e Tests: Failed"