---
parameters:
  - name: targetBuild
    type: string
  - name: targetLabel
    type: string
  - name: targetName
    type: string
  - name: targetSuffix
    type: string
  - name: appInsightsKey
    type: string
  - name: armClientId
    type: string
  - name: armClientSecret
    type: string
  - name: armTenantId
    type: string
  - name: armSubscriptionId
    type: string
  
steps:
  # download scripts artifact
  - download: ${{ parameters.targetBuild }}
    displayName: Download Scripts
    artifact: 'polaris-script-files'

  # send custom event to AppInsights
  - template: task_send-to-app-insights.yml
    parameters:
      appInsightsKey: ${{ parameters.appInsightsKey }}
      targetBuild: ${{ parameters.targetBuild }}
      message: "${{ parameters.targetLabel }} ${{ parameters.targetName }}: Update Durable Extension Code - Started"

  # Set Durable Extension Code app setting, post Coordinator creation, in Coordinator app settings, including the deployment slot
  - bash: |
      az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID
      az account set --subscription $ARM_SUBSCRIPTION_ID
      durable_code=$(az functionapp keys list --resource-group rg-polaris-pipeline$ARM_SUFFIX --name fa-polaris$ARM_SUFFIX-coordinator --query 'systemKeys.durabletask_extension' --output tsv)
      az functionapp config appsettings set --name fa-polaris$ARM_SUFFIX-coordinator --resource-group rg-polaris-pipeline$ARM_SUFFIX --settings "PolarisPipelineCoordinatorDurableExtensionCode=$durable_code"
      az functionapp config appsettings set --name fa-polaris$ARM_SUFFIX-coordinator --resource-group rg-polaris-pipeline$ARM_SUFFIX --slot "staging1" --settings "PolarisPipelineCoordinatorDurableExtensionCode=$durable_code"
    displayName: Script > Update Keys in Pipeline Component Config
    env:
      ARM_CLIENT_ID: ${{ parameters.armClientId }}
      ARM_CLIENT_SECRET: ${{ parameters.armClientSecret }}
      ARM_TENANT_ID: ${{ parameters.armTenantId }}
      ARM_SUBSCRIPTION_ID: ${{ parameters.armSubscriptionId }}
      ARM_SUFFIX: ${{ parameters.targetSuffix }}

  # send custom event to AppInsights
  - template: task_send-to-app-insights.yml
    parameters:
      appInsightsKey: ${{ parameters.appInsightsKey }}
      targetBuild: ${{ parameters.targetBuild }}
      message: "${{ parameters.targetLabel }} ${{ parameters.targetName }}: Update Durable Extension Code - Completed"