---
parameters:
  - name: targetBuild
    type: string
  - name: targetLabel
    type: string
  - name: resourceGroupName
    type: string
  - name: appName
    type: string
  - name: azureSubscription
    type: string
  
steps:
  #download scripts artifact
  - download: ${{ parameters.targetBuild }}
    displayName: Download Scripts
    artifact: 'polaris-script-files'

  #- task: Powershell@2
  #  displayName: Setting up Az Powershell Module
  #  inputs:
  #    failOnStderr: true
  #    targetType: 'filePath'
  #    filePath: $(Pipeline.Workspace)/${{ parameters.targetBuild }}/polaris-script-files/InstallAzModules.ps1
    
  #sync slot app settings
  - task:  AzurePowerShell@5
    displayName: 'Sync ${{ parameters.targetLabel }} slot settings'
    inputs:
      azureSubscription: ${{ parameters.azureSubscription }}
      FailOnStandardError: true
      ScriptType: 'filePath'
      ScriptPath: $(Pipeline.Workspace)/${{ parameters.targetBuild }}/polaris-script-files/SyncAppSettings.ps1
      azurePowerShellVersion: "LatestVersion"
      ScriptArguments: > # Use this to avoid newline characters in multi-line string
        -ResourceGroupName ${{ parameters.resourceGroupName }}
        -AppName ${{ parameters.appName }}
