---
parameters:
  - name: azureSubscriptionId
    type: string
    
steps:
  - task: AzureCLI@2
    displayName: Fetch Azure Credentials
    name: credentials
    inputs:
      azureSubscription: ${{ parameters.azureSubscriptionId }}
      scriptType: bash
      addSpnToEnvironment: true # this will add the required credentials to env vars
      useGlobalConfig: true
      scriptLocation: inlineScript
      inlineScript: |
        echo "##vso[task.setvariable variable=TENANT_ID;isOutput=true]$tenantId"
        echo "##vso[task.setvariable variable=CLIENT_ID;isOutput=true]$servicePrincipalId"
        echo "##vso[task.setvariable variable=CLIENT_SECRET;isOutput=true]$servicePrincipalKey"
        echo "##vso[task.setvariable variable=SUBSCRIPTION_ID;isOutput=true]$(az account show --query="id" -o tsv)"