---
parameters:
  - name: targetLabel
    type: string
  - name: targetLabelLower
    type: string

steps:
  - checkout: self
    persistCredentials: true

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        $targetLabel = "${{ parameters.targetLabel }}"
        $lowercaseTargetLabel = $targetLabel.ToLower()
        $diffTag = "$lowercaseTargetLabel...HEAD"
        $reportName = "commit-report-$lowercaseTargetLabel.csv"
        git log "$diffTag" --oneline --pretty=format:%h,%an,%ae,%s > "$reportName"
    displayName: Generate commit report for ${{ parameters.targetLabel }}

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: "$(Build.Repository.LocalPath)/commit-report-${{ parameters.targetLabelLower }}.csv"
      artifact: "Commit Report - ${{ parameters.targetLabel }} ($(System.JobAttempt))"
    displayName: "Publish Commit report for ${{ parameters.targetLabel }}"
