---
trigger: none
pr: none

resources:
  pipelines:
    - pipeline: PolarisCodebaseBuild
      source: Polaris Codebase - Build
      trigger:
        branches:
          include:
            - refs/heads/main
        stages:
          - Publish_Artifacts

variables:
  - group: kv-dev-terraform
  - group: kv-qa-terraform
  - group: kv-prod-terraform
  - group: polaris-global
  - group: polaris-status-check-endpoints

stages:
  - template: ../templates/stages/stage_deploy-codebase.yml
    parameters:
      stageBuildAgent: $(dev-build-agent)
      stageDependsOn:
      envLabel: "Dev"
      targetBuild: PolarisCodebaseBuild
      targetLabel: "DEV"
      targetName: "Codebase CI Deployment"
      targetSuffix: "-dev"
      appInsightsKey: "$(innovation-development-app-insights-instrumentation-key)"
      azureSubscription: $(dev-azure-subscription)
      devOpsPatToken: "$(devops-pat-token)"
      logResultDependsOn:
        - LogStart
        - DeployCoordinator
        - DeployPdfGenerator
        - DeployTextGenerator
        - DeploySpa
        - DeployGateway
        - DeployAuthHandover

  - template: ../templates/stages/stage_status-checks.yml
    parameters:
      stageBuildAgent: $(dev-build-agent)
      stageDependsOn: Deploy_DEV
      envLabel: "Dev"
      targetBuild: PolarisCodebaseBuild
      targetLabel: "DEV"
      targetName: "Codebase CI Status Checks"
      appInsightsKey: "$(innovation-development-app-insights-instrumentation-key)"
      statusCheckMethod: $(status-check-method)
      statusCheckRetries: $(status-check-retries)
      statusCheckDelaySeconds: $(status-check-delay-seconds)
      statusCheckTimeoutSeconds: $(status-check-timeout-seconds)
      devOpsPatToken: "$(devops-pat-token)"
      logResultDependsOn:
        - LogStart
        - CheckCoordinator
        - CheckPDFGenerator
        - CheckTextExtractor
        - CheckAuthHandover
        - CheckGateway
        - CheckProxy
        - CheckSPA

  - template: ../templates/stages/stage_run-e2e-tests.yml
    parameters:
      stageBuildAgent: $(dev-build-agent)
      targetBuild: PolarisCodebaseBuild
      targetLabel: "DEV"
      buildDefinitionId: 129
      appInsightsKey: "$(innovation-development-app-insights-instrumentation-key)"
      devOpsPatToken: "$(devops-pat-token)"

  - template: ../templates/stages/stage_deploy-codebase.yml
    parameters:
      stageBuildAgent: $(qa-build-agent)
      stageDependsOn: Run_e2e_Tests_DEV
      envLabel: "QA"
      targetBuild: PolarisCodebaseBuild
      targetLabel: "QA"
      targetName: "Codebase CI Deployment"
      targetSuffix: "-qa"
      appInsightsKey: "$(innovation-qa-app-insights-instrumentation-key)"
      azureSubscription: $(qa-azure-subscription)
      devOpsPatToken: "$(devops-pat-token)"

  - template: ../templates/stages/stage_status-checks.yml
    parameters:
      stageBuildAgent: $(qa-build-agent)
      stageDependsOn: Deploy_QA
      envLabel: "QA"
      targetBuild: PolarisCodebaseBuild
      targetLabel: "QA"
      targetName: "Codebase CI Status Checks"
      appInsightsKey: "$(innovation-qa-app-insights-instrumentation-key)"
      statusCheckMethod: $(status-check-method)
      statusCheckRetries: $(status-check-retries)
      statusCheckDelaySeconds: $(status-check-delay-seconds)
      statusCheckTimeoutSeconds: $(status-check-timeout-seconds)
      devOpsPatToken: "$(devops-pat-token)"
      logResultDependsOn:
        - LogStart
        - CheckCoordinator
        - CheckPDFGenerator
        - CheckTextExtractor
        - CheckAuthHandover
        - CheckGateway
        - CheckProxy
        - CheckSPA

  - template: ../templates/stages/stage_run-e2e-tests.yml
    parameters:
      stageBuildAgent: $(qa-build-agent)
      targetBuild: PolarisCodebaseBuild
      targetLabel: "QA"
      buildDefinitionId: 210
      appInsightsKey: "$(innovation-qa-app-insights-instrumentation-key)"
      devOpsPatToken: "$(devops-pat-token)"

  - template: ../templates/stages/stage_deploy-codebase.yml
    parameters:
      stageBuildAgent: $(prod-build-agent)
      stageDependsOn: Run_e2e_Tests_DEV
      envLabel: "Prod"
      targetBuild: PolarisCodebaseBuild
      targetLabel: "PROD"
      targetName: "Codebase CI Deployment"
      targetSuffix: ""
      appInsightsKey: "$(innovation-prod-app-insights-instrumentation-key)"
      azureSubscription: $(prod-azure-subscription)
      devOpsPatToken: "$(devops-pat-token)"

  - template: ../templates/stages/stage_status-checks.yml
    parameters:
      stageBuildAgent: $(prod-build-agent)
      stageDependsOn: Deploy_PROD
      envLabel: "Prod"
      targetBuild: PolarisCodebaseBuild
      targetLabel: "PROD"
      targetName: "Codebase CI Status Checks"
      appInsightsKey: "$(innovation-prod-app-insights-instrumentation-key)"
      spaStatusUrl: $(prod-ui-status-url)
      statusCheckMethod: $(status-check-method)
      statusCheckRetries: $(status-check-retries)
      statusCheckDelaySeconds: $(status-check-delay-seconds)
      statusCheckTimeoutSeconds: $(status-check-timeout-seconds)
      devOpsPatToken: "$(devops-pat-token)"

  - template: ../templates/stages/stage_run-e2e-tests.yml
    parameters:
      stageBuildAgent: $(prod-build-agent)
      targetBuild: PolarisCodebaseBuild
      targetLabel: "PROD"
      buildDefinitionId: 240
      appInsightsKey: "$(innovation-prod-app-insights-instrumentation-key)"
      devOpsPatToken: "$(devops-pat-token)"
