trigger: none
pr: none

resources:
  pipelines:
    - pipeline: PolarisCodebaseBuild
      source: Polaris Codebase - Build
      trigger:
        branches:
          include:
            - refs/heads/main
        stages:
          - Publish_Artifacts

variables:
  - group: kv-dev-terraform
  - group: kv-qa-terraform
  - group: kv-prod-terraform
  - group: polaris-global
  - group: polaris-status-check-endpoints

stages:
  - template: ../templates/stages/deploy-codebase.yml
    parameters:
      stageBuildAgent: $(dev-build-agent)
      stageDependsOn:
      envLabel: "Dev"
      targetLabel: "DEV"
      targetName: "Codebase CI Deployment"
      targetSuffix: "-dev"
      appInsightsKey: "$(innovation-development-app-insights-instrumentation-key)"
      azureSubscription: $(dev-azure-subscription)
      devOpsPatToken: "$(devops-pat-token)"
      logResultDependsOn:
        - LogStart
        - DeployCoordinator
        - DeployPdfGenerator
        - DeployTextGenerator
        - DeploySpa
        - DeployGateway
        - DeployAuthHandover
  
  - template: ../templates/stages/status-checks-codebase.yml
    parameters:
      stageBuildAgent: $(dev-build-agent)
      stageDependsOn: Deploy_DEV
      envLabel: "Dev"
      targetLabel: "DEV"
      targetName: "Codebase CI Status Checks"
      appInsightsKey: "$(innovation-development-app-insights-instrumentation-key)"
      coordinatorStatusUrl: $(dev-coordinator-status-url)
      pdfGeneratorStatusUrl: $(dev-pdf-generator-status-url)
      textExtractorStatusUrl: $(dev-text-extractor-status-url)
      authHandoverStatusUrl: $(dev-auth-handover-status-url)
      gatewayStatusUrl: $(dev-gateway-status-url)
      proxyStatusUrl: $(dev-proxy-status-url)
      spaStatusUrl: $(dev-ui-status-url)
      statusCheckMethod: $(status-check-method)
      statusCheckRetries: $(status-check-retries)
      statusCheckDelaySeconds: $(status-check-delay-seconds)
      statusCheckTimeoutSeconds: $(status-check-timeout-seconds)
      devOpsPatToken: "$(devops-pat-token)"
      logResultDependsOn:
        - LogStart
        - CheckCoordinator
        - CheckPDFGenerator
        - CheckTextExtractor
        - CheckAuthHandover
        - CheckGateway
        - CheckSPA
  
  - template: ../templates/stages/run-e2e-tests.yml
    parameters:
      stageBuildAgent: $(dev-build-agent)
      targetLabel: "DEV"
      buildDefinitionId: 129
      appInsightsKey: "$(innovation-development-app-insights-instrumentation-key)"
      devOpsPatToken: "$(devops-pat-token)"
      
  - template: ../templates/stages/deploy-codebase.yml
    parameters:
      stageBuildAgent: $(qa-build-agent)
      stageDependsOn: Run_e2e_Tests_DEV
      envLabel: "QA"
      targetLabel: "QA"
      targetName: "Codebase CI Deployment"
      targetSuffix: "-qa"
      appInsightsKey: "$(innovation-qa-app-insights-instrumentation-key)"
      azureSubscription: $(qa-azure-subscription)
      devOpsPatToken: "$(devops-pat-token)"
      logResultDependsOn:
        - LogStart
        - DeployCoordinator
        - DeployPdfGenerator
        - DeployTextGenerator
        - DeploySpa
        - DeployGateway
        - DeployAuthHandover

  - template: ../templates/stages/status-checks-codebase.yml
    parameters:
      stageBuildAgent: $(qa-build-agent)
      stageDependsOn: Deploy_QA
      envLabel: "QA"
      targetLabel: "QA"
      targetName: "Codebase CI Status Checks"
      appInsightsKey: "$(innovation-qa-app-insights-instrumentation-key)"
      coordinatorStatusUrl: $(qa-coordinator-status-url)
      pdfGeneratorStatusUrl: $(qa-pdf-generator-status-url)
      textExtractorStatusUrl: $(qa-text-extractor-status-url)
      authHandoverStatusUrl: $(qa-auth-handover-status-url)
      gatewayStatusUrl: $(qa-gateway-status-url)
      proxyStatusUrl: $(qa-proxy-status-url)
      spaStatusUrl: $(qa-ui-status-url)
      statusCheckMethod: $(status-check-method)
      statusCheckRetries: $(status-check-retries)
      statusCheckDelaySeconds: $(status-check-delay-seconds)
      statusCheckTimeoutSeconds: $(status-check-timeout-seconds)
      devOpsPatToken: "$(devops-pat-token)"
      logResultDependsOn:
        - LogStart
        - CheckCoordinator
        - CheckPDFGenerator
        - CheckTextExtractor
        - CheckAuthHandover
        - CheckGateway
        - CheckSPA

  - template: ../templates/stages/run-e2e-tests.yml
    parameters:
      stageBuildAgent: $(qa-build-agent)
      targetLabel: "QA"
      buildDefinitionId: 210
      appInsightsKey: "$(innovation-qa-app-insights-instrumentation-key)"
      devOpsPatToken: "$(devops-pat-token)"
      
  - template: ../templates/stages/deploy-codebase.yml
    parameters:
      stageBuildAgent: $(prod-build-agent)
      stageDependsOn: Run_e2e_Tests_QA
      envLabel: "Prod"
      targetLabel: "PROD"
      targetName: "Codebase CI Deployment"
      targetSuffix: ""
      appInsightsKey: "$(innovation-prod-app-insights-instrumentation-key)"
      azureSubscription: $(prod-azure-subscription)
      devOpsPatToken: "$(devops-pat-token)"
      logResultDependsOn:
        - LogStart
        - DeployCoordinator
        - DeployPdfGenerator
        - DeployTextGenerator
        - DeploySpa
        - DeployGateway
        - DeployAuthHandover

  - template: ../templates/stages/status-checks-codebase.yml
    parameters:
      stageBuildAgent: $(prod-build-agent)
      stageDependsOn: Deploy_PROD
      envLabel: "Prod"
      targetLabel: "PROD"
      targetName: "Codebase CI Status Checks"
      appInsightsKey: "$(innovation-prod-app-insights-instrumentation-key)"
      coordinatorStatusUrl: $(prod-coordinator-status-url)
      pdfGeneratorStatusUrl: $(prod-pdf-generator-status-url)
      textExtractorStatusUrl: $(prod-text-extractor-status-url)
      authHandoverStatusUrl: $(prod-auth-handover-status-url)
      gatewayStatusUrl: $(prod-gateway-status-url)
      proxyStatusUrl: $(prod-proxy-status-url)
      spaStatusUrl: $(prod-ui-status-url)
      statusCheckMethod: $(status-check-method)
      statusCheckRetries: $(status-check-retries)
      statusCheckDelaySeconds: $(status-check-delay-seconds)
      statusCheckTimeoutSeconds: $(status-check-timeout-seconds)
      devOpsPatToken: "$(devops-pat-token)"
      logResultDependsOn:
        - LogStart
        - CheckCoordinator
        - CheckPDFGenerator
        - CheckTextExtractor
        - CheckAuthHandover
        - CheckGateway
        - CheckSPA

  - template: ../templates/stages/run-e2e-tests.yml
    parameters:
      stageBuildAgent: $(prod-build-agent)
      targetLabel: "PROD"
      buildDefinitionId: 240
      appInsightsKey: "$(innovation-prod-app-insights-instrumentation-key)"
      devOpsPatToken: "$(devops-pat-token)"