// <copyright file="GlobalSuppressions.cs" company="TheCrownProsecutionService">
// Copyright (c) The Crown Prosecution Service. All rights reserved.
// </copyright>

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Limits testability", Scope = "member", Target = "~M:Cps.Fct.Hk.Ui.Services.BulkSetUnusedService.DetermineStatus(System.Collections.Concurrent.ConcurrentDictionary{System.Int32,Cps.Fct.Hk.Ui.Interfaces.Model.FailedMaterial},System.Collections.Concurrent.ConcurrentDictionary{System.Int32,Cps.Fct.Hk.Ui.Interfaces.Model.ReclassifiedMaterial})~System.String")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Limits testability", Scope = "member", Target = "~M:Cps.Fct.Hk.Ui.Services.BulkSetUnusedService.GenerateMessage(System.Collections.Concurrent.ConcurrentDictionary{System.Int32,Cps.Fct.Hk.Ui.Interfaces.Model.FailedMaterial},System.Collections.Concurrent.ConcurrentDictionary{System.Int32,Cps.Fct.Hk.Ui.Interfaces.Model.ReclassifiedMaterial})~System.String")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Limits testability", Scope = "member", Target = "~M:Cps.Fct.Hk.Ui.Services.DocumentService.UrlEncodeFilePath(System.String)~System.String")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Limits testability", Scope = "member", Target = "~M:Cps.Fct.Hk.Ui.Services.ConversionService.IsRasterImage(System.String)~System.Boolean")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Limits testability", Scope = "member", Target = "~M:Cps.Fct.Hk.Ui.Services.JwtValidator.ValidateJwtToken(System.String)~System.IdentityModel.Tokens.Jwt.JwtSecurityToken")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Limits testability", Scope = "member", Target = "~M:Cps.Fct.Hk.Ui.Services.JwtValidator.GetCertificateFromBase64(System.String)~System.Security.Cryptography.X509Certificates.X509Certificate2")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Limits testability", Scope = "member", Target = "~M:Cps.Fct.Hk.Ui.Services.JwtValidator.GetRsaPublicKey(System.Security.Cryptography.X509Certificates.X509Certificate2)~System.Security.Cryptography.RSA")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Limits testability", Scope = "member", Target = "~M:Cps.Fct.Hk.Ui.Services.JwtValidator.ExtractX5cFromJwks(System.String,System.String)~System.String")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Limits testability", Scope = "member", Target = "~M:Cps.Fct.Hk.Ui.Services.JwtValidator.GetKidFromToken(System.String)~System.String")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1009:Closing parenthesis should be spaced correctly", Justification = "Conflicts with different warning", Scope = "member", Target = "~M:Cps.Fct.Hk.Ui.Services.JwtValidator.GetKidFromToken(System.String)~System.String")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1009:Closing parenthesis should be spaced correctly", Justification = "Conflicts with different warning", Scope = "member", Target = "~M:Cps.Fct.Hk.Ui.Services.JwtValidator.ExtractX5cFromJwks(System.String,System.String)~System.String")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Limits testability", Scope = "member", Target = "~M:Cps.Fct.Hk.Ui.Services.JwtValidator.CreateValidationParameters(System.String,System.String,System.Security.Cryptography.RSA)~Microsoft.IdentityModel.Tokens.TokenValidationParameters")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1010:Opening square brackets should be spaced correctly", Justification = "Conflcits with diferent warning", Scope = "member", Target = "~M:Cps.Fct.Hk.Ui.Services.ConversionService.ConvertPdfToPdfDocumentAsync(System.String,System.Boolean)~System.Threading.Tasks.Task{System.String}")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1011:Closing square brackets should be spaced correctly", Justification = "Conflcits with diferent warning", Scope = "member", Target = "~M:Cps.Fct.Hk.Ui.Services.CaseActionPlanService.AddCaseActionPlanAsync(System.Int32,Cps.Fct.Hk.Ui.Interfaces.Model.CmsAuthValues,Cps.Fct.Hk.Ui.Interfaces.Model.AddCaseActionPlanRequest)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.NoContentResult}")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1011:Closing square brackets should be spaced correctly", Justification = "Conflcits with diferent warning", Scope = "member", Target = "~M:Cps.Fct.Hk.Ui.Services.CaseActionPlanService.AddCaseActionPlanAsync(System.Int32,Cps.Fct.Hk.Ui.Interfaces.Model.AddCaseActionPlanRequest,Cps.Fct.Hk.Ui.Interfaces.Model.CmsAuthValues)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.NoContentResult}")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1011:Closing square brackets should be spaced correctly", Justification = "Conflcits with diferent warning", Scope = "member", Target = "~M:Cps.Fct.Hk.Ui.Services.CaseActionPlanService.AddCaseActionPlanAsync(System.String,System.Int32,Cps.Fct.Hk.Ui.Interfaces.Model.AddCaseActionPlanRequest,Cps.Fct.Hk.Ui.Interfaces.Model.CmsAuthValues)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.NoContentResult}")]
