---
parameters:
  - name: targetBuild
    type: string
  - name: targetLabel
    type: string
  - name: appInsightsKey
    type: string
  - name: environments
    type: object
    default: [] #expects an object with values for name, targetLabel and buildDefinitionId
  
stages:
  - stage: Schedule_Releases
    displayName: Schedule Releases
    dependsOn: Run_e2e_Tests
    condition: succeeded()
    jobs:
      - job: Log_Start
        displayName: Log Start
        condition: succeeded()
        steps:
          - template: jobs/tasks/task_log-start.yml
            parameters:
              targetBuild: ${{ parameters.targetBuild }}
              targetLabel: ${{ parameters.targetLabel }}
              targetName: "Schedule Releases"
              appInsightsKey: ${{ parameters.appInsightsKey }}

      - ${{ each env in parameters.environments }}:
        - job: Schedule_Release_${{ env.name }}
          condition: succeeded()
          dependsOn: Log_Start
          steps:
            - template: jobs/tasks/task_schedule-release.yml
              parameters:
                targetLabel: ${{ env.targetLabel }}
                buildDefinitionId: ${{ env.buildDefinitionId }}
                devOpsPatToken: $(System.AccessToken)

      - job: Log_Result
        condition: succeeded()
        displayName: Log End
        dependsOn:
          - Log_Start
          - ${{ each env in parameters.environments }}:
              - Schedule_Release_${{ env.name }}
        steps:
          - template: jobs/tasks/task_log-result.yml
            parameters:
              targetBuild: ${{ parameters.targetBuild }}
              targetLabel: ${{ parameters.targetLabel }}
              targetName: "Schedule Releases"
              appInsightsKey: ${{ parameters.appInsightsKey }}
              devOpsPatToken: $(System.AccessToken)