---

stages:
  - stage: Publish_Artifacts
    displayName: Publish Pipeline Scripts
    jobs:
      - job: Build_Pipeline_Scripts
        steps:
          - task: PublishPipelineArtifact@1
            displayName: "Publish pipeline scripts"
            inputs:
              targetPath: "$(Pipeline.Workspace)/s/polaris-devops-pipelines/scripts"
              artifact: "polaris-script-files"
              publishLocation: "pipeline"

      - job: Build_Coordinator_Artifact
        steps:
          - task: DotNetCoreCLI@2
            inputs:
              command: publish
              publishWebProjects: false
              projects: "polaris-pipeline/coordinator/coordinator.csproj"
              arguments: "--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory) /p:Version=$(Build.BuildNumber) /p:SourceRevisionId=$(Build.SourceVersion)"
              zipAfterPublish: false
            displayName: "Build Coordinator artifact"
          
          # Add build version
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              workingDirectory: '$(Build.ArtifactStagingDirectory)/coordinator'
              script: |
                New-Item build-version.txt -force
                $currentDate = Get-Date
                Set-Content build-version.txt "{`"name`":`"Coordinator`",`"buildVersion`":`"$(Build.BuildNumber)`",`"sourceVersion`":`"$(Build.SourceVersion)`",`"lastBuilt`":`"$currentDate`"}"
            displayName: "Record version details"

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: "$(Build.ArtifactStagingDirectory)/coordinator"
              artifact: "polaris-coordinator-drop"
            displayName: "Publish Coordinator artifact"
