parameters:
  - name: targetBuild
    type: string
  - name: targetLabel
    type: string
  - name: appInsightsKey
    type: string
  - name: stageDependsOn
    type: object
  - name: polarisGatewayUri
    type: string
  - name: cmsProxyUri
    type: string
  - name: cmsUsername
    type: string
  - name: cmsPassword
    type: string
  - name: tokenAuthUri
    type: string
  - name: clientId
    type: string
  - name: grantType
    type: string
  - name: scope
    type: string
  - name: clientSecret
    type: string
  - name: username
    type: string
  - name: password
    type: string
  
stages:
  - stage: Run_Integration_Tests
    displayName: Integration tests
    dependsOn: ${{ parameters.stageDependsOn }}
    condition: succeeded()
    jobs:
      - job: Log_Start
        displayName: Log Start
        condition: succeeded()
        steps:
          - template: jobs/tasks/task_log-start.yml
            parameters:
              targetBuild: ${{ parameters.targetBuild }}
              targetLabel: ${{ parameters.targetLabel }}
              targetName: "Integration Tests"
              appInsightsKey: ${{ parameters.appInsightsKey }}

      - job: Run_Integration_Tests
        condition: succeeded()
        dependsOn: Log_Start
        steps:
          - template: jobs/tasks/task_run-integration-tests.yml
            parameters:
              project: "polaris-gateway.integration-tests/polaris-gateway.integration-tests.csproj"
              arguments: >
                --configuration Release
                /p:CollectCoverage=true
                /p:CoverletOutputFormat=cobertura
                --settings polaris-gateway.integration-tests/test.runsettings
                --
                TestRunParameters.Parameter(name="\""PolarisGatewayUri"\"", value="\""${{ parameters.polarisGatewayUri }}"\"")
                TestRunParameters.Parameter(name="\""CmsProxyUri"\"", value="\""${{ parameters.cmsProxyUri }}"\"")
                TestRunParameters.Parameter(name="\""CmsUsername"\"", value="\""${{ parameters.cmsUsername }}"\"")
                TestRunParameters.Parameter(name="\""CmsPassword"\"", value="\""${{ parameters.cmsPassword }}"\"")
                TestRunParameters.Parameter(name="\""TokenAuthUri"\"", value="\""${{ parameters.tokenAuthUri }}"\"")
                TestRunParameters.Parameter(name="\""ClientId"\"", value="\""${{ parameters.clientId }}"\"")
                TestRunParameters.Parameter(name="\""GrantType"\"", value="\""${{ parameters.grantType }}"\"")
                TestRunParameters.Parameter(name="\""Scope"\"", value="\""${{ parameters.scope }}"\"")
                TestRunParameters.Parameter(name="\""ClientSecret"\"", value="\""${{ parameters.clientSecret }}"\"")
                TestRunParameters.Parameter(name="\""Username"\"", value="\""${{ parameters.username }}"\"")
                TestRunParameters.Parameter(name="\""Password"\"", value="\""${{ parameters.password }}"\"")'

      - job: Log_Result
        condition: succeeded()
        displayName: Log End
        dependsOn:
          - Log_Start
          - Run_Integration_Tests
        steps:
          - template: jobs/tasks/task_log-result.yml
            parameters:
              targetBuild: ${{ parameters.targetBuild }}
              targetLabel: ${{ parameters.targetLabel }}
              targetName: "Integration Tests"
              appInsightsKey: ${{ parameters.appInsightsKey }}
              devOpsPatToken: $(System.AccessToken)
