using System.Collections.Generic;
using PolarisAuthHandover.Domain.CaseData;

namespace PolarisAuthHandover.Domain.StaticData
{
    public static class DocumentCmsTypes
    {
        public static IEnumerable<DocumentCmsType> GetDocumentCmsTypes
        {
            get
            {
                var documentCmsTypes = new List<DocumentCmsType>{
                    new DocumentCmsType(100004,"1","rer32r32r2r"),
                    new DocumentCmsType(100011,"1111","1111"),
                    new DocumentCmsType(100156,"1111233446","OR78888888OR788888888or788888888or788888888OR78888"),
                    new DocumentCmsType(100200,"123","123455"),
                    new DocumentCmsType(100196,"1230","test code"),
                    new DocumentCmsType(100183,"1234","Test Demo2"),
                    new DocumentCmsType(100212,"12345ATEST","ATEST"),
                    new DocumentCmsType(100053,"18850test","ortest"),
                    new DocumentCmsType(100076,"18929logo","one"),
                    new DocumentCmsType(100090,"2nd","2nd"),
                    new DocumentCmsType(100178,"3452","test demop"),
                    new DocumentCmsType(100182,"5478","Test Demo"),
                    new DocumentCmsType(100165,"AA","BB"),
                    new DocumentCmsType(100153,"AAAAARGH","AAAAARGH!"),
                    new DocumentCmsType(100154,"AAARGHmk2","AAARGHmk2"),
                    new DocumentCmsType(100102,"AATEST","AATEST1"),
                    new DocumentCmsType(1201,"ABE","ABE"),
                    new DocumentCmsType(100209,"ABSDDDD","New test document"),
                    new DocumentCmsType(1,"AD01","Initial Details of the Prosecution Case"),
                    new DocumentCmsType(100140,"ANew£$%%$","ANew"),
                    new DocumentCmsType(100112,"AP RG2","AP RG2"),
                    new DocumentCmsType(100034,"AP4 CMS","AP4 CMS"),
                    new DocumentCmsType(100083,"AP4 LMTest","AP4 LMTest"),
                    new DocumentCmsType(100040,"AP4 One","AP4 One"),
                    new DocumentCmsType(100099,"AP4 Three","AP4 Three"),
                    new DocumentCmsType(100108,"AP4 ThreeZ","AP4 ThreeZ"),
                    new DocumentCmsType(100038,"AP4 Two","AP4 Two"),
                    new DocumentCmsType(100107,"AP4 Two1","AP4 Two1"),
                    new DocumentCmsType(100051,"AP4 WMStwo","AP4 WMStwo"),
                    new DocumentCmsType(100109,"AP4 Z 1","AP4 Z 1"),
                    new DocumentCmsType(100110,"AP4 Zwms2","AP4 Zwms2"),
                    new DocumentCmsType(100113,"AP4RG3","AR4RG3"),
                    new DocumentCmsType(100041,"AP4WMS One","AP4WMS One"),
                    new DocumentCmsType(117,"AR01","Discharge Order"),
                    new DocumentCmsType(118,"AR02","Consent Order - Shares"),
                    new DocumentCmsType(119,"AR03","Consent Order - House"),
                    new DocumentCmsType(120,"AR04","Consent Order - Car"),
                    new DocumentCmsType(121,"AR05","Ex-Parte Variation Order"),
                    new DocumentCmsType(122,"AR06","Restraint Order"),
                    new DocumentCmsType(123,"AR07","Order of alternative service"),
                    new DocumentCmsType(124,"AR08","Statement for Mgt Receiver"),
                    new DocumentCmsType(125,"AR09","Mgt Receivership Order"),
                    new DocumentCmsType(126,"AR10","Restraint Application"),
                    new DocumentCmsType(127,"AR11","Confirmation of service form"),
                    new DocumentCmsType(128,"AR12","Letter to Land Registry"),
                    new DocumentCmsType(129,"AR13","Receivership Order"),
                    new DocumentCmsType(130,"AR14","Brief to Counsel to Appoint Receiver"),
                    new DocumentCmsType(131,"AR15","SIS of Receivership Order"),
                    new DocumentCmsType(132,"AR16","Statement of Service"),
                    new DocumentCmsType(133,"AR17","NTC Criminal Lifestyle"),
                    new DocumentCmsType(134,"AR18","NTC not Criminal Lifestyle"),
                    new DocumentCmsType(161,"ASW","Area Staff Workbook"),
                    new DocumentCmsType(100190,"AW1","AW1"),
                    new DocumentCmsType(100084,"Adamtest","Adamtest"),
                    new DocumentCmsType(100097,"Alice","Alice"),
                    new DocumentCmsType(152,"BCE01","Bad Character - Non-Defendant Application"),
                    new DocumentCmsType(153,"BCE02","Bad Character - Defendant Notice"),
                    new DocumentCmsType(195,"BCE03","Bad Character Non-Defendant Objection Notice"),
                    new DocumentCmsType(154,"BCE04","App adduce non-def's BC (CC)"),
                    new DocumentCmsType(155,"BCE05","Notice intent adduce BC (CC)"),
                    new DocumentCmsType(156,"BCE07","App adduce non-def's BC (CA)"),
                    new DocumentCmsType(157,"BCE08","Notice intent adduce BC (CA)"),
                    new DocumentCmsType(100155,"Boom","Boom"),
                    new DocumentCmsType(227,"CAP01","Case Action Plan"),
                    new DocumentCmsType(184,"CBO1","Notice of Intent to Apply for SCPO (post con)"),
                    new DocumentCmsType(185,"CBO2","Notice of Intent to Apply for ASBO (post con)"),
                    new DocumentCmsType(2,"CCA01","Crown Court Acquittal"),
                    new DocumentCmsType(37,"CCCP01","Outline of Allegations"),
                    new DocumentCmsType(3,"CCCP05","Prosecution Advocate Brief"),
                    new DocumentCmsType(4,"CCCP08","Brief Backsheet"),
                    new DocumentCmsType(5,"CCCP09","Statement/Evidence List"),
                    new DocumentCmsType(6,"CCCP12","Exhibit List"),
                    new DocumentCmsType(7,"CCCP15","Index to Unused Material"),
                    new DocumentCmsType(8,"CCCP17","S41 Schedule"),
                    new DocumentCmsType(83,"CCCP23A","Covering Letter (Court)"),
                    new DocumentCmsType(84,"CCCP23B","Covering Letter (Defence)"),
                    new DocumentCmsType(85,"CCCP23C","Covering Letter (Police)"),
                    new DocumentCmsType(10,"CCCP24","Form14a"),
                    new DocumentCmsType(11,"CCCP25","Form 14a Reply Form"),
                    new DocumentCmsType(100173,"CCR4561","CCR4561"),
                    new DocumentCmsType(100175,"CCR4561","CCR4561"),
                    new DocumentCmsType(100176,"CCR4561B","CCR4561B"),
                    new DocumentCmsType(99,"CD1","Consent Form"),
                    new DocumentCmsType(20,"CFS01","CFS Brief"),
                    new DocumentCmsType(12,"CFS02","CFS Back Sheet"),
                    new DocumentCmsType(100123,"CHADD2","CHADD2"),
                    new DocumentCmsType(191,"CHS01","Case History Sheet"),
                    new DocumentCmsType(162,"CMP","Case Management Panel Briefing"),
                    new DocumentCmsType(201,"CMPSCR","CMP/Sensitive Case Referral"),
                    new DocumentCmsType(13,"CMS01","Indictment"),
                    new DocumentCmsType(188,"CMS01a","Indictment (CCC)"),
                    new DocumentCmsType(14,"CMS10","DCV Letter"),
                    new DocumentCmsType(15,"CMS11","Meeting - Family"),
                    new DocumentCmsType(16,"CMS12","Meeting - Victim"),
                    new DocumentCmsType(17,"CMS13","ESMM Request"),
                    new DocumentCmsType(18,"CMS21","Transfer Letter (Def)"),
                    new DocumentCmsType(19,"CMS22","Transfer Letter (MC)"),
                    new DocumentCmsType(21,"CMS25","A/C Brief"),
                    new DocumentCmsType(22,"CMS26","A/S Brief"),
                    new DocumentCmsType(23,"CMS27","Note to Counsel"),
                    new DocumentCmsType(511,"CMS27a","Note to Counsel"),
                    new DocumentCmsType(24,"CMS28","Undertaking (Cover Letter)"),
                    new DocumentCmsType(25,"CMS30","Undertaking Discharged"),
                    new DocumentCmsType(26,"CMS33","Remitted Case"),
                    new DocumentCmsType(89,"CMS34P","Charge Label (Portrait)"),
                    new DocumentCmsType(91,"CMS36P","Advice Label (Portrait)"),
                    new DocumentCmsType(97,"CMS37L","Appeal Label (Landscape)"),
                    new DocumentCmsType(98,"CMS38L","Crown Court Label (Landscape)"),
                    new DocumentCmsType(32,"CMS39","Victim Letter"),
                    new DocumentCmsType(33,"CMS40","Defendant Letter"),
                    new DocumentCmsType(34,"CMS41","Court (MC) Letter"),
                    new DocumentCmsType(136,"CMS41b","Court (CC) Letter"),
                    new DocumentCmsType(35,"CMS42","General Letter"),
                    new DocumentCmsType(36,"CMS43","Further Charges"),
                    new DocumentCmsType(38,"CMS45","Lodge Indictment"),
                    new DocumentCmsType(39,"CMS46","Judge's bundle (cover)"),
                    new DocumentCmsType(40,"CMS47","Defence bundle (cover)"),
                    new DocumentCmsType(41,"CMS48","Prelim Hearing (cover)"),
                    new DocumentCmsType(42,"CMS49","Adverse Outcome Form"),
                    new DocumentCmsType(43,"CMS50","Advice to Police"),
                    new DocumentCmsType(44,"CMS51","Dewarn Memo"),
                    new DocumentCmsType(45,"CMS52","S9 Court Notice"),
                    new DocumentCmsType(46,"CMS53","S51 Schedule"),
                    new DocumentCmsType(47,"CMS54","PSR(CC)"),
                    new DocumentCmsType(105,"CMS55","Schedule of Charges"),
                    new DocumentCmsType(111,"CMS56","Victim - Insufficient Evidence"),
                    new DocumentCmsType(112,"CMS57","Victim - Not in Public Interest"),
                    new DocumentCmsType(113,"CMS58","Witness Summons - Memo to Police"),
                    new DocumentCmsType(114,"CMS59","Witness Summons - MC Letter"),
                    new DocumentCmsType(115,"CMS60","Witness Summons - CC Letter"),
                    new DocumentCmsType(174,"CMS61","Archive Box Label"),
                    new DocumentCmsType(100160,"CN2","CN2"),
                    new DocumentCmsType(48,"CNATV01","TV Link Application (CNATV01)"),
                    new DocumentCmsType(49,"CNAV01","Video Application (CNAV01)"),
                    new DocumentCmsType(100252,"COA BT Inactive","Court of Appeal Brief - local TEST inactive"),
                    new DocumentCmsType(100253,"COA BT TEST","Court of Appeal Brief-local TEST"),
                    new DocumentCmsType(178,"CP1-Def","Application Covering Letter (Defence)"),
                    new DocumentCmsType(204,"CP2-Def","Letter of Application(Defence)"),
                    new DocumentCmsType(205,"CP3-Crt","Letter of Application(Court)"),
                    new DocumentCmsType(50,"CPIA01","Primary - items"),
                    new DocumentCmsType(145,"CPIA01 (pre Apr05)","Primary - items (pre Apr05)"),
                    new DocumentCmsType(51,"CPIA02","Primary - no items"),
                    new DocumentCmsType(146,"CPIA02 (pre Apr05)","Primary - no items (pre Apr05)"),
                    new DocumentCmsType(52,"CPIA03","Def Statement to Police"),
                    new DocumentCmsType(147,"CPIA03 (pre Apr05)","Def Statement to Police (pre Apr05)"),
                    new DocumentCmsType(53,"CPIA04","Secondary - items"),
                    new DocumentCmsType(148,"CPIA04 (pre Apr05)","Secondary - items (pre Apr05)"),
                    new DocumentCmsType(54,"CPIA05","Secondary - no items"),
                    new DocumentCmsType(149,"CPIA05 (pre Apr05)","Secondary - no items (pre Apr05)"),
                    new DocumentCmsType(55,"CPIA06","Copy MG6C to Police"),
                    new DocumentCmsType(150,"CPIA06 (pre Apr05)","Copy MG6C to Police (pre Apr05)"),
                    new DocumentCmsType(56,"CPIA07","Request hearing - court"),
                    new DocumentCmsType(151,"CPIA07 (pre Apr05)","Request hearing - court (pre Apr05)"),
                    new DocumentCmsType(220,"CPIA1 (CC)","Initial - Disclosure (CC)"),
                    new DocumentCmsType(138,"CPIA1 (MC)","Initial - Disclosure (MC)"),
                    new DocumentCmsType(221,"CPIA2 (CC)","Initial - No Disclosure (CC)"),
                    new DocumentCmsType(139,"CPIA2 (MC)","Initial - No Disclosure (MC)"),
                    new DocumentCmsType(140,"CPIA3","Def Statement to Police"),
                    new DocumentCmsType(141,"CPIA4","Ongoing - Disclosure"),
                    new DocumentCmsType(142,"CPIA4a","Inadequate Def Statement"),
                    new DocumentCmsType(143,"CPIA5","Ongoing - No Disclosure"),
                    new DocumentCmsType(144,"CPIA6","Copy MG6c to Police"),
                    new DocumentCmsType(100232,"CPIA8","Disclosure Management Document - Crown Court"),
                    new DocumentCmsType(226015,"CPIA8","Disclosure Management Document - Crown Court"),
                    new DocumentCmsType(186,"CPR3","Application for a Witness Summons"),
                    new DocumentCmsType(100,"CPSLogo","LetterheadLogo"),
                    new DocumentCmsType(57,"CTL01","CTL Extension Notice"),
                    new DocumentCmsType(58,"CTL02","CTL Extension - Defence Letter"),
                    new DocumentCmsType(59,"CTL03","CTL Extension - Listing Office"),
                    new DocumentCmsType(109,"CTL04","CTL Extension Appeal"),
                    new DocumentCmsType(108,"CVR02","Undertaking"),
                    new DocumentCmsType(60,"CVT01","Transcript Request (CVT01)"),
                    new DocumentCmsType(100122,"ChaaDD","Chaadd"),
                    new DocumentCmsType(100157,"ChambersNa","ChambersNa"),
                    new DocumentCmsType(100213,"CodeTFS1770","CodeTFS1770"),
                    new DocumentCmsType(100058,"DA2Z3TEST2","DA2Z3TEST2NAME"),
                    new DocumentCmsType(100101,"DAMYD11","ZZDAMYDC11"),
                    new DocumentCmsType(100052,"DAMYDOC1","DAMYDOC1NAME"),
                    new DocumentCmsType(100059,"DAONE11","DAONE11NAME"),
                    new DocumentCmsType(100071,"DATEM100","DATEM100NAME"),
                    new DocumentCmsType(100092,"DATEST1","ZZLOGOTEST"),
                    new DocumentCmsType(100056,"DAZ2TEST","DAZ2TEST"),
                    new DocumentCmsType(100057,"DAZ3TEST","DAZ3TESTNAME"),
                    new DocumentCmsType(100085,"DB test","Db test"),
                    new DocumentCmsType(1064,"DCF","Digital Case File"),
                    new DocumentCmsType(231,"DCF_BB_D","DCF Breach of Bail"),
                    new DocumentCmsType(232,"DCF_BB_N","DCF Breach of Bail Remand Application"),
                    new DocumentCmsType(229,"DCF_FH_D","DCF First Hearing"),
                    new DocumentCmsType(230,"DCF_FH_N","DCF First Hearing Remand Application"),
                    new DocumentCmsType(1065,"DCS-R","DCS Document Received"),
                    new DocumentCmsType(100230,"DDE1","Defence Engagement Log"),
                    new DocumentCmsType(100103,"DDTEST1","TEST1"),
                    new DocumentCmsType(100177,"DEF111","DEFENCE1"),
                    new DocumentCmsType(206,"DEFRAINF","Information"),
                    new DocumentCmsType(211,"DEFRALET","Summons/S9 Letter"),
                    new DocumentCmsType(207,"DEFRALIC","Laying in Court"),
                    new DocumentCmsType(208,"DEFRAREP","Prosecutor Report"),
                    new DocumentCmsType(209,"DEFRAS9","Section 9"),
                    new DocumentCmsType(210,"DEFRASUM","Summons"),
                    new DocumentCmsType(197,"DGCC","Conditional Caution Authority"),
                    new DocumentCmsType(198,"DGYCC","Youth Conditional Caution Authority"),
                    new DocumentCmsType(222,"DIRCT","Directions Letter (Court)"),
                    new DocumentCmsType(223,"DIRDEF","Directions Letter (Defence)"),
                    new DocumentCmsType(61,"DN01","Disc Notice (Police)"),
                    new DocumentCmsType(62,"DN02","Dropped/LOF (Police)"),
                    new DocumentCmsType(63,"DN03","Disc Notice (MC)"),
                    new DocumentCmsType(64,"DN04","Disc Notice (Defence)"),
                    new DocumentCmsType(202,"DN09","Disc Notice (Prison)"),
                    new DocumentCmsType(65,"DP01","Proposed Discontinuance"),
                    new DocumentCmsType(1055,"DREP","DREP"),
                    new DocumentCmsType(137,"DRS","Disclosure Record Sheet"),
                    new DocumentCmsType(66,"DVM1","DVM1"),
                    new DocumentCmsType(116,"DVM4","DVM4"),
                    new DocumentCmsType(216,"DWPCPO","CPO Letter"),
                    new DocumentCmsType(215,"DWPCPR","Client Prosecution Report"),
                    new DocumentCmsType(213,"DWPDISC1","Case Discontinued"),
                    new DocumentCmsType(214,"DWPDISC2","Client Discontinuance"),
                    new DocumentCmsType(217,"DWPPR","Prosecution Report"),
                    new DocumentCmsType(67,"DWR01","S51 Notice (Def)"),
                    new DocumentCmsType(100065,"Dave","Dave"),
                    new DocumentCmsType(100121,"Def Sols","Defence Sols"),
                    new DocumentCmsType(100126,"DefDOB1","DefDOB1"),
                    new DocumentCmsType(100118,"DefDOBTest","DefDOBTEST"),
                    new DocumentCmsType(100119,"Defs DOB","Defendants and DOB"),
                    new DocumentCmsType(100120,"Defs DOB2","Defs DOB 2"),
                    new DocumentCmsType(100239,"EG3","Egress Unused Disclosed MME"),
                    new DocumentCmsType(226148,"EG3","Egress Unused Disclosed MME"),
                    new DocumentCmsType(100241,"FEE202","Updated Case Management Record for CCDs"),
                    new DocumentCmsType(100240,"FEES01","Crown Court Fee Log"),
                    new DocumentCmsType(163,"FIST2","Fees Information Sheet"),
                    new DocumentCmsType(100198,"Fantasy2","Fantasy2"),
                    new DocumentCmsType(100199,"Fantasy3","Fantasy3"),
                    new DocumentCmsType(100116,"Friday","Friday"),
                    new DocumentCmsType(164,"HFCC1","Notify Heavy Fraud/Complex Case"),
                    new DocumentCmsType(228,"HR","Hearing Record"),
                    new DocumentCmsType(225,"HRS-CC","Hearing Record Sheet - Crown Court"),
                    new DocumentCmsType(224,"HRS-MC","Hearing Record Sheet - Magistrates Court"),
                    new DocumentCmsType(1032,"HTE","Forwarded Internal Email"),
                    new DocumentCmsType(190,"KDAR01","Key Decision and Action Record"),
                    new DocumentCmsType(200,"LLA","Live Link Application"),
                    new DocumentCmsType(100181,"LM1SMOKE","New05NOV"),
                    new DocumentCmsType(100104,"LMTemp","Local temp CoverLetterLM"),
                    new DocumentCmsType(100247,"LOC03","Local-test-document"),
                    new DocumentCmsType(100248,"LOC4-test","Local-doc-test"),
                    new DocumentCmsType(100226,"LOCALTEMPLATENS","Local Template Non-Sensitive Unit"),
                    new DocumentCmsType(100228,"LOCALTEMPLATENS","Local Template in SFD proxy"),
                    new DocumentCmsType(100227,"LOCALTEMPLATENS","Local Template in SFD Unit"),
                    new DocumentCmsType(100225,"LOCALTEMPLATES","Local Template in Sensitive Unit"),
                    new DocumentCmsType(100245,"Local Template01","POC3"),
                    new DocumentCmsType(100077,"Logo&Text","OR18929"),
                    new DocumentCmsType(199,"MCTP","Magistrates' Court Case Management Form"),
                    new DocumentCmsType(1066,"MG 00","MG00"),
                    new DocumentCmsType(1001,"MG 1","MG1"),
                    new DocumentCmsType(1015,"MG 10","MG10"),
                    new DocumentCmsType(1031,"MG 11","MG11"),
                    new DocumentCmsType(1016,"MG 11(CONT)","MG11(CONT)"),
                    new DocumentCmsType(1059,"MG 11(R)","MG11(R)"),
                    new DocumentCmsType(1017,"MG 11(T)","MG11(T)"),
                    new DocumentCmsType(1018,"MG 11T(CONT)","MG11T(CONT)"),
                    new DocumentCmsType(1019,"MG 12","MG12"),
                    new DocumentCmsType(1040,"MG 13","MG13"),
                    new DocumentCmsType(1041,"MG 14","MG14"),
                    new DocumentCmsType(1062,"MG 15(CNOI)","MG15(CNOI)"),
                    new DocumentCmsType(1021,"MG 15(CONT)","MG15(CONT)"),
                    new DocumentCmsType(1020,"MG 15(ROTI)","MG15(ROTI)"),
                    new DocumentCmsType(1044,"MG 15(ROVI)","MG15(ROVI)"),
                    new DocumentCmsType(1042,"MG 15(SDN)","MG15(SDN)"),
                    new DocumentCmsType(1022,"MG 15(T)","MG15(T)"),
                    new DocumentCmsType(1023,"MG 15(T)(CONT)","MG15(T)(CONT)"),
                    new DocumentCmsType(1063,"MG 16","MG16"),
                    new DocumentCmsType(1045,"MG 16(DBCI)","MG16(DBCI)"),
                    new DocumentCmsType(1046,"MG 16(DDOI)","MG16(DDOI)"),
                    new DocumentCmsType(1047,"MG 17","MG17"),
                    new DocumentCmsType(1024,"MG 18","MG18"),
                    new DocumentCmsType(1033,"MG 2","MG2"),
                    new DocumentCmsType(1026,"MG 20","MG20"),
                    new DocumentCmsType(1048,"MG 21","MG21"),
                    new DocumentCmsType(1049,"MG 21A","MG21A"),
                    new DocumentCmsType(1034,"MG 3","MG3"),
                    new DocumentCmsType(1035,"MG 3A","MG3A"),
                    new DocumentCmsType(1002,"MG 4","MG4"),
                    new DocumentCmsType(1037,"MG 4(Post)","MG4(Post)"),
                    new DocumentCmsType(1003,"MG 4A","MG4A"),
                    new DocumentCmsType(1004,"MG 4B","MG4B"),
                    new DocumentCmsType(1005,"MG 4C","MG4C"),
                    new DocumentCmsType(1060,"MG 4D","MG4D"),
                    new DocumentCmsType(1061,"MG 4E","MG4E"),
                    new DocumentCmsType(1036,"MG 4F","MG4F"),
                    new DocumentCmsType(1006,"MG 5","MG5"),
                    new DocumentCmsType(1038,"MG 5(SP)","MG5(SP)"),
                    new DocumentCmsType(1039,"MG 6A","MG6A"),
                    new DocumentCmsType(1008,"MG 6B","MG6B"),
                    new DocumentCmsType(1009,"MG 6C","MG6C"),
                    new DocumentCmsType(1010,"MG 6D","MG6D"),
                    new DocumentCmsType(1011,"MG 6E","MG6E"),
                    new DocumentCmsType(1012,"MG 7","MG7"),
                    new DocumentCmsType(1013,"MG 8","MG8"),
                    new DocumentCmsType(1014,"MG 9","MG9"),
                    new DocumentCmsType(1027,"MG/FSS A","MG/FSS A"),
                    new DocumentCmsType(1028,"MG/FSS B","MG/FSS B"),
                    new DocumentCmsType(516,"MG17","MG17"),
                    new DocumentCmsType(1025,"MG19","MG19"),
                    new DocumentCmsType(1203,"MG22 SFR","MG22 SFR"),
                    new DocumentCmsType(101,"MG3","MG3"),
                    new DocumentCmsType(102,"MG3A","MG3A"),
                    new DocumentCmsType(104,"MG3AS","MG3A (with Schedule of Charges)"),
                    new DocumentCmsType(103,"MG3S","MG3 (with Schedule of Charges)"),
                    new DocumentCmsType(1007,"MG6","MG6"),
                    new DocumentCmsType(1050,"MGDD","MGDD"),
                    new DocumentCmsType(69,"MIC01","MIC1"),
                    new DocumentCmsType(100082,"MSCTEST","TEST2"),
                    new DocumentCmsType(100055,"MYDOC10","MYDOC10NAME"),
                    new DocumentCmsType(100187,"MoreNeeds","MoreNeeds"),
                    new DocumentCmsType(70,"NEA01","Offer No Evidence (CC)"),
                    new DocumentCmsType(71,"NFE01","Notice Further Evidence"),
                    new DocumentCmsType(72,"NFE02","Letter (CC)"),
                    new DocumentCmsType(73,"NFE03","Letter (Police)"),
                    new DocumentCmsType(74,"NFE04","Letter (Def)"),
                    new DocumentCmsType(175,"NFR-CCF1","Report to Supervising Lawyer"),
                    new DocumentCmsType(176,"NFR-CCF2","Case Diary Plan"),
                    new DocumentCmsType(177,"NFR-CCF3","Case Activity Log"),
                    new DocumentCmsType(158,"NFR-HE1","Hearsay Notice"),
                    new DocumentCmsType(159,"NFR-HE2","Hearsay Exclusion Application after Notice"),
                    new DocumentCmsType(196,"NFR-HE3","Hearsay Exclusion Application without Notice"),
                    new DocumentCmsType(517,"NFR-PS1","Plea and Sentence"),
                    new DocumentCmsType(100115,"NH2","NH2"),
                    new DocumentCmsType(75,"NT01","Form 1 Notice (CC)"),
                    new DocumentCmsType(76,"NT02","Form 2 Notice (Def)"),
                    new DocumentCmsType(77,"NT03","Consent Form (Custody)"),
                    new DocumentCmsType(100186,"Needs","needs"),
                    new DocumentCmsType(100074,"OR18929","Check"),
                    new DocumentCmsType(100075,"OR18929-2","Both Logo and text"),
                    new DocumentCmsType(100161,"OR19559","OR19559 Test"),
                    new DocumentCmsType(1030,"OTHER EXHIBIT","Other Exhibit"),
                    new DocumentCmsType(1200,"OTHER MATERIAL","Other Material"),
                    new DocumentCmsType(1056,"PCN 1","PCN1"),
                    new DocumentCmsType(1057,"PCN 2","PCN2"),
                    new DocumentCmsType(1058,"PCN 3","PCN3"),
                    new DocumentCmsType(218,"PCREng","Requisition (English)"),
                    new DocumentCmsType(219,"PCRWel","Requisition (Welsh)"),
                    new DocumentCmsType(1051,"PE 1","PE1"),
                    new DocumentCmsType(1052,"PE 2","PE2"),
                    new DocumentCmsType(1053,"PE 3","PE3"),
                    new DocumentCmsType(1054,"PE 4","PE4"),
                    new DocumentCmsType(100235,"PFD01","Protection of Children - Request for Disc"),
                    new DocumentCmsType(225583,"PFD01","Protection of Children - Request for Disc"),
                    new DocumentCmsType(100234,"PFD02-","Standard Request for Police Information"),
                    new DocumentCmsType(225584,"PFD02-","Standard Request for Police Information"),
                    new DocumentCmsType(100236,"PFD03","Notice to Local Auth - CPIA Disclosure Test"),
                    new DocumentCmsType(225581,"PFD03","Notice to Local Auth - CPIA Disclosure Test"),
                    new DocumentCmsType(100233,"PFD04","Notice from Local Auth - Representations on Disc"),
                    new DocumentCmsType(225582,"PFD04","Notice from Local Auth - Representations on Disc"),
                    new DocumentCmsType(100204,"PJM1","Paula"),
                    new DocumentCmsType(100214,"PLEA1","PLEA1"),
                    new DocumentCmsType(100242,"POC01","Proceeds of Crime"),
                    new DocumentCmsType(100251,"POC02-new","POC02-local"),
                    new DocumentCmsType(100244,"POL02","Proceeds of Crime-local"),
                    new DocumentCmsType(68,"POL1","Police Memo"),
                    new DocumentCmsType(110,"POL2","Pre-charge Police Memo"),
                    new DocumentCmsType(160,"POL3","Quick Police Memo"),
                    new DocumentCmsType(203,"PRMB","Post Review Meeting Briefing"),
                    new DocumentCmsType(78,"PSR","PSR (MC)"),
                    new DocumentCmsType(183,"PSR02","PSR (CC)"),
                    new DocumentCmsType(100224,"PTPH","PTPH Form"),
                    new DocumentCmsType(100223,"PTPH-RG1","Test PTPH Final"),
                    new DocumentCmsType(100215,"PTPH1","Plea and Trial Hearing Form"),
                    new DocumentCmsType(100216,"PTPH2","Plea and Trial Preparation Hearing Form 2"),
                    new DocumentCmsType(100217,"PTPH3","Plea and Trial Hearing Form 1"),
                    new DocumentCmsType(100218,"PTPH5","Plea and Trial Preparation Hearing Form"),
                    new DocumentCmsType(100221,"PTPH6","PTPH DCS RP"),
                    new DocumentCmsType(100222,"PTPHTest","PTPH Final Version"),
                    new DocumentCmsType(100016,"Pre-Deploy","Pre-Deploy"),
                    new DocumentCmsType(100243,"Proceeds of Crime","POC01"),
                    new DocumentCmsType(189,"REV1","Review Document"),
                    new DocumentCmsType(212,"REVIEW","Standard Review"),
                    new DocumentCmsType(100219,"RG1","PTPH Test"),
                    new DocumentCmsType(100220,"RG2","PTPH Test DCS"),
                    new DocumentCmsType(79,"RID1","RID1"),
                    new DocumentCmsType(181,"RP1","Rape Prosecution Essential Steps Monitoring"),
                    new DocumentCmsType(182,"RP2","Rape Pros Decision Making Quality Monitoring"),
                    new DocumentCmsType(512,"RRA01","Reporting Restrictions (MC)"),
                    new DocumentCmsType(513,"RRA02","Reporting Restrictions (CC)"),
                    new DocumentCmsType(100141,"Rubbish","Rubbish"),
                    new DocumentCmsType(80,"S9","S9 Notice"),
                    new DocumentCmsType(100067,"SB AP4 Two","SB AP4 Two"),
                    new DocumentCmsType(81,"SC01","Schedule of Charges"),
                    new DocumentCmsType(1202,"SDC","Streamlined Disclosure Certificate"),
                    new DocumentCmsType(100068,"SJB AP4 Tw","SJB Ap4 Two"),
                    new DocumentCmsType(100249,"SMOKE 04MAR","New 04MAR"),
                    new DocumentCmsType(100237,"SMOKE0502","New0502"),
                    new DocumentCmsType(100130,"SMOKE1","Local Doc"),
                    new DocumentCmsType(100149,"SMOKE1","New18JUN"),
                    new DocumentCmsType(100139,"SMOKE11","New17MAY"),
                    new DocumentCmsType(100150,"SMOKE2","new19JUN"),
                    new DocumentCmsType(100162,"SMOKE2","New09JUL"),
                    new DocumentCmsType(100151,"SMOKE2a","44731"),
                    new DocumentCmsType(100194,"SMOKEE1","New25Oct"),
                    new DocumentCmsType(100238,"SMOKEe0502","NEWNEW0502"),
                    new DocumentCmsType(100231,"STWAC01","Record Conversation(s) with Witnesses"),
                    new DocumentCmsType(100020,"Stephen28","Stephen28"),
                    new DocumentCmsType(100060,"TEAM","TESTING"),
                    new DocumentCmsType(100001,"TEMP1","Local Temp CoverLetter"),
                    new DocumentCmsType(100129,"TEMP1a","Local Temp Cover Letter"),
                    new DocumentCmsType(100002,"TEMP2","Local Temp CoverLetter2"),
                    new DocumentCmsType(100179,"TEMP2","Local Temp CoverLetter"),
                    new DocumentCmsType(100094,"TEST","ZZLHTEST"),
                    new DocumentCmsType(100246,"TEST-LOCAL_doc","LOCAL-DOC"),
                    new DocumentCmsType(100229,"TESTWW","TESTWW"),
                    new DocumentCmsType(100202,"TFS1126","Abbrev. no.space def. and charg."),
                    new DocumentCmsType(100203,"TFS1127","Abbrev. no.space def. and charg."),
                    new DocumentCmsType(100018,"TH01","Template1"),
                    new DocumentCmsType(100019,"THA02","Temp2forTestingMissingTemplates"),
                    new DocumentCmsType(100000,"Test","Test"),
                    new DocumentCmsType(100180,"Test temp2","Local temp coverletter test"),
                    new DocumentCmsType(100189,"TestDot","AW"),
                    new DocumentCmsType(100152,"TestExplos","TestExplosion"),
                    new DocumentCmsType(1029,"UNKNOWN","Other Comm (In)"),
                    new DocumentCmsType(100069,"URNx","URNx"),
                    new DocumentCmsType(180,"VFS1","Victim Focus Scheme"),
                    new DocumentCmsType(165,"VHCC1","Advice/Pre-send Reduced Scheme"),
                    new DocumentCmsType(166,"VHCC2","Higher Court Reduced Scheme"),
                    new DocumentCmsType(167,"VHCC3","Advice/Pre-send Full Scheme"),
                    new DocumentCmsType(168,"VHCC4","Crown Court Case"),
                    new DocumentCmsType(169,"VHCC5","Higher Court Full Scheme"),
                    new DocumentCmsType(170,"VHCC6","Crown Court Fee Scheme"),
                    new DocumentCmsType(171,"VHCC7","Magistrates' Court Case"),
                    new DocumentCmsType(172,"VHCC8","VHCC - Stage Plan"),
                    new DocumentCmsType(173,"VHCC9","VHCC - Case Plan"),
                    new DocumentCmsType(514,"VIW01","Record of ESM Meeting"),
                    new DocumentCmsType(515,"VIW02","Record of Prosecutors Meeting"),
                    new DocumentCmsType(86,"VIW03","Special Measures Application (MC)"),
                    new DocumentCmsType(87,"VIW04","Special Measures Application (CC)"),
                    new DocumentCmsType(88,"VIW05","Transcript Request (VIW05)"),
                    new DocumentCmsType(106,"VIW07","Special Measures Extension Applic"),
                    new DocumentCmsType(107,"VIW08","Special Measures Applic Out of Time"),
                    new DocumentCmsType(187,"VIW11","Special Measures Application (MC/CC)"),
                    new DocumentCmsType(100117,"WCU","WCU"),
                    new DocumentCmsType(82,"WEF04","LWAC"),
                    new DocumentCmsType(135,"WEF04(Cont)","LWAC Continuation"),
                    new DocumentCmsType(179,"WEFLabel","Witness Expense Form Labels"),
                    new DocumentCmsType(226,"WIH01","Witnesses In Hearing"),
                    new DocumentCmsType(10002,"WMS-B1","Introduction - no PMoC identified"),
                    new DocumentCmsType(10011,"WMS-B10","Def on Warrant"),
                    new DocumentCmsType(100211,"WMS-B10","blobby"),
                    new DocumentCmsType(10509,"WMS-B10G","Def on Warrant (Guardian)"),
                    new DocumentCmsType(10609,"WMS-B10GW","Def on Warrant (G) (W)"),
                    new DocumentCmsType(10028,"WMS-B10W","Def on Warrant (Welsh)"),
                    new DocumentCmsType(10012,"WMS-B11","Guilty Plea - Adj For Sentence"),
                    new DocumentCmsType(10510,"WMS-B11G","Guilty Plea - Adj For Sentence (Guardian)"),
                    new DocumentCmsType(10610,"WMS-B11GW","Guilty Plea - Adj For Sentence (G) (W)"),
                    new DocumentCmsType(10029,"WMS-B11W","Guilty Plea - Adj For Sentence (Welsh)"),
                    new DocumentCmsType(10013,"WMS-B12","Guilty Plea - Def Sentenced"),
                    new DocumentCmsType(10511,"WMS-B12G","Guilty Plea - Def Sentenced (Guardian)"),
                    new DocumentCmsType(10611,"WMS-B12GW","Guilty Plea - Def Sentenced (G) (W)"),
                    new DocumentCmsType(10030,"WMS-B12W","Guilty Plea - Def Sentenced (Welsh)"),
                    new DocumentCmsType(10014,"WMS-B13","Conviction After Trial - Adj For Sentence"),
                    new DocumentCmsType(10512,"WMS-B13G","Conviction After Trial - Adj For Sentence (G)"),
                    new DocumentCmsType(10612,"WMS-B13GW","Conviction After Trial - Adj For Sentence (G) (W)"),
                    new DocumentCmsType(10031,"WMS-B13W","Conviction After Trial - Adj For Sentence (Welsh)"),
                    new DocumentCmsType(10015,"WMS-B14","Conviction After Trial - Def Sentenced"),
                    new DocumentCmsType(10513,"WMS-B14G","Conviction After Trial - Def Sentenced (Guardian)"),
                    new DocumentCmsType(10613,"WMS-B14GW","Conviction After Trial - Def Sentenced (G) (W)"),
                    new DocumentCmsType(10032,"WMS-B14W","Conviction After Trial - Def Sentenced (Welsh)"),
                    new DocumentCmsType(10016,"WMS-B15","Not Guilty After Trial"),
                    new DocumentCmsType(10514,"WMS-B15G","Not Guilty After Trial (Guardian)"),
                    new DocumentCmsType(10614,"WMS-B15GW","Not Guilty After Trial (G) (W)"),
                    new DocumentCmsType(10033,"WMS-B15W","Not Guilty After Trial (Welsh)"),
                    new DocumentCmsType(10500,"WMS-B1G","Introduction - no PMoC identified  (Guardian)"),
                    new DocumentCmsType(10600,"WMS-B1GW","Introduction - no PMoC identified  (G) (W)"),
                    new DocumentCmsType(10019,"WMS-B1W","Introduction - no PMoC identified (Welsh)"),
                    new DocumentCmsType(10003,"WMS-B2","Introduction - PMoC letter"),
                    new DocumentCmsType(10020,"WMS-B2W","Introduction - PMoC letter (Welsh)"),
                    new DocumentCmsType(10004,"WMS-B3","Introduction - PMoC telephone"),
                    new DocumentCmsType(10021,"WMS-B3W","Introduction - PMoC telephone (Welsh)"),
                    new DocumentCmsType(10005,"WMS-B4","Guilty Plea and Sentence at First Hearing"),
                    new DocumentCmsType(10501,"WMS-B4G","Guilty Plea and Sentence First Hearing (Guardian)"),
                    new DocumentCmsType(10601,"WMS-B4GW","Guilty Plea and Sentence First Hearing (G) (W)"),
                    new DocumentCmsType(10022,"WMS-B4W","Guilty Plea and Sentence at First Hearing (Welsh)"),
                    new DocumentCmsType(10006,"WMS-B5","Not Guilty Plea at First Hearing"),
                    new DocumentCmsType(10502,"WMS-B5G","Not Guilty Plea at First Hearing (Guardian)"),
                    new DocumentCmsType(10602,"WMS-B5GW","Not Guilty Plea at First Hearing (G) (W)"),
                    new DocumentCmsType(10023,"WMS-B5W","Not Guilty Plea at First Hearing (Welsh)"),
                    new DocumentCmsType(10007,"WMS-B6","Availability for Trial"),
                    new DocumentCmsType(10503,"WMS-B6G","Availability for Trial (Guardian)"),
                    new DocumentCmsType(10603,"WMS-B6GW","Availability for Trial (G) (W)"),
                    new DocumentCmsType(10024,"WMS-B6W","Availability for Trial (Welsh)"),
                    new DocumentCmsType(10008,"WMS-B7","Witness Warning - MC"),
                    new DocumentCmsType(10504,"WMS-B7G","Witness Warning - MC (Guardian)"),
                    new DocumentCmsType(10604,"WMS-B7GW","Witness Warning - MC (G) (W)"),
                    new DocumentCmsType(10025,"WMS-B7W","Witness Warning - MC (Welsh)"),
                    new DocumentCmsType(10009,"WMS-B8","Witness Warning - CC"),
                    new DocumentCmsType(10505,"WMS-B8G","Witness Warning - CC (Guardian)"),
                    new DocumentCmsType(10605,"WMS-B8GW","Witness Warning - CC (G) (W)"),
                    new DocumentCmsType(10506,"WMS-B8R","Witness Warning - CC (Reserve)"),
                    new DocumentCmsType(10507,"WMS-B8RG","Witness Warning - CC ( Reserve Guardian)"),
                    new DocumentCmsType(10607,"WMS-B8RGW","Witness Warning - CC ( Reserve Guardian) (W)"),
                    new DocumentCmsType(10606,"WMS-B8RW","Witness Warning - CC (Reserve) (W)"),
                    new DocumentCmsType(10026,"WMS-B8W","Witness Warning - CC (Welsh)"),
                    new DocumentCmsType(10010,"WMS-B9","Attendance Not Required at Court"),
                    new DocumentCmsType(10508,"WMS-B9G","Attendance Not Required at Court  (Guardian)"),
                    new DocumentCmsType(10608,"WMS-B9GW","Attendance Not Required at Court  (G) (W)"),
                    new DocumentCmsType(10027,"WMS-B9W","Attendance Not Required at Court (Welsh)"),
                    new DocumentCmsType(10517,"WMS-GU","General update - Case"),
                    new DocumentCmsType(10518,"WMS-GUG","General update - Case (Guardian)"),
                    new DocumentCmsType(10618,"WMS-GUGW","General update - Case (G) (W)"),
                    new DocumentCmsType(10617,"WMS-GUW","General update - Case (W)"),
                    new DocumentCmsType(10018,"WMS-LogoLeft","LetterheadLogoLeft"),
                    new DocumentCmsType(10017,"WMS-LogoRight","LetterheadLogoRight"),
                    new DocumentCmsType(10515,"WMS-PWLC","Requirement to attend court - Crown"),
                    new DocumentCmsType(10516,"WMS-PWLM","Requirement to attend court - Magistrates"),
                    new DocumentCmsType(10034,"WMS-WEFLabel","Witness Expense Form Labels"),
                    new DocumentCmsType(10001,"WMS001","Blank Needs Assessment Form"),
                    new DocumentCmsType(100135,"Witness99","Witness99"),
                    new DocumentCmsType(100061,"Z2TEST1","TEST11"),
                    new DocumentCmsType(100188,"ZNeeds","ZNeeds"),
                    new DocumentCmsType(100127,"ZZDEF1","ZZDEF1NAME"),
                    new DocumentCmsType(100128,"ZZDEF2","ZZDEF2NAME"),
                    new DocumentCmsType(100210,"ZZ_A","ZZ_A_NAME"),
                    new DocumentCmsType(100205,"ZZ_BD18","ZZ_BD18test"),
                    new DocumentCmsType(100145,"a1","a1"),
                    new DocumentCmsType(100144,"a11","a11"),
                    new DocumentCmsType(100148,"a1b","a1b"),
                    new DocumentCmsType(100146,"a2","s2"),
                    new DocumentCmsType(100159,"aOr19513","aOr19513"),
                    new DocumentCmsType(100208,"aaa","aaaaarrow"),
                    new DocumentCmsType(100191,"aaaaa","aaaaa"),
                    new DocumentCmsType(100133,"aaaaaa","aaaaaa"),
                    new DocumentCmsType(100012,"aaaaaaaa","bbbbbb"),
                    new DocumentCmsType(100005,"aaaaaaaaaa","aaaaaaaaaa"),
                    new DocumentCmsType(100105,"aaacode","zortest"),
                    new DocumentCmsType(100132,"aazacube","aazacube"),
                    new DocumentCmsType(100131,"aazcube","aazcube"),
                    new DocumentCmsType(100171,"abacode","abarcode"),
                    new DocumentCmsType(100134,"abc","abc"),
                    new DocumentCmsType(100137,"abtest","abtest"),
                    new DocumentCmsType(100048,"ap4 test","ap4 test"),
                    new DocumentCmsType(100172,"aplam","aplam"),
                    new DocumentCmsType(100039,"apt 4 thre","ap4 thre"),
                    new DocumentCmsType(100158,"atemplateN","atemplatfgtrgfredsefghhjjkkkll"),
                    new DocumentCmsType(100138,"awms","awms"),
                    new DocumentCmsType(100006,"bbbbb","bbbbb"),
                    new DocumentCmsType(100142,"bottom","bottom"),
                    new DocumentCmsType(100007,"ccc","ccc"),
                    new DocumentCmsType(100174,"ccr4561","ccr4561"),
                    new DocumentCmsType(100080,"cha","cha"),
                    new DocumentCmsType(100081,"cha1","cha1"),
                    new DocumentCmsType(100125,"chacourt","chacourt"),
                    new DocumentCmsType(100124,"chadd2","chadd2"),
                    new DocumentCmsType(100035,"cmsap4","cmsap4"),
                    new DocumentCmsType(100147,"con","con"),
                    new DocumentCmsType(100079,"createddat","createddate"),
                    new DocumentCmsType(100066,"d2","d2"),
                    new DocumentCmsType(100014,"datr","dater"),
                    new DocumentCmsType(100086,"db1","db1"),
                    new DocumentCmsType(100091,"db1","db1"),
                    new DocumentCmsType(100087,"dbwithtext","dbwithtext"),
                    new DocumentCmsType(100072,"dc","dc"),
                    new DocumentCmsType(100008,"dddd","dddd"),
                    new DocumentCmsType(100184,"fantasy","fantasy"),
                    new DocumentCmsType(100164,"jgtemp1","jglocal temp cover letter"),
                    new DocumentCmsType(100043,"m1","m1"),
                    new DocumentCmsType(100044,"m11","m11"),
                    new DocumentCmsType(100042,"ma1","ma1"),
                    new DocumentCmsType(100073,"new boy","newboy"),
                    new DocumentCmsType(100078,"none","none"),
                    new DocumentCmsType(100088,"noneincl","noneincl"),
                    new DocumentCmsType(100089,"noneincl","noneincl"),
                    new DocumentCmsType(100054,"or18850","test"),
                    new DocumentCmsType(100136,"rach1","rach1"),
                    new DocumentCmsType(100163,"rachel","rachel"),
                    new DocumentCmsType(100143,"red","red"),
                    new DocumentCmsType(192,"s51(Ct)","s51 Cover (Court)"),
                    new DocumentCmsType(193,"s51(Def)","s51 Cover (Defence)"),
                    new DocumentCmsType(194,"s51(Pol)","s51 Cover (Police)"),
                    new DocumentCmsType(100197,"sdfsd","sdfsdfsdf"),
                    new DocumentCmsType(100195,"smoke6","new28oct"),
                    new DocumentCmsType(100167,"ssss","ssss"),
                    new DocumentCmsType(100021,"stephen29","zzz10"),
                    new DocumentCmsType(100207,"sum","sum"),
                    new DocumentCmsType(100049,"systemtest","systemtest"),
                    new DocumentCmsType(100250,"temp","local temp cover letter"),
                    new DocumentCmsType(100010,"temp1","Local Temp Cover letter"),
                    new DocumentCmsType(100093,"temp12","TempLocalCoverLetter2"),
                    new DocumentCmsType(100050,"template","template"),
                    new DocumentCmsType(100045,"test2010","test20"),
                    new DocumentCmsType(100046,"test20101","test20101"),
                    new DocumentCmsType(100192,"tst spc ch","Test on 17/10/2013"),
                    new DocumentCmsType(100193,"tst- ash","Ashley doc on 17/10"),
                    new DocumentCmsType(100070,"ttttcode","ttttname"),
                    new DocumentCmsType(100063,"urn","urn"),
                    new DocumentCmsType(100064,"urn2","urn2"),
                    new DocumentCmsType(100003,"uy","u6"),
                    new DocumentCmsType(100013,"w","q"),
                    new DocumentCmsType(100206,"xtl","xtl"),
                    new DocumentCmsType(100095,"xx19119","xx19119"),
                    new DocumentCmsType(100166,"xxx","xxxx"),
                    new DocumentCmsType(100062,"xyz","xyz"),
                    new DocumentCmsType(100009,"yygygyyhy","vytfty"),
                    new DocumentCmsType(100017,"yyy","yyy"),
                    new DocumentCmsType(100025,"z1","z1"),
                    new DocumentCmsType(100100,"z1","z1"),
                    new DocumentCmsType(100028,"z10","z10 word2010 bc"),
                    new DocumentCmsType(100029,"z11","2010 template"),
                    new DocumentCmsType(100026,"z2","z2"),
                    new DocumentCmsType(100033,"z55","z55"),
                    new DocumentCmsType(100027,"z9","z9"),
                    new DocumentCmsType(100114,"zRevCat","zRevCat"),
                    new DocumentCmsType(100185,"zdec","zdec"),
                    new DocumentCmsType(100106,"zortest","zortest"),
                    new DocumentCmsType(100201,"zpaula","zpaula"),
                    new DocumentCmsType(100111,"zubairtest","zubairtest"),
                    new DocumentCmsType(100036,"zz","zz"),
                    new DocumentCmsType(100098,"zz A4 One","zz AP4 One"),
                    new DocumentCmsType(100096,"zz AP4 Two","zz AP4 Two"),
                    new DocumentCmsType(100030,"zz11","zz11 2010 template"),
                    new DocumentCmsType(100032,"zzStephen2","zzStephen2"),
                    new DocumentCmsType(100031,"zzstephen","zzstephen"),
                    new DocumentCmsType(100037,"zzz","zzz"),
                    new DocumentCmsType(100015,"zzz","zzz"),
                    new DocumentCmsType(100022,"zzzurn2","zzzurn2"),
                    new DocumentCmsType(100023,"zzzurn3","zzzurn3"),
                    new DocumentCmsType(100024,"zzzzz","zzzzz"),
                    new DocumentCmsType(100047,"zzzzz1999","zzzzz1999"),
                };

                return documentCmsTypes;
            }
        }
    }
}