# Build and Publish Artifact Azure DevOps pipeline for Polaris Terraform and Codebase

name: '$(majorMinorVersion).$(Year:yy)$(DayOfYear).$(semanticVersion)-ci'

trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - polaris-terraform/proxy-terraform/*
       
pr: none
  
variables:
  - group: polaris-global
  - name: buildConfiguration
    value: "Release"
  - name: majorMinorVersion
    value: "1.0"
  - name: semanticVersion
    value: "$[counter(variables['majorMinorVersion'], 1)]"
    
pool:
  name: $(dev-build-agent)
  
stages:
  - stage: Publish_Artifacts
    displayName: Publish artifacts
    jobs:
      - job: Build_Artifacts
        steps:
          - task: PublishPipelineArtifact@1
            displayName: "Publish pipeline scripts"
            inputs:
              targetPath: "$(Pipeline.Workspace)/s/polaris-devops-pipelines/scripts"
              artifact: "polaris-script-files"
              publishLocation: "pipeline"
              
          - task: PublishPipelineArtifact@1
            displayName: 'Publish pipeline templates'
            inputs:
              targetPath: '$(Pipeline.Workspace)/s/polaris-devops-pipelines/templates'
              artifact: 'polaris-template-files'
              publishLocation: 'pipeline'
              
          - task: PublishPipelineArtifact@1
            displayName: 'Publish Proxy terraform artifact'
            inputs:
              targetPath: '$(Pipeline.Workspace)/s/polaris-terraform/proxy-terraform/'
              artifact: 'proxy-terraform-files'
              publishLocation: 'pipeline'